#!/bin/sh

set -eux
XML="$1"
xml2 <"$XML" | tr -d "\t" | 2csv -d "	" APARTMENTS/APARTMENT @ID @OBJECTID @OBJECTGUID @CHANGEID @NUMBER @APARTTYPE @OPERTYPEID @PREVID @NEXTID @UPDATEDATE @STARTDATE @ENDDATE @ISACTUAL @ISACTIVE >"${XML%.*}.csv"
