CREATE TABLE addr_obj_division (
  id BIGINT NOT NULL PRIMARY KEY,
  parentid BIGINT NOT NULL,
  childid BIGINT NOT NULL,
  changeid BIGINT NOT NULL
);
COMMENT ON TABLE addr_obj_division IS 'Сведения по операциям переподчинения';
COMMENT ON COLUMN addr_obj_division.id IS 'Уникальный идентификатор записи. Ключевое поле';
COMMENT ON COLUMN addr_obj_division.parentid IS 'Родительский ID';
COMMENT ON COLUMN addr_obj_division.childid IS 'Дочерний ID';
COMMENT ON COLUMN addr_obj_division.changeid IS 'ID изменившей транзакции';

CREATE TABLE addr_obj_division_01 (dir SMALLINT NOT NULL DEFAULT 01, CONSTRAINT CHECK (dir = 01)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_02 (dir SMALLINT NOT NULL DEFAULT 02, CONSTRAINT CHECK (dir = 02)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_03 (dir SMALLINT NOT NULL DEFAULT 03, CONSTRAINT CHECK (dir = 03)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_04 (dir SMALLINT NOT NULL DEFAULT 04, CONSTRAINT CHECK (dir = 04)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_05 (dir SMALLINT NOT NULL DEFAULT 05, CONSTRAINT CHECK (dir = 05)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_06 (dir SMALLINT NOT NULL DEFAULT 06, CONSTRAINT CHECK (dir = 06)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_07 (dir SMALLINT NOT NULL DEFAULT 07, CONSTRAINT CHECK (dir = 07)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_08 (dir SMALLINT NOT NULL DEFAULT 08, CONSTRAINT CHECK (dir = 08)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_09 (dir SMALLINT NOT NULL DEFAULT 09, CONSTRAINT CHECK (dir = 09)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_10 (dir SMALLINT NOT NULL DEFAULT 10, CONSTRAINT CHECK (dir = 10)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_11 (dir SMALLINT NOT NULL DEFAULT 11, CONSTRAINT CHECK (dir = 11)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_12 (dir SMALLINT NOT NULL DEFAULT 12, CONSTRAINT CHECK (dir = 12)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_13 (dir SMALLINT NOT NULL DEFAULT 13, CONSTRAINT CHECK (dir = 13)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_14 (dir SMALLINT NOT NULL DEFAULT 14, CONSTRAINT CHECK (dir = 14)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_15 (dir SMALLINT NOT NULL DEFAULT 15, CONSTRAINT CHECK (dir = 15)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_16 (dir SMALLINT NOT NULL DEFAULT 16, CONSTRAINT CHECK (dir = 16)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_17 (dir SMALLINT NOT NULL DEFAULT 17, CONSTRAINT CHECK (dir = 17)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_18 (dir SMALLINT NOT NULL DEFAULT 18, CONSTRAINT CHECK (dir = 18)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_19 (dir SMALLINT NOT NULL DEFAULT 19, CONSTRAINT CHECK (dir = 19)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_20 (dir SMALLINT NOT NULL DEFAULT 20, CONSTRAINT CHECK (dir = 20)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_21 (dir SMALLINT NOT NULL DEFAULT 21, CONSTRAINT CHECK (dir = 21)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_22 (dir SMALLINT NOT NULL DEFAULT 22, CONSTRAINT CHECK (dir = 22)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_23 (dir SMALLINT NOT NULL DEFAULT 23, CONSTRAINT CHECK (dir = 23)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_24 (dir SMALLINT NOT NULL DEFAULT 24, CONSTRAINT CHECK (dir = 24)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_25 (dir SMALLINT NOT NULL DEFAULT 25, CONSTRAINT CHECK (dir = 25)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_26 (dir SMALLINT NOT NULL DEFAULT 26, CONSTRAINT CHECK (dir = 26)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_27 (dir SMALLINT NOT NULL DEFAULT 27, CONSTRAINT CHECK (dir = 27)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_28 (dir SMALLINT NOT NULL DEFAULT 28, CONSTRAINT CHECK (dir = 28)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_29 (dir SMALLINT NOT NULL DEFAULT 29, CONSTRAINT CHECK (dir = 29)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_30 (dir SMALLINT NOT NULL DEFAULT 30, CONSTRAINT CHECK (dir = 30)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_31 (dir SMALLINT NOT NULL DEFAULT 31, CONSTRAINT CHECK (dir = 31)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_32 (dir SMALLINT NOT NULL DEFAULT 32, CONSTRAINT CHECK (dir = 32)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_33 (dir SMALLINT NOT NULL DEFAULT 33, CONSTRAINT CHECK (dir = 33)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_34 (dir SMALLINT NOT NULL DEFAULT 34, CONSTRAINT CHECK (dir = 34)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_35 (dir SMALLINT NOT NULL DEFAULT 35, CONSTRAINT CHECK (dir = 35)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_36 (dir SMALLINT NOT NULL DEFAULT 36, CONSTRAINT CHECK (dir = 36)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_37 (dir SMALLINT NOT NULL DEFAULT 37, CONSTRAINT CHECK (dir = 37)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_38 (dir SMALLINT NOT NULL DEFAULT 38, CONSTRAINT CHECK (dir = 38)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_39 (dir SMALLINT NOT NULL DEFAULT 39, CONSTRAINT CHECK (dir = 39)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_40 (dir SMALLINT NOT NULL DEFAULT 40, CONSTRAINT CHECK (dir = 40)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_41 (dir SMALLINT NOT NULL DEFAULT 41, CONSTRAINT CHECK (dir = 41)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_42 (dir SMALLINT NOT NULL DEFAULT 42, CONSTRAINT CHECK (dir = 42)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_43 (dir SMALLINT NOT NULL DEFAULT 43, CONSTRAINT CHECK (dir = 43)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_44 (dir SMALLINT NOT NULL DEFAULT 44, CONSTRAINT CHECK (dir = 44)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_45 (dir SMALLINT NOT NULL DEFAULT 45, CONSTRAINT CHECK (dir = 45)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_46 (dir SMALLINT NOT NULL DEFAULT 46, CONSTRAINT CHECK (dir = 46)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_47 (dir SMALLINT NOT NULL DEFAULT 47, CONSTRAINT CHECK (dir = 47)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_48 (dir SMALLINT NOT NULL DEFAULT 48, CONSTRAINT CHECK (dir = 48)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_49 (dir SMALLINT NOT NULL DEFAULT 49, CONSTRAINT CHECK (dir = 49)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_50 (dir SMALLINT NOT NULL DEFAULT 50, CONSTRAINT CHECK (dir = 50)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_51 (dir SMALLINT NOT NULL DEFAULT 51, CONSTRAINT CHECK (dir = 51)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_52 (dir SMALLINT NOT NULL DEFAULT 52, CONSTRAINT CHECK (dir = 52)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_53 (dir SMALLINT NOT NULL DEFAULT 53, CONSTRAINT CHECK (dir = 53)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_54 (dir SMALLINT NOT NULL DEFAULT 54, CONSTRAINT CHECK (dir = 54)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_55 (dir SMALLINT NOT NULL DEFAULT 55, CONSTRAINT CHECK (dir = 55)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_56 (dir SMALLINT NOT NULL DEFAULT 56, CONSTRAINT CHECK (dir = 56)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_57 (dir SMALLINT NOT NULL DEFAULT 57, CONSTRAINT CHECK (dir = 57)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_58 (dir SMALLINT NOT NULL DEFAULT 58, CONSTRAINT CHECK (dir = 58)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_59 (dir SMALLINT NOT NULL DEFAULT 59, CONSTRAINT CHECK (dir = 59)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_60 (dir SMALLINT NOT NULL DEFAULT 60, CONSTRAINT CHECK (dir = 60)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_61 (dir SMALLINT NOT NULL DEFAULT 61, CONSTRAINT CHECK (dir = 61)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_62 (dir SMALLINT NOT NULL DEFAULT 62, CONSTRAINT CHECK (dir = 62)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_63 (dir SMALLINT NOT NULL DEFAULT 63, CONSTRAINT CHECK (dir = 63)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_64 (dir SMALLINT NOT NULL DEFAULT 64, CONSTRAINT CHECK (dir = 64)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_65 (dir SMALLINT NOT NULL DEFAULT 65, CONSTRAINT CHECK (dir = 65)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_66 (dir SMALLINT NOT NULL DEFAULT 66, CONSTRAINT CHECK (dir = 66)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_67 (dir SMALLINT NOT NULL DEFAULT 67, CONSTRAINT CHECK (dir = 67)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_68 (dir SMALLINT NOT NULL DEFAULT 68, CONSTRAINT CHECK (dir = 68)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_69 (dir SMALLINT NOT NULL DEFAULT 69, CONSTRAINT CHECK (dir = 69)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_70 (dir SMALLINT NOT NULL DEFAULT 70, CONSTRAINT CHECK (dir = 70)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_71 (dir SMALLINT NOT NULL DEFAULT 71, CONSTRAINT CHECK (dir = 71)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_72 (dir SMALLINT NOT NULL DEFAULT 72, CONSTRAINT CHECK (dir = 72)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_73 (dir SMALLINT NOT NULL DEFAULT 73, CONSTRAINT CHECK (dir = 73)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_74 (dir SMALLINT NOT NULL DEFAULT 74, CONSTRAINT CHECK (dir = 74)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_75 (dir SMALLINT NOT NULL DEFAULT 75, CONSTRAINT CHECK (dir = 75)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_76 (dir SMALLINT NOT NULL DEFAULT 76, CONSTRAINT CHECK (dir = 76)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_77 (dir SMALLINT NOT NULL DEFAULT 77, CONSTRAINT CHECK (dir = 77)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_78 (dir SMALLINT NOT NULL DEFAULT 78, CONSTRAINT CHECK (dir = 78)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_79 (dir SMALLINT NOT NULL DEFAULT 79, CONSTRAINT CHECK (dir = 79)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_80 (dir SMALLINT NOT NULL DEFAULT 80, CONSTRAINT CHECK (dir = 80)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_81 (dir SMALLINT NOT NULL DEFAULT 81, CONSTRAINT CHECK (dir = 81)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_82 (dir SMALLINT NOT NULL DEFAULT 82, CONSTRAINT CHECK (dir = 82)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_83 (dir SMALLINT NOT NULL DEFAULT 83, CONSTRAINT CHECK (dir = 83)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_84 (dir SMALLINT NOT NULL DEFAULT 84, CONSTRAINT CHECK (dir = 84)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_85 (dir SMALLINT NOT NULL DEFAULT 85, CONSTRAINT CHECK (dir = 85)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_86 (dir SMALLINT NOT NULL DEFAULT 86, CONSTRAINT CHECK (dir = 86)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_87 (dir SMALLINT NOT NULL DEFAULT 87, CONSTRAINT CHECK (dir = 87)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_88 (dir SMALLINT NOT NULL DEFAULT 88, CONSTRAINT CHECK (dir = 88)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_89 (dir SMALLINT NOT NULL DEFAULT 89, CONSTRAINT CHECK (dir = 89)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_90 (dir SMALLINT NOT NULL DEFAULT 90, CONSTRAINT CHECK (dir = 90)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_91 (dir SMALLINT NOT NULL DEFAULT 91, CONSTRAINT CHECK (dir = 91)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_92 (dir SMALLINT NOT NULL DEFAULT 92, CONSTRAINT CHECK (dir = 92)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_93 (dir SMALLINT NOT NULL DEFAULT 93, CONSTRAINT CHECK (dir = 93)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_94 (dir SMALLINT NOT NULL DEFAULT 94, CONSTRAINT CHECK (dir = 94)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_95 (dir SMALLINT NOT NULL DEFAULT 95, CONSTRAINT CHECK (dir = 95)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_96 (dir SMALLINT NOT NULL DEFAULT 96, CONSTRAINT CHECK (dir = 96)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_97 (dir SMALLINT NOT NULL DEFAULT 97, CONSTRAINT CHECK (dir = 97)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_98 (dir SMALLINT NOT NULL DEFAULT 98, CONSTRAINT CHECK (dir = 98)) INHERITS (addr_obj_division);
CREATE TABLE addr_obj_division_99 (dir SMALLINT NOT NULL DEFAULT 99, CONSTRAINT CHECK (dir = 99)) INHERITS (addr_obj_division);
