CREATE TABLE IF NOT EXISTS addr_obj_division (
  id BIGINT NOT NULL PRIMARY KEY,
  parentid BIGINT NOT NULL,
  childid BIGINT NOT NULL,
  changeid BIGINT NOT NULL
);
COMMENT ON TABLE addr_obj_division IS 'Сведения по операциям переподчинения';
COMMENT ON COLUMN addr_obj_division.id IS 'Уникальный идентификатор записи. Ключевое поле';
COMMENT ON COLUMN addr_obj_division.parentid IS 'Родительский ID';
COMMENT ON COLUMN addr_obj_division.childid IS 'Дочерний ID';
COMMENT ON COLUMN addr_obj_division.changeid IS 'ID изменившей транзакции';
CREATE TABLE IF NOT EXISTS addr_obj_division_01 (CONSTRAINT addr_obj_division_01_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_02 (CONSTRAINT addr_obj_division_02_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_03 (CONSTRAINT addr_obj_division_03_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_04 (CONSTRAINT addr_obj_division_04_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_05 (CONSTRAINT addr_obj_division_05_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_06 (CONSTRAINT addr_obj_division_06_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_07 (CONSTRAINT addr_obj_division_07_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_08 (CONSTRAINT addr_obj_division_08_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_09 (CONSTRAINT addr_obj_division_09_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_10 (CONSTRAINT addr_obj_division_10_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_11 (CONSTRAINT addr_obj_division_11_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_12 (CONSTRAINT addr_obj_division_12_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_13 (CONSTRAINT addr_obj_division_13_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_14 (CONSTRAINT addr_obj_division_14_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_15 (CONSTRAINT addr_obj_division_15_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_16 (CONSTRAINT addr_obj_division_16_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_17 (CONSTRAINT addr_obj_division_17_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_18 (CONSTRAINT addr_obj_division_18_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_19 (CONSTRAINT addr_obj_division_19_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_20 (CONSTRAINT addr_obj_division_20_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_21 (CONSTRAINT addr_obj_division_21_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_22 (CONSTRAINT addr_obj_division_22_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_23 (CONSTRAINT addr_obj_division_23_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_24 (CONSTRAINT addr_obj_division_24_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_25 (CONSTRAINT addr_obj_division_25_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_26 (CONSTRAINT addr_obj_division_26_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_27 (CONSTRAINT addr_obj_division_27_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_28 (CONSTRAINT addr_obj_division_28_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_29 (CONSTRAINT addr_obj_division_29_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_30 (CONSTRAINT addr_obj_division_30_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_31 (CONSTRAINT addr_obj_division_31_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_32 (CONSTRAINT addr_obj_division_32_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_33 (CONSTRAINT addr_obj_division_33_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_34 (CONSTRAINT addr_obj_division_34_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_35 (CONSTRAINT addr_obj_division_35_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_36 (CONSTRAINT addr_obj_division_36_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_37 (CONSTRAINT addr_obj_division_37_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_38 (CONSTRAINT addr_obj_division_38_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_39 (CONSTRAINT addr_obj_division_39_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_40 (CONSTRAINT addr_obj_division_40_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_41 (CONSTRAINT addr_obj_division_41_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_42 (CONSTRAINT addr_obj_division_42_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_43 (CONSTRAINT addr_obj_division_43_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_44 (CONSTRAINT addr_obj_division_44_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_45 (CONSTRAINT addr_obj_division_45_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_46 (CONSTRAINT addr_obj_division_46_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_47 (CONSTRAINT addr_obj_division_47_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_48 (CONSTRAINT addr_obj_division_48_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_49 (CONSTRAINT addr_obj_division_49_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_50 (CONSTRAINT addr_obj_division_50_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_51 (CONSTRAINT addr_obj_division_51_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_52 (CONSTRAINT addr_obj_division_52_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_53 (CONSTRAINT addr_obj_division_53_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_54 (CONSTRAINT addr_obj_division_54_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_55 (CONSTRAINT addr_obj_division_55_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_56 (CONSTRAINT addr_obj_division_56_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_57 (CONSTRAINT addr_obj_division_57_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_58 (CONSTRAINT addr_obj_division_58_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_59 (CONSTRAINT addr_obj_division_59_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_60 (CONSTRAINT addr_obj_division_60_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_61 (CONSTRAINT addr_obj_division_61_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_62 (CONSTRAINT addr_obj_division_62_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_63 (CONSTRAINT addr_obj_division_63_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_64 (CONSTRAINT addr_obj_division_64_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_65 (CONSTRAINT addr_obj_division_65_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_66 (CONSTRAINT addr_obj_division_66_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_67 (CONSTRAINT addr_obj_division_67_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_68 (CONSTRAINT addr_obj_division_68_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_69 (CONSTRAINT addr_obj_division_69_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_70 (CONSTRAINT addr_obj_division_70_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_71 (CONSTRAINT addr_obj_division_71_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_72 (CONSTRAINT addr_obj_division_72_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_73 (CONSTRAINT addr_obj_division_73_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_74 (CONSTRAINT addr_obj_division_74_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_75 (CONSTRAINT addr_obj_division_75_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_76 (CONSTRAINT addr_obj_division_76_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_77 (CONSTRAINT addr_obj_division_77_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_78 (CONSTRAINT addr_obj_division_78_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_79 (CONSTRAINT addr_obj_division_79_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_80 (CONSTRAINT addr_obj_division_80_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_81 (CONSTRAINT addr_obj_division_81_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_82 (CONSTRAINT addr_obj_division_82_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_83 (CONSTRAINT addr_obj_division_83_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_84 (CONSTRAINT addr_obj_division_84_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_85 (CONSTRAINT addr_obj_division_85_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_86 (CONSTRAINT addr_obj_division_86_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_87 (CONSTRAINT addr_obj_division_87_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_88 (CONSTRAINT addr_obj_division_88_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_89 (CONSTRAINT addr_obj_division_89_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_90 (CONSTRAINT addr_obj_division_90_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_91 (CONSTRAINT addr_obj_division_91_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_92 (CONSTRAINT addr_obj_division_92_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_93 (CONSTRAINT addr_obj_division_93_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_94 (CONSTRAINT addr_obj_division_94_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_95 (CONSTRAINT addr_obj_division_95_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_96 (CONSTRAINT addr_obj_division_96_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_97 (CONSTRAINT addr_obj_division_97_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_98 (CONSTRAINT addr_obj_division_98_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
CREATE TABLE IF NOT EXISTS addr_obj_division_99 (CONSTRAINT addr_obj_division_99_pkey PRIMARY KEY (id)) INHERITS (addr_obj_division);
