CREATE TABLE IF NOT EXISTS addr_obj (
  id BIGINT NOT NULL PRIMARY KEY,
  objectid BIGINT NOT NULL,
  objectguid UUID NOT NULL,
  changeid BIGINT NOT NULL,
  name VARCHAR(250) NOT NULL,
  typename VARCHAR(50) NOT NULL,
  level INT NOT NULL,
  opertypeid INT NOT NULL,
  previd BIGINT,
  nextid BIGINT,
  updatedate DATE NOT NULL,
  startdate DATE NOT NULL,
  enddate DATE NOT NULL,
  isactual SMALLINT NOT NULL,
  isactive SMALLINT NOT NULL
);
COMMENT ON TABLE addr_obj IS 'Сведения классификатора адресообразующих элементов';
COMMENT ON COLUMN addr_obj.id IS 'Уникальный идентификатор записи. Ключевое поле';
COMMENT ON COLUMN addr_obj.objectid IS 'Глобальный уникальный идентификатор адресного объекта типа INTEGER';
COMMENT ON COLUMN addr_obj.objectguid IS 'Глобальный уникальный идентификатор адресного объекта типа UUID';
COMMENT ON COLUMN addr_obj.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN addr_obj.name IS 'Наименование';
COMMENT ON COLUMN addr_obj.typename IS 'Краткое наименование типа объекта';
COMMENT ON COLUMN addr_obj.level IS 'Уровень адресного объекта';
COMMENT ON COLUMN addr_obj.opertypeid IS 'Статус действия над записью – причина появления записи';
COMMENT ON COLUMN addr_obj.previd IS 'Идентификатор записи связывания с предыдущей исторической записью';
COMMENT ON COLUMN addr_obj.nextid IS 'Идентификатор записи связывания с последующей исторической записью';
COMMENT ON COLUMN addr_obj.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN addr_obj.startdate IS 'Начало действия записи';
COMMENT ON COLUMN addr_obj.enddate IS 'Окончание действия записи';
COMMENT ON COLUMN addr_obj.isactual IS 'Статус актуальности адресного объекта ФИАС';
COMMENT ON COLUMN addr_obj.isactive IS 'Признак действующего адресного объекта';
CREATE INDEX IF NOT EXISTS addr_obj_startdate_idx ON addr_obj USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_enddate_idx ON addr_obj USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_isactual_idx ON addr_obj USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_isactive_idx ON addr_obj USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_01 (CONSTRAINT addr_obj_01_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_01_startdate_idx ON addr_obj_01 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_01_enddate_idx ON addr_obj_01 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_01_isactual_idx ON addr_obj_01 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_01_isactive_idx ON addr_obj_01 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_02 (CONSTRAINT addr_obj_02_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_02_startdate_idx ON addr_obj_02 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_02_enddate_idx ON addr_obj_02 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_02_isactual_idx ON addr_obj_02 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_02_isactive_idx ON addr_obj_02 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_03 (CONSTRAINT addr_obj_03_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_03_startdate_idx ON addr_obj_03 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_03_enddate_idx ON addr_obj_03 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_03_isactual_idx ON addr_obj_03 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_03_isactive_idx ON addr_obj_03 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_04 (CONSTRAINT addr_obj_04_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_04_startdate_idx ON addr_obj_04 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_04_enddate_idx ON addr_obj_04 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_04_isactual_idx ON addr_obj_04 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_04_isactive_idx ON addr_obj_04 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_05 (CONSTRAINT addr_obj_05_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_05_startdate_idx ON addr_obj_05 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_05_enddate_idx ON addr_obj_05 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_05_isactual_idx ON addr_obj_05 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_05_isactive_idx ON addr_obj_05 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_06 (CONSTRAINT addr_obj_06_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_06_startdate_idx ON addr_obj_06 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_06_enddate_idx ON addr_obj_06 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_06_isactual_idx ON addr_obj_06 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_06_isactive_idx ON addr_obj_06 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_07 (CONSTRAINT addr_obj_07_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_07_startdate_idx ON addr_obj_07 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_07_enddate_idx ON addr_obj_07 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_07_isactual_idx ON addr_obj_07 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_07_isactive_idx ON addr_obj_07 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_08 (CONSTRAINT addr_obj_08_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_08_startdate_idx ON addr_obj_08 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_08_enddate_idx ON addr_obj_08 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_08_isactual_idx ON addr_obj_08 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_08_isactive_idx ON addr_obj_08 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_09 (CONSTRAINT addr_obj_09_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_09_startdate_idx ON addr_obj_09 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_09_enddate_idx ON addr_obj_09 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_09_isactual_idx ON addr_obj_09 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_09_isactive_idx ON addr_obj_09 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_10 (CONSTRAINT addr_obj_10_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_10_startdate_idx ON addr_obj_10 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_10_enddate_idx ON addr_obj_10 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_10_isactual_idx ON addr_obj_10 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_10_isactive_idx ON addr_obj_10 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_11 (CONSTRAINT addr_obj_11_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_11_startdate_idx ON addr_obj_11 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_11_enddate_idx ON addr_obj_11 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_11_isactual_idx ON addr_obj_11 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_11_isactive_idx ON addr_obj_11 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_12 (CONSTRAINT addr_obj_12_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_12_startdate_idx ON addr_obj_12 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_12_enddate_idx ON addr_obj_12 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_12_isactual_idx ON addr_obj_12 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_12_isactive_idx ON addr_obj_12 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_13 (CONSTRAINT addr_obj_13_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_13_startdate_idx ON addr_obj_13 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_13_enddate_idx ON addr_obj_13 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_13_isactual_idx ON addr_obj_13 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_13_isactive_idx ON addr_obj_13 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_14 (CONSTRAINT addr_obj_14_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_14_startdate_idx ON addr_obj_14 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_14_enddate_idx ON addr_obj_14 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_14_isactual_idx ON addr_obj_14 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_14_isactive_idx ON addr_obj_14 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_15 (CONSTRAINT addr_obj_15_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_15_startdate_idx ON addr_obj_15 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_15_enddate_idx ON addr_obj_15 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_15_isactual_idx ON addr_obj_15 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_15_isactive_idx ON addr_obj_15 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_16 (CONSTRAINT addr_obj_16_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_16_startdate_idx ON addr_obj_16 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_16_enddate_idx ON addr_obj_16 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_16_isactual_idx ON addr_obj_16 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_16_isactive_idx ON addr_obj_16 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_17 (CONSTRAINT addr_obj_17_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_17_startdate_idx ON addr_obj_17 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_17_enddate_idx ON addr_obj_17 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_17_isactual_idx ON addr_obj_17 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_17_isactive_idx ON addr_obj_17 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_18 (CONSTRAINT addr_obj_18_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_18_startdate_idx ON addr_obj_18 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_18_enddate_idx ON addr_obj_18 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_18_isactual_idx ON addr_obj_18 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_18_isactive_idx ON addr_obj_18 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_19 (CONSTRAINT addr_obj_19_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_19_startdate_idx ON addr_obj_19 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_19_enddate_idx ON addr_obj_19 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_19_isactual_idx ON addr_obj_19 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_19_isactive_idx ON addr_obj_19 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_20 (CONSTRAINT addr_obj_20_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_20_startdate_idx ON addr_obj_20 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_20_enddate_idx ON addr_obj_20 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_20_isactual_idx ON addr_obj_20 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_20_isactive_idx ON addr_obj_20 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_21 (CONSTRAINT addr_obj_21_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_21_startdate_idx ON addr_obj_21 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_21_enddate_idx ON addr_obj_21 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_21_isactual_idx ON addr_obj_21 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_21_isactive_idx ON addr_obj_21 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_22 (CONSTRAINT addr_obj_22_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_22_startdate_idx ON addr_obj_22 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_22_enddate_idx ON addr_obj_22 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_22_isactual_idx ON addr_obj_22 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_22_isactive_idx ON addr_obj_22 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_23 (CONSTRAINT addr_obj_23_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_23_startdate_idx ON addr_obj_23 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_23_enddate_idx ON addr_obj_23 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_23_isactual_idx ON addr_obj_23 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_23_isactive_idx ON addr_obj_23 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_24 (CONSTRAINT addr_obj_24_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_24_startdate_idx ON addr_obj_24 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_24_enddate_idx ON addr_obj_24 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_24_isactual_idx ON addr_obj_24 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_24_isactive_idx ON addr_obj_24 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_25 (CONSTRAINT addr_obj_25_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_25_startdate_idx ON addr_obj_25 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_25_enddate_idx ON addr_obj_25 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_25_isactual_idx ON addr_obj_25 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_25_isactive_idx ON addr_obj_25 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_26 (CONSTRAINT addr_obj_26_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_26_startdate_idx ON addr_obj_26 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_26_enddate_idx ON addr_obj_26 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_26_isactual_idx ON addr_obj_26 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_26_isactive_idx ON addr_obj_26 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_27 (CONSTRAINT addr_obj_27_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_27_startdate_idx ON addr_obj_27 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_27_enddate_idx ON addr_obj_27 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_27_isactual_idx ON addr_obj_27 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_27_isactive_idx ON addr_obj_27 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_28 (CONSTRAINT addr_obj_28_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_28_startdate_idx ON addr_obj_28 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_28_enddate_idx ON addr_obj_28 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_28_isactual_idx ON addr_obj_28 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_28_isactive_idx ON addr_obj_28 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_29 (CONSTRAINT addr_obj_29_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_29_startdate_idx ON addr_obj_29 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_29_enddate_idx ON addr_obj_29 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_29_isactual_idx ON addr_obj_29 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_29_isactive_idx ON addr_obj_29 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_30 (CONSTRAINT addr_obj_30_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_30_startdate_idx ON addr_obj_30 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_30_enddate_idx ON addr_obj_30 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_30_isactual_idx ON addr_obj_30 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_30_isactive_idx ON addr_obj_30 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_31 (CONSTRAINT addr_obj_31_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_31_startdate_idx ON addr_obj_31 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_31_enddate_idx ON addr_obj_31 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_31_isactual_idx ON addr_obj_31 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_31_isactive_idx ON addr_obj_31 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_32 (CONSTRAINT addr_obj_32_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_32_startdate_idx ON addr_obj_32 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_32_enddate_idx ON addr_obj_32 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_32_isactual_idx ON addr_obj_32 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_32_isactive_idx ON addr_obj_32 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_33 (CONSTRAINT addr_obj_33_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_33_startdate_idx ON addr_obj_33 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_33_enddate_idx ON addr_obj_33 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_33_isactual_idx ON addr_obj_33 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_33_isactive_idx ON addr_obj_33 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_34 (CONSTRAINT addr_obj_34_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_34_startdate_idx ON addr_obj_34 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_34_enddate_idx ON addr_obj_34 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_34_isactual_idx ON addr_obj_34 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_34_isactive_idx ON addr_obj_34 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_35 (CONSTRAINT addr_obj_35_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_35_startdate_idx ON addr_obj_35 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_35_enddate_idx ON addr_obj_35 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_35_isactual_idx ON addr_obj_35 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_35_isactive_idx ON addr_obj_35 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_36 (CONSTRAINT addr_obj_36_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_36_startdate_idx ON addr_obj_36 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_36_enddate_idx ON addr_obj_36 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_36_isactual_idx ON addr_obj_36 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_36_isactive_idx ON addr_obj_36 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_37 (CONSTRAINT addr_obj_37_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_37_startdate_idx ON addr_obj_37 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_37_enddate_idx ON addr_obj_37 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_37_isactual_idx ON addr_obj_37 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_37_isactive_idx ON addr_obj_37 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_38 (CONSTRAINT addr_obj_38_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_38_startdate_idx ON addr_obj_38 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_38_enddate_idx ON addr_obj_38 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_38_isactual_idx ON addr_obj_38 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_38_isactive_idx ON addr_obj_38 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_39 (CONSTRAINT addr_obj_39_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_39_startdate_idx ON addr_obj_39 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_39_enddate_idx ON addr_obj_39 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_39_isactual_idx ON addr_obj_39 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_39_isactive_idx ON addr_obj_39 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_40 (CONSTRAINT addr_obj_40_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_40_startdate_idx ON addr_obj_40 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_40_enddate_idx ON addr_obj_40 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_40_isactual_idx ON addr_obj_40 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_40_isactive_idx ON addr_obj_40 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_41 (CONSTRAINT addr_obj_41_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_41_startdate_idx ON addr_obj_41 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_41_enddate_idx ON addr_obj_41 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_41_isactual_idx ON addr_obj_41 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_41_isactive_idx ON addr_obj_41 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_42 (CONSTRAINT addr_obj_42_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_42_startdate_idx ON addr_obj_42 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_42_enddate_idx ON addr_obj_42 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_42_isactual_idx ON addr_obj_42 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_42_isactive_idx ON addr_obj_42 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_43 (CONSTRAINT addr_obj_43_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_43_startdate_idx ON addr_obj_43 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_43_enddate_idx ON addr_obj_43 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_43_isactual_idx ON addr_obj_43 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_43_isactive_idx ON addr_obj_43 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_44 (CONSTRAINT addr_obj_44_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_44_startdate_idx ON addr_obj_44 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_44_enddate_idx ON addr_obj_44 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_44_isactual_idx ON addr_obj_44 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_44_isactive_idx ON addr_obj_44 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_45 (CONSTRAINT addr_obj_45_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_45_startdate_idx ON addr_obj_45 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_45_enddate_idx ON addr_obj_45 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_45_isactual_idx ON addr_obj_45 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_45_isactive_idx ON addr_obj_45 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_46 (CONSTRAINT addr_obj_46_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_46_startdate_idx ON addr_obj_46 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_46_enddate_idx ON addr_obj_46 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_46_isactual_idx ON addr_obj_46 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_46_isactive_idx ON addr_obj_46 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_47 (CONSTRAINT addr_obj_47_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_47_startdate_idx ON addr_obj_47 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_47_enddate_idx ON addr_obj_47 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_47_isactual_idx ON addr_obj_47 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_47_isactive_idx ON addr_obj_47 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_48 (CONSTRAINT addr_obj_48_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_48_startdate_idx ON addr_obj_48 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_48_enddate_idx ON addr_obj_48 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_48_isactual_idx ON addr_obj_48 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_48_isactive_idx ON addr_obj_48 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_49 (CONSTRAINT addr_obj_49_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_49_startdate_idx ON addr_obj_49 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_49_enddate_idx ON addr_obj_49 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_49_isactual_idx ON addr_obj_49 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_49_isactive_idx ON addr_obj_49 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_50 (CONSTRAINT addr_obj_50_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_50_startdate_idx ON addr_obj_50 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_50_enddate_idx ON addr_obj_50 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_50_isactual_idx ON addr_obj_50 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_50_isactive_idx ON addr_obj_50 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_51 (CONSTRAINT addr_obj_51_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_51_startdate_idx ON addr_obj_51 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_51_enddate_idx ON addr_obj_51 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_51_isactual_idx ON addr_obj_51 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_51_isactive_idx ON addr_obj_51 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_52 (CONSTRAINT addr_obj_52_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_52_startdate_idx ON addr_obj_52 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_52_enddate_idx ON addr_obj_52 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_52_isactual_idx ON addr_obj_52 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_52_isactive_idx ON addr_obj_52 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_53 (CONSTRAINT addr_obj_53_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_53_startdate_idx ON addr_obj_53 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_53_enddate_idx ON addr_obj_53 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_53_isactual_idx ON addr_obj_53 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_53_isactive_idx ON addr_obj_53 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_54 (CONSTRAINT addr_obj_54_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_54_startdate_idx ON addr_obj_54 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_54_enddate_idx ON addr_obj_54 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_54_isactual_idx ON addr_obj_54 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_54_isactive_idx ON addr_obj_54 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_55 (CONSTRAINT addr_obj_55_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_55_startdate_idx ON addr_obj_55 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_55_enddate_idx ON addr_obj_55 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_55_isactual_idx ON addr_obj_55 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_55_isactive_idx ON addr_obj_55 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_56 (CONSTRAINT addr_obj_56_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_56_startdate_idx ON addr_obj_56 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_56_enddate_idx ON addr_obj_56 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_56_isactual_idx ON addr_obj_56 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_56_isactive_idx ON addr_obj_56 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_57 (CONSTRAINT addr_obj_57_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_57_startdate_idx ON addr_obj_57 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_57_enddate_idx ON addr_obj_57 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_57_isactual_idx ON addr_obj_57 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_57_isactive_idx ON addr_obj_57 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_58 (CONSTRAINT addr_obj_58_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_58_startdate_idx ON addr_obj_58 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_58_enddate_idx ON addr_obj_58 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_58_isactual_idx ON addr_obj_58 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_58_isactive_idx ON addr_obj_58 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_59 (CONSTRAINT addr_obj_59_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_59_startdate_idx ON addr_obj_59 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_59_enddate_idx ON addr_obj_59 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_59_isactual_idx ON addr_obj_59 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_59_isactive_idx ON addr_obj_59 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_60 (CONSTRAINT addr_obj_60_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_60_startdate_idx ON addr_obj_60 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_60_enddate_idx ON addr_obj_60 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_60_isactual_idx ON addr_obj_60 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_60_isactive_idx ON addr_obj_60 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_61 (CONSTRAINT addr_obj_61_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_61_startdate_idx ON addr_obj_61 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_61_enddate_idx ON addr_obj_61 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_61_isactual_idx ON addr_obj_61 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_61_isactive_idx ON addr_obj_61 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_62 (CONSTRAINT addr_obj_62_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_62_startdate_idx ON addr_obj_62 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_62_enddate_idx ON addr_obj_62 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_62_isactual_idx ON addr_obj_62 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_62_isactive_idx ON addr_obj_62 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_63 (CONSTRAINT addr_obj_63_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_63_startdate_idx ON addr_obj_63 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_63_enddate_idx ON addr_obj_63 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_63_isactual_idx ON addr_obj_63 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_63_isactive_idx ON addr_obj_63 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_64 (CONSTRAINT addr_obj_64_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_64_startdate_idx ON addr_obj_64 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_64_enddate_idx ON addr_obj_64 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_64_isactual_idx ON addr_obj_64 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_64_isactive_idx ON addr_obj_64 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_65 (CONSTRAINT addr_obj_65_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_65_startdate_idx ON addr_obj_65 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_65_enddate_idx ON addr_obj_65 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_65_isactual_idx ON addr_obj_65 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_65_isactive_idx ON addr_obj_65 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_66 (CONSTRAINT addr_obj_66_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_66_startdate_idx ON addr_obj_66 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_66_enddate_idx ON addr_obj_66 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_66_isactual_idx ON addr_obj_66 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_66_isactive_idx ON addr_obj_66 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_67 (CONSTRAINT addr_obj_67_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_67_startdate_idx ON addr_obj_67 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_67_enddate_idx ON addr_obj_67 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_67_isactual_idx ON addr_obj_67 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_67_isactive_idx ON addr_obj_67 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_68 (CONSTRAINT addr_obj_68_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_68_startdate_idx ON addr_obj_68 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_68_enddate_idx ON addr_obj_68 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_68_isactual_idx ON addr_obj_68 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_68_isactive_idx ON addr_obj_68 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_69 (CONSTRAINT addr_obj_69_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_69_startdate_idx ON addr_obj_69 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_69_enddate_idx ON addr_obj_69 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_69_isactual_idx ON addr_obj_69 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_69_isactive_idx ON addr_obj_69 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_70 (CONSTRAINT addr_obj_70_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_70_startdate_idx ON addr_obj_70 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_70_enddate_idx ON addr_obj_70 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_70_isactual_idx ON addr_obj_70 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_70_isactive_idx ON addr_obj_70 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_71 (CONSTRAINT addr_obj_71_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_71_startdate_idx ON addr_obj_71 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_71_enddate_idx ON addr_obj_71 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_71_isactual_idx ON addr_obj_71 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_71_isactive_idx ON addr_obj_71 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_72 (CONSTRAINT addr_obj_72_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_72_startdate_idx ON addr_obj_72 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_72_enddate_idx ON addr_obj_72 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_72_isactual_idx ON addr_obj_72 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_72_isactive_idx ON addr_obj_72 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_73 (CONSTRAINT addr_obj_73_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_73_startdate_idx ON addr_obj_73 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_73_enddate_idx ON addr_obj_73 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_73_isactual_idx ON addr_obj_73 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_73_isactive_idx ON addr_obj_73 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_74 (CONSTRAINT addr_obj_74_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_74_startdate_idx ON addr_obj_74 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_74_enddate_idx ON addr_obj_74 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_74_isactual_idx ON addr_obj_74 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_74_isactive_idx ON addr_obj_74 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_75 (CONSTRAINT addr_obj_75_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_75_startdate_idx ON addr_obj_75 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_75_enddate_idx ON addr_obj_75 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_75_isactual_idx ON addr_obj_75 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_75_isactive_idx ON addr_obj_75 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_76 (CONSTRAINT addr_obj_76_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_76_startdate_idx ON addr_obj_76 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_76_enddate_idx ON addr_obj_76 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_76_isactual_idx ON addr_obj_76 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_76_isactive_idx ON addr_obj_76 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_77 (CONSTRAINT addr_obj_77_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_77_startdate_idx ON addr_obj_77 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_77_enddate_idx ON addr_obj_77 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_77_isactual_idx ON addr_obj_77 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_77_isactive_idx ON addr_obj_77 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_78 (CONSTRAINT addr_obj_78_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_78_startdate_idx ON addr_obj_78 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_78_enddate_idx ON addr_obj_78 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_78_isactual_idx ON addr_obj_78 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_78_isactive_idx ON addr_obj_78 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_79 (CONSTRAINT addr_obj_79_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_79_startdate_idx ON addr_obj_79 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_79_enddate_idx ON addr_obj_79 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_79_isactual_idx ON addr_obj_79 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_79_isactive_idx ON addr_obj_79 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_80 (CONSTRAINT addr_obj_80_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_80_startdate_idx ON addr_obj_80 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_80_enddate_idx ON addr_obj_80 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_80_isactual_idx ON addr_obj_80 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_80_isactive_idx ON addr_obj_80 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_81 (CONSTRAINT addr_obj_81_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_81_startdate_idx ON addr_obj_81 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_81_enddate_idx ON addr_obj_81 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_81_isactual_idx ON addr_obj_81 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_81_isactive_idx ON addr_obj_81 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_82 (CONSTRAINT addr_obj_82_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_82_startdate_idx ON addr_obj_82 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_82_enddate_idx ON addr_obj_82 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_82_isactual_idx ON addr_obj_82 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_82_isactive_idx ON addr_obj_82 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_83 (CONSTRAINT addr_obj_83_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_83_startdate_idx ON addr_obj_83 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_83_enddate_idx ON addr_obj_83 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_83_isactual_idx ON addr_obj_83 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_83_isactive_idx ON addr_obj_83 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_84 (CONSTRAINT addr_obj_84_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_84_startdate_idx ON addr_obj_84 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_84_enddate_idx ON addr_obj_84 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_84_isactual_idx ON addr_obj_84 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_84_isactive_idx ON addr_obj_84 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_85 (CONSTRAINT addr_obj_85_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_85_startdate_idx ON addr_obj_85 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_85_enddate_idx ON addr_obj_85 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_85_isactual_idx ON addr_obj_85 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_85_isactive_idx ON addr_obj_85 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_86 (CONSTRAINT addr_obj_86_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_86_startdate_idx ON addr_obj_86 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_86_enddate_idx ON addr_obj_86 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_86_isactual_idx ON addr_obj_86 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_86_isactive_idx ON addr_obj_86 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_87 (CONSTRAINT addr_obj_87_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_87_startdate_idx ON addr_obj_87 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_87_enddate_idx ON addr_obj_87 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_87_isactual_idx ON addr_obj_87 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_87_isactive_idx ON addr_obj_87 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_88 (CONSTRAINT addr_obj_88_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_88_startdate_idx ON addr_obj_88 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_88_enddate_idx ON addr_obj_88 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_88_isactual_idx ON addr_obj_88 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_88_isactive_idx ON addr_obj_88 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_89 (CONSTRAINT addr_obj_89_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_89_startdate_idx ON addr_obj_89 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_89_enddate_idx ON addr_obj_89 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_89_isactual_idx ON addr_obj_89 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_89_isactive_idx ON addr_obj_89 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_90 (CONSTRAINT addr_obj_90_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_90_startdate_idx ON addr_obj_90 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_90_enddate_idx ON addr_obj_90 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_90_isactual_idx ON addr_obj_90 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_90_isactive_idx ON addr_obj_90 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_91 (CONSTRAINT addr_obj_91_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_91_startdate_idx ON addr_obj_91 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_91_enddate_idx ON addr_obj_91 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_91_isactual_idx ON addr_obj_91 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_91_isactive_idx ON addr_obj_91 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_92 (CONSTRAINT addr_obj_92_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_92_startdate_idx ON addr_obj_92 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_92_enddate_idx ON addr_obj_92 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_92_isactual_idx ON addr_obj_92 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_92_isactive_idx ON addr_obj_92 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_93 (CONSTRAINT addr_obj_93_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_93_startdate_idx ON addr_obj_93 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_93_enddate_idx ON addr_obj_93 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_93_isactual_idx ON addr_obj_93 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_93_isactive_idx ON addr_obj_93 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_94 (CONSTRAINT addr_obj_94_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_94_startdate_idx ON addr_obj_94 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_94_enddate_idx ON addr_obj_94 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_94_isactual_idx ON addr_obj_94 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_94_isactive_idx ON addr_obj_94 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_95 (CONSTRAINT addr_obj_95_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_95_startdate_idx ON addr_obj_95 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_95_enddate_idx ON addr_obj_95 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_95_isactual_idx ON addr_obj_95 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_95_isactive_idx ON addr_obj_95 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_96 (CONSTRAINT addr_obj_96_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_96_startdate_idx ON addr_obj_96 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_96_enddate_idx ON addr_obj_96 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_96_isactual_idx ON addr_obj_96 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_96_isactive_idx ON addr_obj_96 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_97 (CONSTRAINT addr_obj_97_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_97_startdate_idx ON addr_obj_97 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_97_enddate_idx ON addr_obj_97 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_97_isactual_idx ON addr_obj_97 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_97_isactive_idx ON addr_obj_97 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_98 (CONSTRAINT addr_obj_98_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_98_startdate_idx ON addr_obj_98 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_98_enddate_idx ON addr_obj_98 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_98_isactual_idx ON addr_obj_98 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_98_isactive_idx ON addr_obj_98 USING btree (isactive);
CREATE TABLE IF NOT EXISTS addr_obj_99 (CONSTRAINT addr_obj_99_pkey PRIMARY KEY (id)) INHERITS (addr_obj);
CREATE INDEX IF NOT EXISTS addr_obj_99_startdate_idx ON addr_obj_99 USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_99_enddate_idx ON addr_obj_99 USING btree (enddate);
CREATE INDEX IF NOT EXISTS addr_obj_99_isactual_idx ON addr_obj_99 USING btree (isactual);
CREATE INDEX IF NOT EXISTS addr_obj_99_isactive_idx ON addr_obj_99 USING btree (isactive);
