CREATE TABLE IF NOT EXISTS adm_hierarchy (
  id BIGINT NOT NULL PRIMARY KEY,
  objectid BIGINT NOT NULL,
  parentobjid BIGINT,
  changeid BIGINT NOT NULL,
  regioncode VARCHAR(4),
  areacode VARCHAR(4),
  citycode VARCHAR(4),
  placecode VARCHAR(4),
  plancode VARCHAR(4),
  streetcode VARCHAR(4),
  previd BIGINT,
  nextid BIGINT,
  updatedate DATE NOT NULL,
  startdate DATE NOT NULL,
  enddate DATE NOT NULL,
  isactive SMALLINT NOT NULL
);
COMMENT ON TABLE adm_hierarchy IS 'Сведения по иерархии в административном делении';
COMMENT ON COLUMN adm_hierarchy.id IS 'Уникальный идентификатор записи. Ключевое поле';
COMMENT ON COLUMN adm_hierarchy.objectid IS 'Глобальный уникальный идентификатор объекта';
COMMENT ON COLUMN adm_hierarchy.parentobjid IS 'Идентификатор родительского объекта';
COMMENT ON COLUMN adm_hierarchy.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN adm_hierarchy.regioncode IS 'Код региона';
COMMENT ON COLUMN adm_hierarchy.areacode IS 'Код района';
COMMENT ON COLUMN adm_hierarchy.citycode IS 'Код города';
COMMENT ON COLUMN adm_hierarchy.placecode IS 'Код населенного пункта';
COMMENT ON COLUMN adm_hierarchy.plancode IS 'Код ЭПС';
COMMENT ON COLUMN adm_hierarchy.streetcode IS 'Код улицы';
COMMENT ON COLUMN adm_hierarchy.previd IS 'Идентификатор записи связывания с предыдущей исторической записью';
COMMENT ON COLUMN adm_hierarchy.nextid IS 'Идентификатор записи связывания с последующей исторической записью';
COMMENT ON COLUMN adm_hierarchy.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN adm_hierarchy.startdate IS 'Начало действия записи';
COMMENT ON COLUMN adm_hierarchy.enddate IS 'Окончание действия записи';
COMMENT ON COLUMN adm_hierarchy.isactive IS 'Признак действующего адресного объекта';
CREATE INDEX IF NOT EXISTS adm_hierarchy_startdate_idx ON adm_hierarchy USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_enddate_idx ON adm_hierarchy USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_isactive_idx ON adm_hierarchy USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_01 (CONSTRAINT adm_hierarchy_01_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_01_startdate_idx ON adm_hierarchy_01 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_01_enddate_idx ON adm_hierarchy_01 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_01_isactive_idx ON adm_hierarchy_01 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_02 (CONSTRAINT adm_hierarchy_02_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_02_startdate_idx ON adm_hierarchy_02 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_02_enddate_idx ON adm_hierarchy_02 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_02_isactive_idx ON adm_hierarchy_02 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_03 (CONSTRAINT adm_hierarchy_03_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_03_startdate_idx ON adm_hierarchy_03 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_03_enddate_idx ON adm_hierarchy_03 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_03_isactive_idx ON adm_hierarchy_03 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_04 (CONSTRAINT adm_hierarchy_04_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_04_startdate_idx ON adm_hierarchy_04 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_04_enddate_idx ON adm_hierarchy_04 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_04_isactive_idx ON adm_hierarchy_04 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_05 (CONSTRAINT adm_hierarchy_05_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_05_startdate_idx ON adm_hierarchy_05 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_05_enddate_idx ON adm_hierarchy_05 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_05_isactive_idx ON adm_hierarchy_05 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_06 (CONSTRAINT adm_hierarchy_06_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_06_startdate_idx ON adm_hierarchy_06 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_06_enddate_idx ON adm_hierarchy_06 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_06_isactive_idx ON adm_hierarchy_06 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_07 (CONSTRAINT adm_hierarchy_07_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_07_startdate_idx ON adm_hierarchy_07 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_07_enddate_idx ON adm_hierarchy_07 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_07_isactive_idx ON adm_hierarchy_07 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_08 (CONSTRAINT adm_hierarchy_08_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_08_startdate_idx ON adm_hierarchy_08 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_08_enddate_idx ON adm_hierarchy_08 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_08_isactive_idx ON adm_hierarchy_08 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_09 (CONSTRAINT adm_hierarchy_09_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_09_startdate_idx ON adm_hierarchy_09 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_09_enddate_idx ON adm_hierarchy_09 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_09_isactive_idx ON adm_hierarchy_09 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_10 (CONSTRAINT adm_hierarchy_10_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_10_startdate_idx ON adm_hierarchy_10 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_10_enddate_idx ON adm_hierarchy_10 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_10_isactive_idx ON adm_hierarchy_10 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_11 (CONSTRAINT adm_hierarchy_11_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_11_startdate_idx ON adm_hierarchy_11 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_11_enddate_idx ON adm_hierarchy_11 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_11_isactive_idx ON adm_hierarchy_11 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_12 (CONSTRAINT adm_hierarchy_12_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_12_startdate_idx ON adm_hierarchy_12 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_12_enddate_idx ON adm_hierarchy_12 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_12_isactive_idx ON adm_hierarchy_12 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_13 (CONSTRAINT adm_hierarchy_13_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_13_startdate_idx ON adm_hierarchy_13 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_13_enddate_idx ON adm_hierarchy_13 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_13_isactive_idx ON adm_hierarchy_13 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_14 (CONSTRAINT adm_hierarchy_14_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_14_startdate_idx ON adm_hierarchy_14 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_14_enddate_idx ON adm_hierarchy_14 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_14_isactive_idx ON adm_hierarchy_14 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_15 (CONSTRAINT adm_hierarchy_15_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_15_startdate_idx ON adm_hierarchy_15 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_15_enddate_idx ON adm_hierarchy_15 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_15_isactive_idx ON adm_hierarchy_15 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_16 (CONSTRAINT adm_hierarchy_16_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_16_startdate_idx ON adm_hierarchy_16 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_16_enddate_idx ON adm_hierarchy_16 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_16_isactive_idx ON adm_hierarchy_16 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_17 (CONSTRAINT adm_hierarchy_17_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_17_startdate_idx ON adm_hierarchy_17 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_17_enddate_idx ON adm_hierarchy_17 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_17_isactive_idx ON adm_hierarchy_17 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_18 (CONSTRAINT adm_hierarchy_18_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_18_startdate_idx ON adm_hierarchy_18 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_18_enddate_idx ON adm_hierarchy_18 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_18_isactive_idx ON adm_hierarchy_18 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_19 (CONSTRAINT adm_hierarchy_19_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_19_startdate_idx ON adm_hierarchy_19 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_19_enddate_idx ON adm_hierarchy_19 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_19_isactive_idx ON adm_hierarchy_19 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_20 (CONSTRAINT adm_hierarchy_20_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_20_startdate_idx ON adm_hierarchy_20 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_20_enddate_idx ON adm_hierarchy_20 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_20_isactive_idx ON adm_hierarchy_20 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_21 (CONSTRAINT adm_hierarchy_21_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_21_startdate_idx ON adm_hierarchy_21 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_21_enddate_idx ON adm_hierarchy_21 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_21_isactive_idx ON adm_hierarchy_21 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_22 (CONSTRAINT adm_hierarchy_22_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_22_startdate_idx ON adm_hierarchy_22 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_22_enddate_idx ON adm_hierarchy_22 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_22_isactive_idx ON adm_hierarchy_22 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_23 (CONSTRAINT adm_hierarchy_23_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_23_startdate_idx ON adm_hierarchy_23 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_23_enddate_idx ON adm_hierarchy_23 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_23_isactive_idx ON adm_hierarchy_23 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_24 (CONSTRAINT adm_hierarchy_24_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_24_startdate_idx ON adm_hierarchy_24 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_24_enddate_idx ON adm_hierarchy_24 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_24_isactive_idx ON adm_hierarchy_24 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_25 (CONSTRAINT adm_hierarchy_25_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_25_startdate_idx ON adm_hierarchy_25 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_25_enddate_idx ON adm_hierarchy_25 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_25_isactive_idx ON adm_hierarchy_25 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_26 (CONSTRAINT adm_hierarchy_26_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_26_startdate_idx ON adm_hierarchy_26 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_26_enddate_idx ON adm_hierarchy_26 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_26_isactive_idx ON adm_hierarchy_26 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_27 (CONSTRAINT adm_hierarchy_27_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_27_startdate_idx ON adm_hierarchy_27 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_27_enddate_idx ON adm_hierarchy_27 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_27_isactive_idx ON adm_hierarchy_27 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_28 (CONSTRAINT adm_hierarchy_28_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_28_startdate_idx ON adm_hierarchy_28 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_28_enddate_idx ON adm_hierarchy_28 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_28_isactive_idx ON adm_hierarchy_28 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_29 (CONSTRAINT adm_hierarchy_29_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_29_startdate_idx ON adm_hierarchy_29 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_29_enddate_idx ON adm_hierarchy_29 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_29_isactive_idx ON adm_hierarchy_29 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_30 (CONSTRAINT adm_hierarchy_30_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_30_startdate_idx ON adm_hierarchy_30 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_30_enddate_idx ON adm_hierarchy_30 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_30_isactive_idx ON adm_hierarchy_30 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_31 (CONSTRAINT adm_hierarchy_31_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_31_startdate_idx ON adm_hierarchy_31 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_31_enddate_idx ON adm_hierarchy_31 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_31_isactive_idx ON adm_hierarchy_31 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_32 (CONSTRAINT adm_hierarchy_32_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_32_startdate_idx ON adm_hierarchy_32 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_32_enddate_idx ON adm_hierarchy_32 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_32_isactive_idx ON adm_hierarchy_32 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_33 (CONSTRAINT adm_hierarchy_33_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_33_startdate_idx ON adm_hierarchy_33 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_33_enddate_idx ON adm_hierarchy_33 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_33_isactive_idx ON adm_hierarchy_33 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_34 (CONSTRAINT adm_hierarchy_34_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_34_startdate_idx ON adm_hierarchy_34 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_34_enddate_idx ON adm_hierarchy_34 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_34_isactive_idx ON adm_hierarchy_34 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_35 (CONSTRAINT adm_hierarchy_35_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_35_startdate_idx ON adm_hierarchy_35 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_35_enddate_idx ON adm_hierarchy_35 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_35_isactive_idx ON adm_hierarchy_35 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_36 (CONSTRAINT adm_hierarchy_36_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_36_startdate_idx ON adm_hierarchy_36 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_36_enddate_idx ON adm_hierarchy_36 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_36_isactive_idx ON adm_hierarchy_36 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_37 (CONSTRAINT adm_hierarchy_37_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_37_startdate_idx ON adm_hierarchy_37 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_37_enddate_idx ON adm_hierarchy_37 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_37_isactive_idx ON adm_hierarchy_37 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_38 (CONSTRAINT adm_hierarchy_38_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_38_startdate_idx ON adm_hierarchy_38 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_38_enddate_idx ON adm_hierarchy_38 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_38_isactive_idx ON adm_hierarchy_38 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_39 (CONSTRAINT adm_hierarchy_39_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_39_startdate_idx ON adm_hierarchy_39 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_39_enddate_idx ON adm_hierarchy_39 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_39_isactive_idx ON adm_hierarchy_39 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_40 (CONSTRAINT adm_hierarchy_40_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_40_startdate_idx ON adm_hierarchy_40 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_40_enddate_idx ON adm_hierarchy_40 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_40_isactive_idx ON adm_hierarchy_40 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_41 (CONSTRAINT adm_hierarchy_41_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_41_startdate_idx ON adm_hierarchy_41 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_41_enddate_idx ON adm_hierarchy_41 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_41_isactive_idx ON adm_hierarchy_41 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_42 (CONSTRAINT adm_hierarchy_42_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_42_startdate_idx ON adm_hierarchy_42 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_42_enddate_idx ON adm_hierarchy_42 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_42_isactive_idx ON adm_hierarchy_42 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_43 (CONSTRAINT adm_hierarchy_43_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_43_startdate_idx ON adm_hierarchy_43 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_43_enddate_idx ON adm_hierarchy_43 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_43_isactive_idx ON adm_hierarchy_43 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_44 (CONSTRAINT adm_hierarchy_44_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_44_startdate_idx ON adm_hierarchy_44 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_44_enddate_idx ON adm_hierarchy_44 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_44_isactive_idx ON adm_hierarchy_44 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_45 (CONSTRAINT adm_hierarchy_45_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_45_startdate_idx ON adm_hierarchy_45 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_45_enddate_idx ON adm_hierarchy_45 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_45_isactive_idx ON adm_hierarchy_45 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_46 (CONSTRAINT adm_hierarchy_46_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_46_startdate_idx ON adm_hierarchy_46 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_46_enddate_idx ON adm_hierarchy_46 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_46_isactive_idx ON adm_hierarchy_46 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_47 (CONSTRAINT adm_hierarchy_47_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_47_startdate_idx ON adm_hierarchy_47 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_47_enddate_idx ON adm_hierarchy_47 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_47_isactive_idx ON adm_hierarchy_47 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_48 (CONSTRAINT adm_hierarchy_48_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_48_startdate_idx ON adm_hierarchy_48 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_48_enddate_idx ON adm_hierarchy_48 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_48_isactive_idx ON adm_hierarchy_48 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_49 (CONSTRAINT adm_hierarchy_49_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_49_startdate_idx ON adm_hierarchy_49 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_49_enddate_idx ON adm_hierarchy_49 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_49_isactive_idx ON adm_hierarchy_49 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_50 (CONSTRAINT adm_hierarchy_50_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_50_startdate_idx ON adm_hierarchy_50 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_50_enddate_idx ON adm_hierarchy_50 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_50_isactive_idx ON adm_hierarchy_50 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_51 (CONSTRAINT adm_hierarchy_51_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_51_startdate_idx ON adm_hierarchy_51 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_51_enddate_idx ON adm_hierarchy_51 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_51_isactive_idx ON adm_hierarchy_51 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_52 (CONSTRAINT adm_hierarchy_52_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_52_startdate_idx ON adm_hierarchy_52 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_52_enddate_idx ON adm_hierarchy_52 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_52_isactive_idx ON adm_hierarchy_52 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_53 (CONSTRAINT adm_hierarchy_53_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_53_startdate_idx ON adm_hierarchy_53 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_53_enddate_idx ON adm_hierarchy_53 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_53_isactive_idx ON adm_hierarchy_53 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_54 (CONSTRAINT adm_hierarchy_54_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_54_startdate_idx ON adm_hierarchy_54 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_54_enddate_idx ON adm_hierarchy_54 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_54_isactive_idx ON adm_hierarchy_54 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_55 (CONSTRAINT adm_hierarchy_55_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_55_startdate_idx ON adm_hierarchy_55 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_55_enddate_idx ON adm_hierarchy_55 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_55_isactive_idx ON adm_hierarchy_55 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_56 (CONSTRAINT adm_hierarchy_56_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_56_startdate_idx ON adm_hierarchy_56 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_56_enddate_idx ON adm_hierarchy_56 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_56_isactive_idx ON adm_hierarchy_56 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_57 (CONSTRAINT adm_hierarchy_57_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_57_startdate_idx ON adm_hierarchy_57 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_57_enddate_idx ON adm_hierarchy_57 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_57_isactive_idx ON adm_hierarchy_57 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_58 (CONSTRAINT adm_hierarchy_58_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_58_startdate_idx ON adm_hierarchy_58 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_58_enddate_idx ON adm_hierarchy_58 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_58_isactive_idx ON adm_hierarchy_58 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_59 (CONSTRAINT adm_hierarchy_59_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_59_startdate_idx ON adm_hierarchy_59 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_59_enddate_idx ON adm_hierarchy_59 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_59_isactive_idx ON adm_hierarchy_59 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_60 (CONSTRAINT adm_hierarchy_60_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_60_startdate_idx ON adm_hierarchy_60 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_60_enddate_idx ON adm_hierarchy_60 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_60_isactive_idx ON adm_hierarchy_60 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_61 (CONSTRAINT adm_hierarchy_61_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_61_startdate_idx ON adm_hierarchy_61 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_61_enddate_idx ON adm_hierarchy_61 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_61_isactive_idx ON adm_hierarchy_61 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_62 (CONSTRAINT adm_hierarchy_62_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_62_startdate_idx ON adm_hierarchy_62 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_62_enddate_idx ON adm_hierarchy_62 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_62_isactive_idx ON adm_hierarchy_62 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_63 (CONSTRAINT adm_hierarchy_63_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_63_startdate_idx ON adm_hierarchy_63 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_63_enddate_idx ON adm_hierarchy_63 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_63_isactive_idx ON adm_hierarchy_63 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_64 (CONSTRAINT adm_hierarchy_64_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_64_startdate_idx ON adm_hierarchy_64 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_64_enddate_idx ON adm_hierarchy_64 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_64_isactive_idx ON adm_hierarchy_64 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_65 (CONSTRAINT adm_hierarchy_65_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_65_startdate_idx ON adm_hierarchy_65 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_65_enddate_idx ON adm_hierarchy_65 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_65_isactive_idx ON adm_hierarchy_65 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_66 (CONSTRAINT adm_hierarchy_66_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_66_startdate_idx ON adm_hierarchy_66 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_66_enddate_idx ON adm_hierarchy_66 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_66_isactive_idx ON adm_hierarchy_66 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_67 (CONSTRAINT adm_hierarchy_67_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_67_startdate_idx ON adm_hierarchy_67 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_67_enddate_idx ON adm_hierarchy_67 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_67_isactive_idx ON adm_hierarchy_67 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_68 (CONSTRAINT adm_hierarchy_68_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_68_startdate_idx ON adm_hierarchy_68 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_68_enddate_idx ON adm_hierarchy_68 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_68_isactive_idx ON adm_hierarchy_68 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_69 (CONSTRAINT adm_hierarchy_69_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_69_startdate_idx ON adm_hierarchy_69 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_69_enddate_idx ON adm_hierarchy_69 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_69_isactive_idx ON adm_hierarchy_69 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_70 (CONSTRAINT adm_hierarchy_70_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_70_startdate_idx ON adm_hierarchy_70 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_70_enddate_idx ON adm_hierarchy_70 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_70_isactive_idx ON adm_hierarchy_70 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_71 (CONSTRAINT adm_hierarchy_71_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_71_startdate_idx ON adm_hierarchy_71 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_71_enddate_idx ON adm_hierarchy_71 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_71_isactive_idx ON adm_hierarchy_71 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_72 (CONSTRAINT adm_hierarchy_72_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_72_startdate_idx ON adm_hierarchy_72 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_72_enddate_idx ON adm_hierarchy_72 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_72_isactive_idx ON adm_hierarchy_72 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_73 (CONSTRAINT adm_hierarchy_73_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_73_startdate_idx ON adm_hierarchy_73 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_73_enddate_idx ON adm_hierarchy_73 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_73_isactive_idx ON adm_hierarchy_73 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_74 (CONSTRAINT adm_hierarchy_74_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_74_startdate_idx ON adm_hierarchy_74 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_74_enddate_idx ON adm_hierarchy_74 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_74_isactive_idx ON adm_hierarchy_74 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_75 (CONSTRAINT adm_hierarchy_75_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_75_startdate_idx ON adm_hierarchy_75 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_75_enddate_idx ON adm_hierarchy_75 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_75_isactive_idx ON adm_hierarchy_75 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_76 (CONSTRAINT adm_hierarchy_76_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_76_startdate_idx ON adm_hierarchy_76 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_76_enddate_idx ON adm_hierarchy_76 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_76_isactive_idx ON adm_hierarchy_76 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_77 (CONSTRAINT adm_hierarchy_77_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_77_startdate_idx ON adm_hierarchy_77 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_77_enddate_idx ON adm_hierarchy_77 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_77_isactive_idx ON adm_hierarchy_77 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_78 (CONSTRAINT adm_hierarchy_78_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_78_startdate_idx ON adm_hierarchy_78 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_78_enddate_idx ON adm_hierarchy_78 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_78_isactive_idx ON adm_hierarchy_78 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_79 (CONSTRAINT adm_hierarchy_79_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_79_startdate_idx ON adm_hierarchy_79 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_79_enddate_idx ON adm_hierarchy_79 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_79_isactive_idx ON adm_hierarchy_79 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_80 (CONSTRAINT adm_hierarchy_80_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_80_startdate_idx ON adm_hierarchy_80 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_80_enddate_idx ON adm_hierarchy_80 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_80_isactive_idx ON adm_hierarchy_80 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_81 (CONSTRAINT adm_hierarchy_81_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_81_startdate_idx ON adm_hierarchy_81 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_81_enddate_idx ON adm_hierarchy_81 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_81_isactive_idx ON adm_hierarchy_81 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_82 (CONSTRAINT adm_hierarchy_82_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_82_startdate_idx ON adm_hierarchy_82 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_82_enddate_idx ON adm_hierarchy_82 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_82_isactive_idx ON adm_hierarchy_82 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_83 (CONSTRAINT adm_hierarchy_83_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_83_startdate_idx ON adm_hierarchy_83 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_83_enddate_idx ON adm_hierarchy_83 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_83_isactive_idx ON adm_hierarchy_83 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_84 (CONSTRAINT adm_hierarchy_84_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_84_startdate_idx ON adm_hierarchy_84 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_84_enddate_idx ON adm_hierarchy_84 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_84_isactive_idx ON adm_hierarchy_84 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_85 (CONSTRAINT adm_hierarchy_85_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_85_startdate_idx ON adm_hierarchy_85 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_85_enddate_idx ON adm_hierarchy_85 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_85_isactive_idx ON adm_hierarchy_85 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_86 (CONSTRAINT adm_hierarchy_86_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_86_startdate_idx ON adm_hierarchy_86 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_86_enddate_idx ON adm_hierarchy_86 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_86_isactive_idx ON adm_hierarchy_86 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_87 (CONSTRAINT adm_hierarchy_87_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_87_startdate_idx ON adm_hierarchy_87 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_87_enddate_idx ON adm_hierarchy_87 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_87_isactive_idx ON adm_hierarchy_87 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_88 (CONSTRAINT adm_hierarchy_88_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_88_startdate_idx ON adm_hierarchy_88 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_88_enddate_idx ON adm_hierarchy_88 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_88_isactive_idx ON adm_hierarchy_88 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_89 (CONSTRAINT adm_hierarchy_89_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_89_startdate_idx ON adm_hierarchy_89 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_89_enddate_idx ON adm_hierarchy_89 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_89_isactive_idx ON adm_hierarchy_89 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_90 (CONSTRAINT adm_hierarchy_90_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_90_startdate_idx ON adm_hierarchy_90 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_90_enddate_idx ON adm_hierarchy_90 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_90_isactive_idx ON adm_hierarchy_90 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_91 (CONSTRAINT adm_hierarchy_91_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_91_startdate_idx ON adm_hierarchy_91 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_91_enddate_idx ON adm_hierarchy_91 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_91_isactive_idx ON adm_hierarchy_91 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_92 (CONSTRAINT adm_hierarchy_92_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_92_startdate_idx ON adm_hierarchy_92 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_92_enddate_idx ON adm_hierarchy_92 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_92_isactive_idx ON adm_hierarchy_92 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_93 (CONSTRAINT adm_hierarchy_93_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_93_startdate_idx ON adm_hierarchy_93 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_93_enddate_idx ON adm_hierarchy_93 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_93_isactive_idx ON adm_hierarchy_93 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_94 (CONSTRAINT adm_hierarchy_94_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_94_startdate_idx ON adm_hierarchy_94 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_94_enddate_idx ON adm_hierarchy_94 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_94_isactive_idx ON adm_hierarchy_94 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_95 (CONSTRAINT adm_hierarchy_95_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_95_startdate_idx ON adm_hierarchy_95 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_95_enddate_idx ON adm_hierarchy_95 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_95_isactive_idx ON adm_hierarchy_95 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_96 (CONSTRAINT adm_hierarchy_96_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_96_startdate_idx ON adm_hierarchy_96 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_96_enddate_idx ON adm_hierarchy_96 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_96_isactive_idx ON adm_hierarchy_96 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_97 (CONSTRAINT adm_hierarchy_97_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_97_startdate_idx ON adm_hierarchy_97 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_97_enddate_idx ON adm_hierarchy_97 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_97_isactive_idx ON adm_hierarchy_97 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_98 (CONSTRAINT adm_hierarchy_98_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_98_startdate_idx ON adm_hierarchy_98 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_98_enddate_idx ON adm_hierarchy_98 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_98_isactive_idx ON adm_hierarchy_98 USING btree (isactive);
CREATE TABLE IF NOT EXISTS adm_hierarchy_99 (CONSTRAINT adm_hierarchy_99_pkey PRIMARY KEY (id)) INHERITS (adm_hierarchy);
CREATE INDEX IF NOT EXISTS adm_hierarchy_99_startdate_idx ON adm_hierarchy_99 USING btree (startdate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_99_enddate_idx ON adm_hierarchy_99 USING btree (enddate);
CREATE INDEX IF NOT EXISTS adm_hierarchy_99_isactive_idx ON adm_hierarchy_99 USING btree (isactive);
