CREATE TABLE IF NOT EXISTS apartments (
  id BIGINT NOT NULL PRIMARY KEY,
  objectid BIGINT NOT NULL,
  objectguid UUID NOT NULL,
  changeid BIGINT NOT NULL,
  number VARCHAR(50) NOT NULL,
  aparttype INT NOT NULL,
  opertypeid BIGINT NOT NULL,
  previd BIGINT,
  nextid BIGINT,
  updatedate DATE NOT NULL,
  startdate DATE NOT NULL,
  enddate DATE NOT NULL,
  isactual SMALLINT NOT NULL,
  isactive SMALLINT NOT NULL
);
COMMENT ON TABLE apartments IS 'Сведения по помещениям';
COMMENT ON COLUMN apartments.id IS 'Уникальный идентификатор записи. Ключевое поле';
COMMENT ON COLUMN apartments.objectid IS 'Глобальный уникальный идентификатор объекта типа INTEGER';
COMMENT ON COLUMN apartments.objectguid IS 'Глобальный уникальный идентификатор адресного объекта типа UUID';
COMMENT ON COLUMN apartments.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN apartments.number IS 'Номер комнаты';
COMMENT ON COLUMN apartments.aparttype IS 'Тип комнаты';
COMMENT ON COLUMN apartments.opertypeid IS 'Статус действия над записью – причина появления записи';
COMMENT ON COLUMN apartments.previd IS 'Идентификатор записи связывания с предыдущей исторической записью';
COMMENT ON COLUMN apartments.nextid IS 'Идентификатор записи связывания с последующей исторической записью';
COMMENT ON COLUMN apartments.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN apartments.startdate IS 'Начало действия записи';
COMMENT ON COLUMN apartments.enddate IS 'Окончание действия записи';
COMMENT ON COLUMN apartments.isactual IS 'Статус актуальности адресного объекта ФИАС';
COMMENT ON COLUMN apartments.isactive IS 'Признак действующего адресного объекта';
CREATE INDEX IF NOT EXISTS apartments_objectid_idx ON apartments USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_aparttype_idx ON apartments USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_startdate_idx ON apartments USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_enddate_idx ON apartments USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_isactual_idx ON apartments USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_isactive_idx ON apartments USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_01 (CONSTRAINT apartments_01_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_01_objectid_idx ON apartments_01 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_01_aparttype_idx ON apartments_01 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_01_startdate_idx ON apartments_01 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_01_enddate_idx ON apartments_01 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_01_isactual_idx ON apartments_01 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_01_isactive_idx ON apartments_01 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_02 (CONSTRAINT apartments_02_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_02_objectid_idx ON apartments_02 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_02_aparttype_idx ON apartments_02 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_02_startdate_idx ON apartments_02 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_02_enddate_idx ON apartments_02 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_02_isactual_idx ON apartments_02 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_02_isactive_idx ON apartments_02 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_03 (CONSTRAINT apartments_03_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_03_objectid_idx ON apartments_03 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_03_aparttype_idx ON apartments_03 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_03_startdate_idx ON apartments_03 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_03_enddate_idx ON apartments_03 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_03_isactual_idx ON apartments_03 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_03_isactive_idx ON apartments_03 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_04 (CONSTRAINT apartments_04_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_04_objectid_idx ON apartments_04 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_04_aparttype_idx ON apartments_04 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_04_startdate_idx ON apartments_04 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_04_enddate_idx ON apartments_04 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_04_isactual_idx ON apartments_04 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_04_isactive_idx ON apartments_04 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_05 (CONSTRAINT apartments_05_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_05_objectid_idx ON apartments_05 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_05_aparttype_idx ON apartments_05 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_05_startdate_idx ON apartments_05 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_05_enddate_idx ON apartments_05 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_05_isactual_idx ON apartments_05 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_05_isactive_idx ON apartments_05 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_06 (CONSTRAINT apartments_06_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_06_objectid_idx ON apartments_06 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_06_aparttype_idx ON apartments_06 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_06_startdate_idx ON apartments_06 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_06_enddate_idx ON apartments_06 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_06_isactual_idx ON apartments_06 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_06_isactive_idx ON apartments_06 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_07 (CONSTRAINT apartments_07_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_07_objectid_idx ON apartments_07 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_07_aparttype_idx ON apartments_07 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_07_startdate_idx ON apartments_07 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_07_enddate_idx ON apartments_07 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_07_isactual_idx ON apartments_07 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_07_isactive_idx ON apartments_07 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_08 (CONSTRAINT apartments_08_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_08_objectid_idx ON apartments_08 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_08_aparttype_idx ON apartments_08 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_08_startdate_idx ON apartments_08 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_08_enddate_idx ON apartments_08 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_08_isactual_idx ON apartments_08 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_08_isactive_idx ON apartments_08 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_09 (CONSTRAINT apartments_09_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_09_objectid_idx ON apartments_09 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_09_aparttype_idx ON apartments_09 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_09_startdate_idx ON apartments_09 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_09_enddate_idx ON apartments_09 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_09_isactual_idx ON apartments_09 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_09_isactive_idx ON apartments_09 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_10 (CONSTRAINT apartments_10_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_10_objectid_idx ON apartments_10 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_10_aparttype_idx ON apartments_10 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_10_startdate_idx ON apartments_10 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_10_enddate_idx ON apartments_10 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_10_isactual_idx ON apartments_10 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_10_isactive_idx ON apartments_10 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_11 (CONSTRAINT apartments_11_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_11_objectid_idx ON apartments_11 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_11_aparttype_idx ON apartments_11 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_11_startdate_idx ON apartments_11 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_11_enddate_idx ON apartments_11 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_11_isactual_idx ON apartments_11 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_11_isactive_idx ON apartments_11 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_12 (CONSTRAINT apartments_12_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_12_objectid_idx ON apartments_12 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_12_aparttype_idx ON apartments_12 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_12_startdate_idx ON apartments_12 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_12_enddate_idx ON apartments_12 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_12_isactual_idx ON apartments_12 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_12_isactive_idx ON apartments_12 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_13 (CONSTRAINT apartments_13_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_13_objectid_idx ON apartments_13 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_13_aparttype_idx ON apartments_13 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_13_startdate_idx ON apartments_13 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_13_enddate_idx ON apartments_13 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_13_isactual_idx ON apartments_13 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_13_isactive_idx ON apartments_13 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_14 (CONSTRAINT apartments_14_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_14_objectid_idx ON apartments_14 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_14_aparttype_idx ON apartments_14 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_14_startdate_idx ON apartments_14 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_14_enddate_idx ON apartments_14 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_14_isactual_idx ON apartments_14 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_14_isactive_idx ON apartments_14 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_15 (CONSTRAINT apartments_15_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_15_objectid_idx ON apartments_15 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_15_aparttype_idx ON apartments_15 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_15_startdate_idx ON apartments_15 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_15_enddate_idx ON apartments_15 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_15_isactual_idx ON apartments_15 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_15_isactive_idx ON apartments_15 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_16 (CONSTRAINT apartments_16_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_16_objectid_idx ON apartments_16 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_16_aparttype_idx ON apartments_16 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_16_startdate_idx ON apartments_16 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_16_enddate_idx ON apartments_16 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_16_isactual_idx ON apartments_16 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_16_isactive_idx ON apartments_16 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_17 (CONSTRAINT apartments_17_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_17_objectid_idx ON apartments_17 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_17_aparttype_idx ON apartments_17 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_17_startdate_idx ON apartments_17 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_17_enddate_idx ON apartments_17 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_17_isactual_idx ON apartments_17 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_17_isactive_idx ON apartments_17 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_18 (CONSTRAINT apartments_18_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_18_objectid_idx ON apartments_18 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_18_aparttype_idx ON apartments_18 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_18_startdate_idx ON apartments_18 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_18_enddate_idx ON apartments_18 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_18_isactual_idx ON apartments_18 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_18_isactive_idx ON apartments_18 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_19 (CONSTRAINT apartments_19_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_19_objectid_idx ON apartments_19 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_19_aparttype_idx ON apartments_19 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_19_startdate_idx ON apartments_19 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_19_enddate_idx ON apartments_19 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_19_isactual_idx ON apartments_19 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_19_isactive_idx ON apartments_19 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_20 (CONSTRAINT apartments_20_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_20_objectid_idx ON apartments_20 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_20_aparttype_idx ON apartments_20 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_20_startdate_idx ON apartments_20 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_20_enddate_idx ON apartments_20 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_20_isactual_idx ON apartments_20 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_20_isactive_idx ON apartments_20 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_21 (CONSTRAINT apartments_21_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_21_objectid_idx ON apartments_21 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_21_aparttype_idx ON apartments_21 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_21_startdate_idx ON apartments_21 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_21_enddate_idx ON apartments_21 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_21_isactual_idx ON apartments_21 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_21_isactive_idx ON apartments_21 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_22 (CONSTRAINT apartments_22_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_22_objectid_idx ON apartments_22 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_22_aparttype_idx ON apartments_22 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_22_startdate_idx ON apartments_22 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_22_enddate_idx ON apartments_22 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_22_isactual_idx ON apartments_22 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_22_isactive_idx ON apartments_22 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_23 (CONSTRAINT apartments_23_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_23_objectid_idx ON apartments_23 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_23_aparttype_idx ON apartments_23 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_23_startdate_idx ON apartments_23 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_23_enddate_idx ON apartments_23 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_23_isactual_idx ON apartments_23 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_23_isactive_idx ON apartments_23 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_24 (CONSTRAINT apartments_24_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_24_objectid_idx ON apartments_24 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_24_aparttype_idx ON apartments_24 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_24_startdate_idx ON apartments_24 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_24_enddate_idx ON apartments_24 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_24_isactual_idx ON apartments_24 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_24_isactive_idx ON apartments_24 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_25 (CONSTRAINT apartments_25_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_25_objectid_idx ON apartments_25 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_25_aparttype_idx ON apartments_25 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_25_startdate_idx ON apartments_25 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_25_enddate_idx ON apartments_25 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_25_isactual_idx ON apartments_25 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_25_isactive_idx ON apartments_25 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_26 (CONSTRAINT apartments_26_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_26_objectid_idx ON apartments_26 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_26_aparttype_idx ON apartments_26 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_26_startdate_idx ON apartments_26 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_26_enddate_idx ON apartments_26 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_26_isactual_idx ON apartments_26 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_26_isactive_idx ON apartments_26 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_27 (CONSTRAINT apartments_27_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_27_objectid_idx ON apartments_27 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_27_aparttype_idx ON apartments_27 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_27_startdate_idx ON apartments_27 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_27_enddate_idx ON apartments_27 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_27_isactual_idx ON apartments_27 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_27_isactive_idx ON apartments_27 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_28 (CONSTRAINT apartments_28_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_28_objectid_idx ON apartments_28 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_28_aparttype_idx ON apartments_28 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_28_startdate_idx ON apartments_28 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_28_enddate_idx ON apartments_28 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_28_isactual_idx ON apartments_28 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_28_isactive_idx ON apartments_28 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_29 (CONSTRAINT apartments_29_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_29_objectid_idx ON apartments_29 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_29_aparttype_idx ON apartments_29 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_29_startdate_idx ON apartments_29 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_29_enddate_idx ON apartments_29 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_29_isactual_idx ON apartments_29 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_29_isactive_idx ON apartments_29 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_30 (CONSTRAINT apartments_30_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_30_objectid_idx ON apartments_30 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_30_aparttype_idx ON apartments_30 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_30_startdate_idx ON apartments_30 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_30_enddate_idx ON apartments_30 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_30_isactual_idx ON apartments_30 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_30_isactive_idx ON apartments_30 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_31 (CONSTRAINT apartments_31_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_31_objectid_idx ON apartments_31 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_31_aparttype_idx ON apartments_31 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_31_startdate_idx ON apartments_31 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_31_enddate_idx ON apartments_31 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_31_isactual_idx ON apartments_31 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_31_isactive_idx ON apartments_31 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_32 (CONSTRAINT apartments_32_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_32_objectid_idx ON apartments_32 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_32_aparttype_idx ON apartments_32 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_32_startdate_idx ON apartments_32 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_32_enddate_idx ON apartments_32 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_32_isactual_idx ON apartments_32 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_32_isactive_idx ON apartments_32 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_33 (CONSTRAINT apartments_33_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_33_objectid_idx ON apartments_33 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_33_aparttype_idx ON apartments_33 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_33_startdate_idx ON apartments_33 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_33_enddate_idx ON apartments_33 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_33_isactual_idx ON apartments_33 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_33_isactive_idx ON apartments_33 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_34 (CONSTRAINT apartments_34_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_34_objectid_idx ON apartments_34 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_34_aparttype_idx ON apartments_34 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_34_startdate_idx ON apartments_34 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_34_enddate_idx ON apartments_34 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_34_isactual_idx ON apartments_34 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_34_isactive_idx ON apartments_34 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_35 (CONSTRAINT apartments_35_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_35_objectid_idx ON apartments_35 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_35_aparttype_idx ON apartments_35 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_35_startdate_idx ON apartments_35 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_35_enddate_idx ON apartments_35 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_35_isactual_idx ON apartments_35 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_35_isactive_idx ON apartments_35 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_36 (CONSTRAINT apartments_36_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_36_objectid_idx ON apartments_36 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_36_aparttype_idx ON apartments_36 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_36_startdate_idx ON apartments_36 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_36_enddate_idx ON apartments_36 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_36_isactual_idx ON apartments_36 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_36_isactive_idx ON apartments_36 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_37 (CONSTRAINT apartments_37_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_37_objectid_idx ON apartments_37 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_37_aparttype_idx ON apartments_37 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_37_startdate_idx ON apartments_37 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_37_enddate_idx ON apartments_37 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_37_isactual_idx ON apartments_37 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_37_isactive_idx ON apartments_37 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_38 (CONSTRAINT apartments_38_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_38_objectid_idx ON apartments_38 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_38_aparttype_idx ON apartments_38 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_38_startdate_idx ON apartments_38 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_38_enddate_idx ON apartments_38 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_38_isactual_idx ON apartments_38 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_38_isactive_idx ON apartments_38 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_39 (CONSTRAINT apartments_39_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_39_objectid_idx ON apartments_39 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_39_aparttype_idx ON apartments_39 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_39_startdate_idx ON apartments_39 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_39_enddate_idx ON apartments_39 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_39_isactual_idx ON apartments_39 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_39_isactive_idx ON apartments_39 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_40 (CONSTRAINT apartments_40_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_40_objectid_idx ON apartments_40 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_40_aparttype_idx ON apartments_40 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_40_startdate_idx ON apartments_40 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_40_enddate_idx ON apartments_40 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_40_isactual_idx ON apartments_40 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_40_isactive_idx ON apartments_40 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_41 (CONSTRAINT apartments_41_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_41_objectid_idx ON apartments_41 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_41_aparttype_idx ON apartments_41 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_41_startdate_idx ON apartments_41 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_41_enddate_idx ON apartments_41 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_41_isactual_idx ON apartments_41 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_41_isactive_idx ON apartments_41 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_42 (CONSTRAINT apartments_42_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_42_objectid_idx ON apartments_42 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_42_aparttype_idx ON apartments_42 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_42_startdate_idx ON apartments_42 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_42_enddate_idx ON apartments_42 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_42_isactual_idx ON apartments_42 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_42_isactive_idx ON apartments_42 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_43 (CONSTRAINT apartments_43_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_43_objectid_idx ON apartments_43 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_43_aparttype_idx ON apartments_43 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_43_startdate_idx ON apartments_43 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_43_enddate_idx ON apartments_43 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_43_isactual_idx ON apartments_43 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_43_isactive_idx ON apartments_43 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_44 (CONSTRAINT apartments_44_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_44_objectid_idx ON apartments_44 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_44_aparttype_idx ON apartments_44 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_44_startdate_idx ON apartments_44 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_44_enddate_idx ON apartments_44 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_44_isactual_idx ON apartments_44 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_44_isactive_idx ON apartments_44 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_45 (CONSTRAINT apartments_45_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_45_objectid_idx ON apartments_45 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_45_aparttype_idx ON apartments_45 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_45_startdate_idx ON apartments_45 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_45_enddate_idx ON apartments_45 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_45_isactual_idx ON apartments_45 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_45_isactive_idx ON apartments_45 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_46 (CONSTRAINT apartments_46_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_46_objectid_idx ON apartments_46 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_46_aparttype_idx ON apartments_46 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_46_startdate_idx ON apartments_46 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_46_enddate_idx ON apartments_46 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_46_isactual_idx ON apartments_46 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_46_isactive_idx ON apartments_46 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_47 (CONSTRAINT apartments_47_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_47_objectid_idx ON apartments_47 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_47_aparttype_idx ON apartments_47 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_47_startdate_idx ON apartments_47 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_47_enddate_idx ON apartments_47 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_47_isactual_idx ON apartments_47 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_47_isactive_idx ON apartments_47 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_48 (CONSTRAINT apartments_48_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_48_objectid_idx ON apartments_48 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_48_aparttype_idx ON apartments_48 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_48_startdate_idx ON apartments_48 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_48_enddate_idx ON apartments_48 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_48_isactual_idx ON apartments_48 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_48_isactive_idx ON apartments_48 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_49 (CONSTRAINT apartments_49_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_49_objectid_idx ON apartments_49 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_49_aparttype_idx ON apartments_49 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_49_startdate_idx ON apartments_49 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_49_enddate_idx ON apartments_49 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_49_isactual_idx ON apartments_49 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_49_isactive_idx ON apartments_49 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_50 (CONSTRAINT apartments_50_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_50_objectid_idx ON apartments_50 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_50_aparttype_idx ON apartments_50 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_50_startdate_idx ON apartments_50 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_50_enddate_idx ON apartments_50 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_50_isactual_idx ON apartments_50 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_50_isactive_idx ON apartments_50 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_51 (CONSTRAINT apartments_51_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_51_objectid_idx ON apartments_51 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_51_aparttype_idx ON apartments_51 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_51_startdate_idx ON apartments_51 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_51_enddate_idx ON apartments_51 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_51_isactual_idx ON apartments_51 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_51_isactive_idx ON apartments_51 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_52 (CONSTRAINT apartments_52_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_52_objectid_idx ON apartments_52 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_52_aparttype_idx ON apartments_52 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_52_startdate_idx ON apartments_52 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_52_enddate_idx ON apartments_52 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_52_isactual_idx ON apartments_52 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_52_isactive_idx ON apartments_52 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_53 (CONSTRAINT apartments_53_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_53_objectid_idx ON apartments_53 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_53_aparttype_idx ON apartments_53 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_53_startdate_idx ON apartments_53 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_53_enddate_idx ON apartments_53 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_53_isactual_idx ON apartments_53 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_53_isactive_idx ON apartments_53 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_54 (CONSTRAINT apartments_54_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_54_objectid_idx ON apartments_54 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_54_aparttype_idx ON apartments_54 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_54_startdate_idx ON apartments_54 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_54_enddate_idx ON apartments_54 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_54_isactual_idx ON apartments_54 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_54_isactive_idx ON apartments_54 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_55 (CONSTRAINT apartments_55_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_55_objectid_idx ON apartments_55 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_55_aparttype_idx ON apartments_55 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_55_startdate_idx ON apartments_55 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_55_enddate_idx ON apartments_55 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_55_isactual_idx ON apartments_55 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_55_isactive_idx ON apartments_55 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_56 (CONSTRAINT apartments_56_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_56_objectid_idx ON apartments_56 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_56_aparttype_idx ON apartments_56 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_56_startdate_idx ON apartments_56 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_56_enddate_idx ON apartments_56 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_56_isactual_idx ON apartments_56 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_56_isactive_idx ON apartments_56 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_57 (CONSTRAINT apartments_57_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_57_objectid_idx ON apartments_57 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_57_aparttype_idx ON apartments_57 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_57_startdate_idx ON apartments_57 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_57_enddate_idx ON apartments_57 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_57_isactual_idx ON apartments_57 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_57_isactive_idx ON apartments_57 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_58 (CONSTRAINT apartments_58_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_58_objectid_idx ON apartments_58 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_58_aparttype_idx ON apartments_58 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_58_startdate_idx ON apartments_58 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_58_enddate_idx ON apartments_58 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_58_isactual_idx ON apartments_58 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_58_isactive_idx ON apartments_58 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_59 (CONSTRAINT apartments_59_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_59_objectid_idx ON apartments_59 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_59_aparttype_idx ON apartments_59 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_59_startdate_idx ON apartments_59 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_59_enddate_idx ON apartments_59 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_59_isactual_idx ON apartments_59 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_59_isactive_idx ON apartments_59 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_60 (CONSTRAINT apartments_60_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_60_objectid_idx ON apartments_60 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_60_aparttype_idx ON apartments_60 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_60_startdate_idx ON apartments_60 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_60_enddate_idx ON apartments_60 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_60_isactual_idx ON apartments_60 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_60_isactive_idx ON apartments_60 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_61 (CONSTRAINT apartments_61_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_61_objectid_idx ON apartments_61 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_61_aparttype_idx ON apartments_61 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_61_startdate_idx ON apartments_61 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_61_enddate_idx ON apartments_61 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_61_isactual_idx ON apartments_61 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_61_isactive_idx ON apartments_61 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_62 (CONSTRAINT apartments_62_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_62_objectid_idx ON apartments_62 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_62_aparttype_idx ON apartments_62 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_62_startdate_idx ON apartments_62 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_62_enddate_idx ON apartments_62 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_62_isactual_idx ON apartments_62 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_62_isactive_idx ON apartments_62 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_63 (CONSTRAINT apartments_63_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_63_objectid_idx ON apartments_63 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_63_aparttype_idx ON apartments_63 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_63_startdate_idx ON apartments_63 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_63_enddate_idx ON apartments_63 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_63_isactual_idx ON apartments_63 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_63_isactive_idx ON apartments_63 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_64 (CONSTRAINT apartments_64_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_64_objectid_idx ON apartments_64 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_64_aparttype_idx ON apartments_64 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_64_startdate_idx ON apartments_64 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_64_enddate_idx ON apartments_64 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_64_isactual_idx ON apartments_64 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_64_isactive_idx ON apartments_64 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_65 (CONSTRAINT apartments_65_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_65_objectid_idx ON apartments_65 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_65_aparttype_idx ON apartments_65 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_65_startdate_idx ON apartments_65 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_65_enddate_idx ON apartments_65 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_65_isactual_idx ON apartments_65 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_65_isactive_idx ON apartments_65 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_66 (CONSTRAINT apartments_66_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_66_objectid_idx ON apartments_66 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_66_aparttype_idx ON apartments_66 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_66_startdate_idx ON apartments_66 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_66_enddate_idx ON apartments_66 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_66_isactual_idx ON apartments_66 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_66_isactive_idx ON apartments_66 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_67 (CONSTRAINT apartments_67_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_67_objectid_idx ON apartments_67 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_67_aparttype_idx ON apartments_67 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_67_startdate_idx ON apartments_67 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_67_enddate_idx ON apartments_67 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_67_isactual_idx ON apartments_67 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_67_isactive_idx ON apartments_67 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_68 (CONSTRAINT apartments_68_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_68_objectid_idx ON apartments_68 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_68_aparttype_idx ON apartments_68 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_68_startdate_idx ON apartments_68 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_68_enddate_idx ON apartments_68 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_68_isactual_idx ON apartments_68 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_68_isactive_idx ON apartments_68 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_69 (CONSTRAINT apartments_69_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_69_objectid_idx ON apartments_69 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_69_aparttype_idx ON apartments_69 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_69_startdate_idx ON apartments_69 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_69_enddate_idx ON apartments_69 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_69_isactual_idx ON apartments_69 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_69_isactive_idx ON apartments_69 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_70 (CONSTRAINT apartments_70_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_70_objectid_idx ON apartments_70 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_70_aparttype_idx ON apartments_70 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_70_startdate_idx ON apartments_70 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_70_enddate_idx ON apartments_70 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_70_isactual_idx ON apartments_70 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_70_isactive_idx ON apartments_70 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_71 (CONSTRAINT apartments_71_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_71_objectid_idx ON apartments_71 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_71_aparttype_idx ON apartments_71 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_71_startdate_idx ON apartments_71 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_71_enddate_idx ON apartments_71 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_71_isactual_idx ON apartments_71 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_71_isactive_idx ON apartments_71 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_72 (CONSTRAINT apartments_72_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_72_objectid_idx ON apartments_72 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_72_aparttype_idx ON apartments_72 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_72_startdate_idx ON apartments_72 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_72_enddate_idx ON apartments_72 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_72_isactual_idx ON apartments_72 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_72_isactive_idx ON apartments_72 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_73 (CONSTRAINT apartments_73_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_73_objectid_idx ON apartments_73 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_73_aparttype_idx ON apartments_73 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_73_startdate_idx ON apartments_73 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_73_enddate_idx ON apartments_73 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_73_isactual_idx ON apartments_73 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_73_isactive_idx ON apartments_73 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_74 (CONSTRAINT apartments_74_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_74_objectid_idx ON apartments_74 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_74_aparttype_idx ON apartments_74 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_74_startdate_idx ON apartments_74 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_74_enddate_idx ON apartments_74 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_74_isactual_idx ON apartments_74 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_74_isactive_idx ON apartments_74 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_75 (CONSTRAINT apartments_75_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_75_objectid_idx ON apartments_75 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_75_aparttype_idx ON apartments_75 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_75_startdate_idx ON apartments_75 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_75_enddate_idx ON apartments_75 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_75_isactual_idx ON apartments_75 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_75_isactive_idx ON apartments_75 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_76 (CONSTRAINT apartments_76_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_76_objectid_idx ON apartments_76 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_76_aparttype_idx ON apartments_76 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_76_startdate_idx ON apartments_76 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_76_enddate_idx ON apartments_76 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_76_isactual_idx ON apartments_76 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_76_isactive_idx ON apartments_76 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_77 (CONSTRAINT apartments_77_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_77_objectid_idx ON apartments_77 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_77_aparttype_idx ON apartments_77 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_77_startdate_idx ON apartments_77 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_77_enddate_idx ON apartments_77 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_77_isactual_idx ON apartments_77 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_77_isactive_idx ON apartments_77 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_78 (CONSTRAINT apartments_78_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_78_objectid_idx ON apartments_78 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_78_aparttype_idx ON apartments_78 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_78_startdate_idx ON apartments_78 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_78_enddate_idx ON apartments_78 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_78_isactual_idx ON apartments_78 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_78_isactive_idx ON apartments_78 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_79 (CONSTRAINT apartments_79_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_79_objectid_idx ON apartments_79 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_79_aparttype_idx ON apartments_79 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_79_startdate_idx ON apartments_79 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_79_enddate_idx ON apartments_79 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_79_isactual_idx ON apartments_79 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_79_isactive_idx ON apartments_79 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_80 (CONSTRAINT apartments_80_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_80_objectid_idx ON apartments_80 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_80_aparttype_idx ON apartments_80 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_80_startdate_idx ON apartments_80 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_80_enddate_idx ON apartments_80 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_80_isactual_idx ON apartments_80 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_80_isactive_idx ON apartments_80 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_81 (CONSTRAINT apartments_81_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_81_objectid_idx ON apartments_81 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_81_aparttype_idx ON apartments_81 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_81_startdate_idx ON apartments_81 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_81_enddate_idx ON apartments_81 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_81_isactual_idx ON apartments_81 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_81_isactive_idx ON apartments_81 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_82 (CONSTRAINT apartments_82_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_82_objectid_idx ON apartments_82 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_82_aparttype_idx ON apartments_82 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_82_startdate_idx ON apartments_82 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_82_enddate_idx ON apartments_82 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_82_isactual_idx ON apartments_82 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_82_isactive_idx ON apartments_82 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_83 (CONSTRAINT apartments_83_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_83_objectid_idx ON apartments_83 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_83_aparttype_idx ON apartments_83 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_83_startdate_idx ON apartments_83 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_83_enddate_idx ON apartments_83 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_83_isactual_idx ON apartments_83 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_83_isactive_idx ON apartments_83 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_84 (CONSTRAINT apartments_84_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_84_objectid_idx ON apartments_84 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_84_aparttype_idx ON apartments_84 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_84_startdate_idx ON apartments_84 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_84_enddate_idx ON apartments_84 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_84_isactual_idx ON apartments_84 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_84_isactive_idx ON apartments_84 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_85 (CONSTRAINT apartments_85_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_85_objectid_idx ON apartments_85 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_85_aparttype_idx ON apartments_85 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_85_startdate_idx ON apartments_85 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_85_enddate_idx ON apartments_85 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_85_isactual_idx ON apartments_85 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_85_isactive_idx ON apartments_85 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_86 (CONSTRAINT apartments_86_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_86_objectid_idx ON apartments_86 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_86_aparttype_idx ON apartments_86 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_86_startdate_idx ON apartments_86 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_86_enddate_idx ON apartments_86 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_86_isactual_idx ON apartments_86 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_86_isactive_idx ON apartments_86 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_87 (CONSTRAINT apartments_87_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_87_objectid_idx ON apartments_87 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_87_aparttype_idx ON apartments_87 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_87_startdate_idx ON apartments_87 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_87_enddate_idx ON apartments_87 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_87_isactual_idx ON apartments_87 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_87_isactive_idx ON apartments_87 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_88 (CONSTRAINT apartments_88_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_88_objectid_idx ON apartments_88 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_88_aparttype_idx ON apartments_88 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_88_startdate_idx ON apartments_88 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_88_enddate_idx ON apartments_88 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_88_isactual_idx ON apartments_88 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_88_isactive_idx ON apartments_88 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_89 (CONSTRAINT apartments_89_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_89_objectid_idx ON apartments_89 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_89_aparttype_idx ON apartments_89 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_89_startdate_idx ON apartments_89 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_89_enddate_idx ON apartments_89 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_89_isactual_idx ON apartments_89 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_89_isactive_idx ON apartments_89 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_90 (CONSTRAINT apartments_90_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_90_objectid_idx ON apartments_90 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_90_aparttype_idx ON apartments_90 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_90_startdate_idx ON apartments_90 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_90_enddate_idx ON apartments_90 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_90_isactual_idx ON apartments_90 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_90_isactive_idx ON apartments_90 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_91 (CONSTRAINT apartments_91_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_91_objectid_idx ON apartments_91 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_91_aparttype_idx ON apartments_91 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_91_startdate_idx ON apartments_91 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_91_enddate_idx ON apartments_91 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_91_isactual_idx ON apartments_91 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_91_isactive_idx ON apartments_91 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_92 (CONSTRAINT apartments_92_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_92_objectid_idx ON apartments_92 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_92_aparttype_idx ON apartments_92 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_92_startdate_idx ON apartments_92 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_92_enddate_idx ON apartments_92 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_92_isactual_idx ON apartments_92 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_92_isactive_idx ON apartments_92 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_93 (CONSTRAINT apartments_93_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_93_objectid_idx ON apartments_93 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_93_aparttype_idx ON apartments_93 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_93_startdate_idx ON apartments_93 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_93_enddate_idx ON apartments_93 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_93_isactual_idx ON apartments_93 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_93_isactive_idx ON apartments_93 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_94 (CONSTRAINT apartments_94_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_94_objectid_idx ON apartments_94 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_94_aparttype_idx ON apartments_94 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_94_startdate_idx ON apartments_94 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_94_enddate_idx ON apartments_94 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_94_isactual_idx ON apartments_94 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_94_isactive_idx ON apartments_94 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_95 (CONSTRAINT apartments_95_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_95_objectid_idx ON apartments_95 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_95_aparttype_idx ON apartments_95 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_95_startdate_idx ON apartments_95 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_95_enddate_idx ON apartments_95 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_95_isactual_idx ON apartments_95 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_95_isactive_idx ON apartments_95 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_96 (CONSTRAINT apartments_96_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_96_objectid_idx ON apartments_96 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_96_aparttype_idx ON apartments_96 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_96_startdate_idx ON apartments_96 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_96_enddate_idx ON apartments_96 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_96_isactual_idx ON apartments_96 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_96_isactive_idx ON apartments_96 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_97 (CONSTRAINT apartments_97_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_97_objectid_idx ON apartments_97 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_97_aparttype_idx ON apartments_97 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_97_startdate_idx ON apartments_97 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_97_enddate_idx ON apartments_97 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_97_isactual_idx ON apartments_97 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_97_isactive_idx ON apartments_97 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_98 (CONSTRAINT apartments_98_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_98_objectid_idx ON apartments_98 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_98_aparttype_idx ON apartments_98 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_98_startdate_idx ON apartments_98 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_98_enddate_idx ON apartments_98 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_98_isactual_idx ON apartments_98 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_98_isactive_idx ON apartments_98 USING btree (isactive);
CREATE TABLE IF NOT EXISTS apartments_99 (CONSTRAINT apartments_99_pkey PRIMARY KEY (id)) INHERITS (apartments);
CREATE INDEX IF NOT EXISTS apartments_99_objectid_idx ON apartments_99 USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_99_aparttype_idx ON apartments_99 USING btree (aparttype);
CREATE INDEX IF NOT EXISTS apartments_99_startdate_idx ON apartments_99 USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_99_enddate_idx ON apartments_99 USING btree (enddate);
CREATE INDEX IF NOT EXISTS apartments_99_isactual_idx ON apartments_99 USING btree (isactual);
CREATE INDEX IF NOT EXISTS apartments_99_isactive_idx ON apartments_99 USING btree (isactive);
