CREATE TABLE IF NOT EXISTS carplaces (
  id BIGINT NOT NULL PRIMARY KEY,
  objectid BIGINT NOT NULL,
  objectguid UUID NOT NULL,
  changeid BIGINT NOT NULL,
  number VARCHAR(50) NOT NULL,
  opertypeid INT NOT NULL,
  previd BIGINT,
  nextid BIGINT,
  updatedate DATE NOT NULL,
  startdate DATE NOT NULL,
  enddate DATE NOT NULL,
  isactual SMALLINT NOT NULL,
  isactive SMALLINT NOT NULL
);
COMMENT ON TABLE carplaces IS 'Сведения по машино-местам';
COMMENT ON COLUMN carplaces.id IS 'Уникальный идентификатор записи. Ключевое поле';
COMMENT ON COLUMN carplaces.objectid IS 'Глобальный уникальный идентификатор объекта типа INTEGER';
COMMENT ON COLUMN carplaces.objectguid IS 'Глобальный уникальный идентификатор адресного объекта типа UUID';
COMMENT ON COLUMN carplaces.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN carplaces.number IS 'Номер машиноместа';
COMMENT ON COLUMN carplaces.opertypeid IS 'Статус действия над записью – причина появления записи';
COMMENT ON COLUMN carplaces.previd IS 'Идентификатор записи связывания с предыдущей исторической записью';
COMMENT ON COLUMN carplaces.nextid IS 'Идентификатор записи связывания с последующей исторической записью';
COMMENT ON COLUMN carplaces.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN carplaces.startdate IS 'Начало действия записи';
COMMENT ON COLUMN carplaces.enddate IS 'Окончание действия записи';
COMMENT ON COLUMN carplaces.isactual IS 'Статус актуальности адресного объекта ФИАС';
COMMENT ON COLUMN carplaces.isactive IS 'Признак действующего адресного объекта';
CREATE INDEX IF NOT EXISTS carplaces_objectid_idx ON carplaces USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_startdate_idx ON carplaces USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_enddate_idx ON carplaces USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_isactual_idx ON carplaces USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_isactive_idx ON carplaces USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_01 (CONSTRAINT carplaces_01_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_01_objectid_idx ON carplaces_01 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_01_startdate_idx ON carplaces_01 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_01_enddate_idx ON carplaces_01 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_01_isactual_idx ON carplaces_01 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_01_isactive_idx ON carplaces_01 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_02 (CONSTRAINT carplaces_02_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_02_objectid_idx ON carplaces_02 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_02_startdate_idx ON carplaces_02 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_02_enddate_idx ON carplaces_02 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_02_isactual_idx ON carplaces_02 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_02_isactive_idx ON carplaces_02 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_03 (CONSTRAINT carplaces_03_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_03_objectid_idx ON carplaces_03 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_03_startdate_idx ON carplaces_03 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_03_enddate_idx ON carplaces_03 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_03_isactual_idx ON carplaces_03 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_03_isactive_idx ON carplaces_03 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_04 (CONSTRAINT carplaces_04_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_04_objectid_idx ON carplaces_04 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_04_startdate_idx ON carplaces_04 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_04_enddate_idx ON carplaces_04 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_04_isactual_idx ON carplaces_04 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_04_isactive_idx ON carplaces_04 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_05 (CONSTRAINT carplaces_05_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_05_objectid_idx ON carplaces_05 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_05_startdate_idx ON carplaces_05 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_05_enddate_idx ON carplaces_05 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_05_isactual_idx ON carplaces_05 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_05_isactive_idx ON carplaces_05 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_06 (CONSTRAINT carplaces_06_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_06_objectid_idx ON carplaces_06 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_06_startdate_idx ON carplaces_06 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_06_enddate_idx ON carplaces_06 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_06_isactual_idx ON carplaces_06 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_06_isactive_idx ON carplaces_06 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_07 (CONSTRAINT carplaces_07_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_07_objectid_idx ON carplaces_07 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_07_startdate_idx ON carplaces_07 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_07_enddate_idx ON carplaces_07 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_07_isactual_idx ON carplaces_07 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_07_isactive_idx ON carplaces_07 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_08 (CONSTRAINT carplaces_08_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_08_objectid_idx ON carplaces_08 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_08_startdate_idx ON carplaces_08 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_08_enddate_idx ON carplaces_08 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_08_isactual_idx ON carplaces_08 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_08_isactive_idx ON carplaces_08 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_09 (CONSTRAINT carplaces_09_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_09_objectid_idx ON carplaces_09 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_09_startdate_idx ON carplaces_09 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_09_enddate_idx ON carplaces_09 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_09_isactual_idx ON carplaces_09 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_09_isactive_idx ON carplaces_09 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_10 (CONSTRAINT carplaces_10_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_10_objectid_idx ON carplaces_10 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_10_startdate_idx ON carplaces_10 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_10_enddate_idx ON carplaces_10 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_10_isactual_idx ON carplaces_10 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_10_isactive_idx ON carplaces_10 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_11 (CONSTRAINT carplaces_11_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_11_objectid_idx ON carplaces_11 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_11_startdate_idx ON carplaces_11 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_11_enddate_idx ON carplaces_11 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_11_isactual_idx ON carplaces_11 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_11_isactive_idx ON carplaces_11 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_12 (CONSTRAINT carplaces_12_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_12_objectid_idx ON carplaces_12 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_12_startdate_idx ON carplaces_12 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_12_enddate_idx ON carplaces_12 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_12_isactual_idx ON carplaces_12 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_12_isactive_idx ON carplaces_12 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_13 (CONSTRAINT carplaces_13_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_13_objectid_idx ON carplaces_13 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_13_startdate_idx ON carplaces_13 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_13_enddate_idx ON carplaces_13 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_13_isactual_idx ON carplaces_13 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_13_isactive_idx ON carplaces_13 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_14 (CONSTRAINT carplaces_14_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_14_objectid_idx ON carplaces_14 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_14_startdate_idx ON carplaces_14 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_14_enddate_idx ON carplaces_14 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_14_isactual_idx ON carplaces_14 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_14_isactive_idx ON carplaces_14 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_15 (CONSTRAINT carplaces_15_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_15_objectid_idx ON carplaces_15 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_15_startdate_idx ON carplaces_15 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_15_enddate_idx ON carplaces_15 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_15_isactual_idx ON carplaces_15 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_15_isactive_idx ON carplaces_15 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_16 (CONSTRAINT carplaces_16_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_16_objectid_idx ON carplaces_16 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_16_startdate_idx ON carplaces_16 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_16_enddate_idx ON carplaces_16 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_16_isactual_idx ON carplaces_16 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_16_isactive_idx ON carplaces_16 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_17 (CONSTRAINT carplaces_17_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_17_objectid_idx ON carplaces_17 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_17_startdate_idx ON carplaces_17 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_17_enddate_idx ON carplaces_17 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_17_isactual_idx ON carplaces_17 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_17_isactive_idx ON carplaces_17 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_18 (CONSTRAINT carplaces_18_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_18_objectid_idx ON carplaces_18 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_18_startdate_idx ON carplaces_18 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_18_enddate_idx ON carplaces_18 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_18_isactual_idx ON carplaces_18 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_18_isactive_idx ON carplaces_18 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_19 (CONSTRAINT carplaces_19_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_19_objectid_idx ON carplaces_19 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_19_startdate_idx ON carplaces_19 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_19_enddate_idx ON carplaces_19 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_19_isactual_idx ON carplaces_19 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_19_isactive_idx ON carplaces_19 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_20 (CONSTRAINT carplaces_20_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_20_objectid_idx ON carplaces_20 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_20_startdate_idx ON carplaces_20 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_20_enddate_idx ON carplaces_20 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_20_isactual_idx ON carplaces_20 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_20_isactive_idx ON carplaces_20 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_21 (CONSTRAINT carplaces_21_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_21_objectid_idx ON carplaces_21 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_21_startdate_idx ON carplaces_21 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_21_enddate_idx ON carplaces_21 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_21_isactual_idx ON carplaces_21 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_21_isactive_idx ON carplaces_21 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_22 (CONSTRAINT carplaces_22_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_22_objectid_idx ON carplaces_22 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_22_startdate_idx ON carplaces_22 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_22_enddate_idx ON carplaces_22 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_22_isactual_idx ON carplaces_22 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_22_isactive_idx ON carplaces_22 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_23 (CONSTRAINT carplaces_23_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_23_objectid_idx ON carplaces_23 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_23_startdate_idx ON carplaces_23 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_23_enddate_idx ON carplaces_23 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_23_isactual_idx ON carplaces_23 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_23_isactive_idx ON carplaces_23 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_24 (CONSTRAINT carplaces_24_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_24_objectid_idx ON carplaces_24 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_24_startdate_idx ON carplaces_24 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_24_enddate_idx ON carplaces_24 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_24_isactual_idx ON carplaces_24 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_24_isactive_idx ON carplaces_24 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_25 (CONSTRAINT carplaces_25_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_25_objectid_idx ON carplaces_25 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_25_startdate_idx ON carplaces_25 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_25_enddate_idx ON carplaces_25 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_25_isactual_idx ON carplaces_25 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_25_isactive_idx ON carplaces_25 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_26 (CONSTRAINT carplaces_26_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_26_objectid_idx ON carplaces_26 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_26_startdate_idx ON carplaces_26 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_26_enddate_idx ON carplaces_26 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_26_isactual_idx ON carplaces_26 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_26_isactive_idx ON carplaces_26 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_27 (CONSTRAINT carplaces_27_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_27_objectid_idx ON carplaces_27 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_27_startdate_idx ON carplaces_27 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_27_enddate_idx ON carplaces_27 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_27_isactual_idx ON carplaces_27 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_27_isactive_idx ON carplaces_27 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_28 (CONSTRAINT carplaces_28_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_28_objectid_idx ON carplaces_28 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_28_startdate_idx ON carplaces_28 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_28_enddate_idx ON carplaces_28 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_28_isactual_idx ON carplaces_28 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_28_isactive_idx ON carplaces_28 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_29 (CONSTRAINT carplaces_29_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_29_objectid_idx ON carplaces_29 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_29_startdate_idx ON carplaces_29 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_29_enddate_idx ON carplaces_29 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_29_isactual_idx ON carplaces_29 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_29_isactive_idx ON carplaces_29 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_30 (CONSTRAINT carplaces_30_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_30_objectid_idx ON carplaces_30 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_30_startdate_idx ON carplaces_30 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_30_enddate_idx ON carplaces_30 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_30_isactual_idx ON carplaces_30 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_30_isactive_idx ON carplaces_30 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_31 (CONSTRAINT carplaces_31_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_31_objectid_idx ON carplaces_31 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_31_startdate_idx ON carplaces_31 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_31_enddate_idx ON carplaces_31 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_31_isactual_idx ON carplaces_31 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_31_isactive_idx ON carplaces_31 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_32 (CONSTRAINT carplaces_32_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_32_objectid_idx ON carplaces_32 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_32_startdate_idx ON carplaces_32 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_32_enddate_idx ON carplaces_32 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_32_isactual_idx ON carplaces_32 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_32_isactive_idx ON carplaces_32 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_33 (CONSTRAINT carplaces_33_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_33_objectid_idx ON carplaces_33 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_33_startdate_idx ON carplaces_33 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_33_enddate_idx ON carplaces_33 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_33_isactual_idx ON carplaces_33 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_33_isactive_idx ON carplaces_33 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_34 (CONSTRAINT carplaces_34_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_34_objectid_idx ON carplaces_34 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_34_startdate_idx ON carplaces_34 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_34_enddate_idx ON carplaces_34 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_34_isactual_idx ON carplaces_34 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_34_isactive_idx ON carplaces_34 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_35 (CONSTRAINT carplaces_35_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_35_objectid_idx ON carplaces_35 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_35_startdate_idx ON carplaces_35 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_35_enddate_idx ON carplaces_35 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_35_isactual_idx ON carplaces_35 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_35_isactive_idx ON carplaces_35 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_36 (CONSTRAINT carplaces_36_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_36_objectid_idx ON carplaces_36 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_36_startdate_idx ON carplaces_36 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_36_enddate_idx ON carplaces_36 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_36_isactual_idx ON carplaces_36 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_36_isactive_idx ON carplaces_36 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_37 (CONSTRAINT carplaces_37_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_37_objectid_idx ON carplaces_37 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_37_startdate_idx ON carplaces_37 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_37_enddate_idx ON carplaces_37 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_37_isactual_idx ON carplaces_37 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_37_isactive_idx ON carplaces_37 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_38 (CONSTRAINT carplaces_38_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_38_objectid_idx ON carplaces_38 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_38_startdate_idx ON carplaces_38 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_38_enddate_idx ON carplaces_38 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_38_isactual_idx ON carplaces_38 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_38_isactive_idx ON carplaces_38 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_39 (CONSTRAINT carplaces_39_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_39_objectid_idx ON carplaces_39 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_39_startdate_idx ON carplaces_39 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_39_enddate_idx ON carplaces_39 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_39_isactual_idx ON carplaces_39 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_39_isactive_idx ON carplaces_39 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_40 (CONSTRAINT carplaces_40_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_40_objectid_idx ON carplaces_40 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_40_startdate_idx ON carplaces_40 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_40_enddate_idx ON carplaces_40 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_40_isactual_idx ON carplaces_40 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_40_isactive_idx ON carplaces_40 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_41 (CONSTRAINT carplaces_41_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_41_objectid_idx ON carplaces_41 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_41_startdate_idx ON carplaces_41 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_41_enddate_idx ON carplaces_41 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_41_isactual_idx ON carplaces_41 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_41_isactive_idx ON carplaces_41 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_42 (CONSTRAINT carplaces_42_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_42_objectid_idx ON carplaces_42 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_42_startdate_idx ON carplaces_42 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_42_enddate_idx ON carplaces_42 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_42_isactual_idx ON carplaces_42 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_42_isactive_idx ON carplaces_42 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_43 (CONSTRAINT carplaces_43_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_43_objectid_idx ON carplaces_43 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_43_startdate_idx ON carplaces_43 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_43_enddate_idx ON carplaces_43 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_43_isactual_idx ON carplaces_43 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_43_isactive_idx ON carplaces_43 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_44 (CONSTRAINT carplaces_44_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_44_objectid_idx ON carplaces_44 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_44_startdate_idx ON carplaces_44 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_44_enddate_idx ON carplaces_44 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_44_isactual_idx ON carplaces_44 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_44_isactive_idx ON carplaces_44 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_45 (CONSTRAINT carplaces_45_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_45_objectid_idx ON carplaces_45 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_45_startdate_idx ON carplaces_45 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_45_enddate_idx ON carplaces_45 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_45_isactual_idx ON carplaces_45 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_45_isactive_idx ON carplaces_45 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_46 (CONSTRAINT carplaces_46_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_46_objectid_idx ON carplaces_46 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_46_startdate_idx ON carplaces_46 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_46_enddate_idx ON carplaces_46 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_46_isactual_idx ON carplaces_46 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_46_isactive_idx ON carplaces_46 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_47 (CONSTRAINT carplaces_47_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_47_objectid_idx ON carplaces_47 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_47_startdate_idx ON carplaces_47 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_47_enddate_idx ON carplaces_47 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_47_isactual_idx ON carplaces_47 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_47_isactive_idx ON carplaces_47 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_48 (CONSTRAINT carplaces_48_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_48_objectid_idx ON carplaces_48 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_48_startdate_idx ON carplaces_48 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_48_enddate_idx ON carplaces_48 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_48_isactual_idx ON carplaces_48 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_48_isactive_idx ON carplaces_48 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_49 (CONSTRAINT carplaces_49_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_49_objectid_idx ON carplaces_49 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_49_startdate_idx ON carplaces_49 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_49_enddate_idx ON carplaces_49 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_49_isactual_idx ON carplaces_49 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_49_isactive_idx ON carplaces_49 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_50 (CONSTRAINT carplaces_50_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_50_objectid_idx ON carplaces_50 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_50_startdate_idx ON carplaces_50 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_50_enddate_idx ON carplaces_50 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_50_isactual_idx ON carplaces_50 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_50_isactive_idx ON carplaces_50 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_51 (CONSTRAINT carplaces_51_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_51_objectid_idx ON carplaces_51 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_51_startdate_idx ON carplaces_51 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_51_enddate_idx ON carplaces_51 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_51_isactual_idx ON carplaces_51 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_51_isactive_idx ON carplaces_51 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_52 (CONSTRAINT carplaces_52_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_52_objectid_idx ON carplaces_52 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_52_startdate_idx ON carplaces_52 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_52_enddate_idx ON carplaces_52 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_52_isactual_idx ON carplaces_52 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_52_isactive_idx ON carplaces_52 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_53 (CONSTRAINT carplaces_53_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_53_objectid_idx ON carplaces_53 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_53_startdate_idx ON carplaces_53 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_53_enddate_idx ON carplaces_53 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_53_isactual_idx ON carplaces_53 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_53_isactive_idx ON carplaces_53 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_54 (CONSTRAINT carplaces_54_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_54_objectid_idx ON carplaces_54 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_54_startdate_idx ON carplaces_54 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_54_enddate_idx ON carplaces_54 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_54_isactual_idx ON carplaces_54 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_54_isactive_idx ON carplaces_54 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_55 (CONSTRAINT carplaces_55_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_55_objectid_idx ON carplaces_55 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_55_startdate_idx ON carplaces_55 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_55_enddate_idx ON carplaces_55 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_55_isactual_idx ON carplaces_55 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_55_isactive_idx ON carplaces_55 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_56 (CONSTRAINT carplaces_56_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_56_objectid_idx ON carplaces_56 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_56_startdate_idx ON carplaces_56 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_56_enddate_idx ON carplaces_56 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_56_isactual_idx ON carplaces_56 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_56_isactive_idx ON carplaces_56 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_57 (CONSTRAINT carplaces_57_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_57_objectid_idx ON carplaces_57 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_57_startdate_idx ON carplaces_57 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_57_enddate_idx ON carplaces_57 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_57_isactual_idx ON carplaces_57 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_57_isactive_idx ON carplaces_57 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_58 (CONSTRAINT carplaces_58_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_58_objectid_idx ON carplaces_58 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_58_startdate_idx ON carplaces_58 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_58_enddate_idx ON carplaces_58 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_58_isactual_idx ON carplaces_58 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_58_isactive_idx ON carplaces_58 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_59 (CONSTRAINT carplaces_59_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_59_objectid_idx ON carplaces_59 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_59_startdate_idx ON carplaces_59 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_59_enddate_idx ON carplaces_59 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_59_isactual_idx ON carplaces_59 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_59_isactive_idx ON carplaces_59 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_60 (CONSTRAINT carplaces_60_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_60_objectid_idx ON carplaces_60 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_60_startdate_idx ON carplaces_60 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_60_enddate_idx ON carplaces_60 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_60_isactual_idx ON carplaces_60 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_60_isactive_idx ON carplaces_60 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_61 (CONSTRAINT carplaces_61_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_61_objectid_idx ON carplaces_61 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_61_startdate_idx ON carplaces_61 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_61_enddate_idx ON carplaces_61 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_61_isactual_idx ON carplaces_61 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_61_isactive_idx ON carplaces_61 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_62 (CONSTRAINT carplaces_62_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_62_objectid_idx ON carplaces_62 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_62_startdate_idx ON carplaces_62 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_62_enddate_idx ON carplaces_62 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_62_isactual_idx ON carplaces_62 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_62_isactive_idx ON carplaces_62 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_63 (CONSTRAINT carplaces_63_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_63_objectid_idx ON carplaces_63 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_63_startdate_idx ON carplaces_63 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_63_enddate_idx ON carplaces_63 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_63_isactual_idx ON carplaces_63 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_63_isactive_idx ON carplaces_63 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_64 (CONSTRAINT carplaces_64_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_64_objectid_idx ON carplaces_64 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_64_startdate_idx ON carplaces_64 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_64_enddate_idx ON carplaces_64 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_64_isactual_idx ON carplaces_64 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_64_isactive_idx ON carplaces_64 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_65 (CONSTRAINT carplaces_65_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_65_objectid_idx ON carplaces_65 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_65_startdate_idx ON carplaces_65 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_65_enddate_idx ON carplaces_65 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_65_isactual_idx ON carplaces_65 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_65_isactive_idx ON carplaces_65 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_66 (CONSTRAINT carplaces_66_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_66_objectid_idx ON carplaces_66 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_66_startdate_idx ON carplaces_66 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_66_enddate_idx ON carplaces_66 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_66_isactual_idx ON carplaces_66 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_66_isactive_idx ON carplaces_66 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_67 (CONSTRAINT carplaces_67_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_67_objectid_idx ON carplaces_67 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_67_startdate_idx ON carplaces_67 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_67_enddate_idx ON carplaces_67 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_67_isactual_idx ON carplaces_67 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_67_isactive_idx ON carplaces_67 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_68 (CONSTRAINT carplaces_68_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_68_objectid_idx ON carplaces_68 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_68_startdate_idx ON carplaces_68 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_68_enddate_idx ON carplaces_68 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_68_isactual_idx ON carplaces_68 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_68_isactive_idx ON carplaces_68 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_69 (CONSTRAINT carplaces_69_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_69_objectid_idx ON carplaces_69 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_69_startdate_idx ON carplaces_69 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_69_enddate_idx ON carplaces_69 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_69_isactual_idx ON carplaces_69 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_69_isactive_idx ON carplaces_69 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_70 (CONSTRAINT carplaces_70_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_70_objectid_idx ON carplaces_70 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_70_startdate_idx ON carplaces_70 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_70_enddate_idx ON carplaces_70 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_70_isactual_idx ON carplaces_70 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_70_isactive_idx ON carplaces_70 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_71 (CONSTRAINT carplaces_71_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_71_objectid_idx ON carplaces_71 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_71_startdate_idx ON carplaces_71 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_71_enddate_idx ON carplaces_71 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_71_isactual_idx ON carplaces_71 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_71_isactive_idx ON carplaces_71 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_72 (CONSTRAINT carplaces_72_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_72_objectid_idx ON carplaces_72 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_72_startdate_idx ON carplaces_72 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_72_enddate_idx ON carplaces_72 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_72_isactual_idx ON carplaces_72 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_72_isactive_idx ON carplaces_72 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_73 (CONSTRAINT carplaces_73_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_73_objectid_idx ON carplaces_73 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_73_startdate_idx ON carplaces_73 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_73_enddate_idx ON carplaces_73 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_73_isactual_idx ON carplaces_73 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_73_isactive_idx ON carplaces_73 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_74 (CONSTRAINT carplaces_74_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_74_objectid_idx ON carplaces_74 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_74_startdate_idx ON carplaces_74 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_74_enddate_idx ON carplaces_74 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_74_isactual_idx ON carplaces_74 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_74_isactive_idx ON carplaces_74 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_75 (CONSTRAINT carplaces_75_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_75_objectid_idx ON carplaces_75 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_75_startdate_idx ON carplaces_75 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_75_enddate_idx ON carplaces_75 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_75_isactual_idx ON carplaces_75 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_75_isactive_idx ON carplaces_75 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_76 (CONSTRAINT carplaces_76_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_76_objectid_idx ON carplaces_76 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_76_startdate_idx ON carplaces_76 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_76_enddate_idx ON carplaces_76 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_76_isactual_idx ON carplaces_76 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_76_isactive_idx ON carplaces_76 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_77 (CONSTRAINT carplaces_77_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_77_objectid_idx ON carplaces_77 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_77_startdate_idx ON carplaces_77 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_77_enddate_idx ON carplaces_77 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_77_isactual_idx ON carplaces_77 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_77_isactive_idx ON carplaces_77 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_78 (CONSTRAINT carplaces_78_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_78_objectid_idx ON carplaces_78 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_78_startdate_idx ON carplaces_78 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_78_enddate_idx ON carplaces_78 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_78_isactual_idx ON carplaces_78 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_78_isactive_idx ON carplaces_78 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_79 (CONSTRAINT carplaces_79_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_79_objectid_idx ON carplaces_79 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_79_startdate_idx ON carplaces_79 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_79_enddate_idx ON carplaces_79 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_79_isactual_idx ON carplaces_79 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_79_isactive_idx ON carplaces_79 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_80 (CONSTRAINT carplaces_80_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_80_objectid_idx ON carplaces_80 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_80_startdate_idx ON carplaces_80 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_80_enddate_idx ON carplaces_80 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_80_isactual_idx ON carplaces_80 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_80_isactive_idx ON carplaces_80 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_81 (CONSTRAINT carplaces_81_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_81_objectid_idx ON carplaces_81 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_81_startdate_idx ON carplaces_81 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_81_enddate_idx ON carplaces_81 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_81_isactual_idx ON carplaces_81 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_81_isactive_idx ON carplaces_81 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_82 (CONSTRAINT carplaces_82_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_82_objectid_idx ON carplaces_82 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_82_startdate_idx ON carplaces_82 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_82_enddate_idx ON carplaces_82 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_82_isactual_idx ON carplaces_82 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_82_isactive_idx ON carplaces_82 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_83 (CONSTRAINT carplaces_83_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_83_objectid_idx ON carplaces_83 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_83_startdate_idx ON carplaces_83 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_83_enddate_idx ON carplaces_83 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_83_isactual_idx ON carplaces_83 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_83_isactive_idx ON carplaces_83 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_84 (CONSTRAINT carplaces_84_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_84_objectid_idx ON carplaces_84 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_84_startdate_idx ON carplaces_84 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_84_enddate_idx ON carplaces_84 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_84_isactual_idx ON carplaces_84 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_84_isactive_idx ON carplaces_84 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_85 (CONSTRAINT carplaces_85_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_85_objectid_idx ON carplaces_85 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_85_startdate_idx ON carplaces_85 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_85_enddate_idx ON carplaces_85 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_85_isactual_idx ON carplaces_85 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_85_isactive_idx ON carplaces_85 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_86 (CONSTRAINT carplaces_86_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_86_objectid_idx ON carplaces_86 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_86_startdate_idx ON carplaces_86 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_86_enddate_idx ON carplaces_86 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_86_isactual_idx ON carplaces_86 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_86_isactive_idx ON carplaces_86 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_87 (CONSTRAINT carplaces_87_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_87_objectid_idx ON carplaces_87 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_87_startdate_idx ON carplaces_87 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_87_enddate_idx ON carplaces_87 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_87_isactual_idx ON carplaces_87 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_87_isactive_idx ON carplaces_87 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_88 (CONSTRAINT carplaces_88_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_88_objectid_idx ON carplaces_88 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_88_startdate_idx ON carplaces_88 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_88_enddate_idx ON carplaces_88 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_88_isactual_idx ON carplaces_88 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_88_isactive_idx ON carplaces_88 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_89 (CONSTRAINT carplaces_89_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_89_objectid_idx ON carplaces_89 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_89_startdate_idx ON carplaces_89 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_89_enddate_idx ON carplaces_89 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_89_isactual_idx ON carplaces_89 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_89_isactive_idx ON carplaces_89 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_90 (CONSTRAINT carplaces_90_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_90_objectid_idx ON carplaces_90 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_90_startdate_idx ON carplaces_90 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_90_enddate_idx ON carplaces_90 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_90_isactual_idx ON carplaces_90 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_90_isactive_idx ON carplaces_90 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_91 (CONSTRAINT carplaces_91_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_91_objectid_idx ON carplaces_91 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_91_startdate_idx ON carplaces_91 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_91_enddate_idx ON carplaces_91 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_91_isactual_idx ON carplaces_91 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_91_isactive_idx ON carplaces_91 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_92 (CONSTRAINT carplaces_92_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_92_objectid_idx ON carplaces_92 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_92_startdate_idx ON carplaces_92 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_92_enddate_idx ON carplaces_92 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_92_isactual_idx ON carplaces_92 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_92_isactive_idx ON carplaces_92 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_93 (CONSTRAINT carplaces_93_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_93_objectid_idx ON carplaces_93 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_93_startdate_idx ON carplaces_93 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_93_enddate_idx ON carplaces_93 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_93_isactual_idx ON carplaces_93 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_93_isactive_idx ON carplaces_93 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_94 (CONSTRAINT carplaces_94_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_94_objectid_idx ON carplaces_94 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_94_startdate_idx ON carplaces_94 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_94_enddate_idx ON carplaces_94 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_94_isactual_idx ON carplaces_94 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_94_isactive_idx ON carplaces_94 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_95 (CONSTRAINT carplaces_95_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_95_objectid_idx ON carplaces_95 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_95_startdate_idx ON carplaces_95 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_95_enddate_idx ON carplaces_95 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_95_isactual_idx ON carplaces_95 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_95_isactive_idx ON carplaces_95 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_96 (CONSTRAINT carplaces_96_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_96_objectid_idx ON carplaces_96 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_96_startdate_idx ON carplaces_96 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_96_enddate_idx ON carplaces_96 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_96_isactual_idx ON carplaces_96 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_96_isactive_idx ON carplaces_96 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_97 (CONSTRAINT carplaces_97_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_97_objectid_idx ON carplaces_97 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_97_startdate_idx ON carplaces_97 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_97_enddate_idx ON carplaces_97 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_97_isactual_idx ON carplaces_97 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_97_isactive_idx ON carplaces_97 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_98 (CONSTRAINT carplaces_98_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_98_objectid_idx ON carplaces_98 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_98_startdate_idx ON carplaces_98 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_98_enddate_idx ON carplaces_98 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_98_isactual_idx ON carplaces_98 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_98_isactive_idx ON carplaces_98 USING btree (isactive);
CREATE TABLE IF NOT EXISTS carplaces_99 (CONSTRAINT carplaces_99_pkey PRIMARY KEY (id)) INHERITS (carplaces);
CREATE INDEX IF NOT EXISTS carplaces_99_objectid_idx ON carplaces_99 USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_99_startdate_idx ON carplaces_99 USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_99_enddate_idx ON carplaces_99 USING btree (enddate);
CREATE INDEX IF NOT EXISTS carplaces_99_isactual_idx ON carplaces_99 USING btree (isactual);
CREATE INDEX IF NOT EXISTS carplaces_99_isactive_idx ON carplaces_99 USING btree (isactive);
