CREATE TABLE carplaces_params (
    param param_type NOT NULL DEFAULT 'carplaces',
    CONSTRAINT carplaces_params_pkey PRIMARY KEY (id),
    CONSTRAINT carplaces_params_param_check CHECK (param = 'carplaces')
) INHERITS (param);
COMMENT ON TABLE carplaces_params IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN carplaces_params.id IS 'Идентификатор записи';
COMMENT ON COLUMN carplaces_params.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN carplaces_params.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN carplaces_params.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN carplaces_params.typeid IS 'Тип параметра';
COMMENT ON COLUMN carplaces_params.value IS 'Значение параметра';
COMMENT ON COLUMN carplaces_params.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN carplaces_params.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN carplaces_params.enddate IS 'Дата окончания действия записи';

CREATE TABLE carplaces_params_01 (dir SMALLINT NOT NULL DEFAULT 01, CONSTRAINT carplaces_params_dir_check CHECK (dir = 01)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_02 (dir SMALLINT NOT NULL DEFAULT 02, CONSTRAINT carplaces_params_dir_check CHECK (dir = 02)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_03 (dir SMALLINT NOT NULL DEFAULT 03, CONSTRAINT carplaces_params_dir_check CHECK (dir = 03)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_04 (dir SMALLINT NOT NULL DEFAULT 04, CONSTRAINT carplaces_params_dir_check CHECK (dir = 04)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_05 (dir SMALLINT NOT NULL DEFAULT 05, CONSTRAINT carplaces_params_dir_check CHECK (dir = 05)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_06 (dir SMALLINT NOT NULL DEFAULT 06, CONSTRAINT carplaces_params_dir_check CHECK (dir = 06)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_07 (dir SMALLINT NOT NULL DEFAULT 07, CONSTRAINT carplaces_params_dir_check CHECK (dir = 07)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_08 (dir SMALLINT NOT NULL DEFAULT 08, CONSTRAINT carplaces_params_dir_check CHECK (dir = 08)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_09 (dir SMALLINT NOT NULL DEFAULT 09, CONSTRAINT carplaces_params_dir_check CHECK (dir = 09)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_10 (dir SMALLINT NOT NULL DEFAULT 10, CONSTRAINT carplaces_params_dir_check CHECK (dir = 10)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_11 (dir SMALLINT NOT NULL DEFAULT 11, CONSTRAINT carplaces_params_dir_check CHECK (dir = 11)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_12 (dir SMALLINT NOT NULL DEFAULT 12, CONSTRAINT carplaces_params_dir_check CHECK (dir = 12)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_13 (dir SMALLINT NOT NULL DEFAULT 13, CONSTRAINT carplaces_params_dir_check CHECK (dir = 13)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_14 (dir SMALLINT NOT NULL DEFAULT 14, CONSTRAINT carplaces_params_dir_check CHECK (dir = 14)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_15 (dir SMALLINT NOT NULL DEFAULT 15, CONSTRAINT carplaces_params_dir_check CHECK (dir = 15)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_16 (dir SMALLINT NOT NULL DEFAULT 16, CONSTRAINT carplaces_params_dir_check CHECK (dir = 16)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_17 (dir SMALLINT NOT NULL DEFAULT 17, CONSTRAINT carplaces_params_dir_check CHECK (dir = 17)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_18 (dir SMALLINT NOT NULL DEFAULT 18, CONSTRAINT carplaces_params_dir_check CHECK (dir = 18)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_19 (dir SMALLINT NOT NULL DEFAULT 19, CONSTRAINT carplaces_params_dir_check CHECK (dir = 19)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_20 (dir SMALLINT NOT NULL DEFAULT 20, CONSTRAINT carplaces_params_dir_check CHECK (dir = 20)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_21 (dir SMALLINT NOT NULL DEFAULT 21, CONSTRAINT carplaces_params_dir_check CHECK (dir = 21)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_22 (dir SMALLINT NOT NULL DEFAULT 22, CONSTRAINT carplaces_params_dir_check CHECK (dir = 22)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_23 (dir SMALLINT NOT NULL DEFAULT 23, CONSTRAINT carplaces_params_dir_check CHECK (dir = 23)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_24 (dir SMALLINT NOT NULL DEFAULT 24, CONSTRAINT carplaces_params_dir_check CHECK (dir = 24)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_25 (dir SMALLINT NOT NULL DEFAULT 25, CONSTRAINT carplaces_params_dir_check CHECK (dir = 25)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_26 (dir SMALLINT NOT NULL DEFAULT 26, CONSTRAINT carplaces_params_dir_check CHECK (dir = 26)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_27 (dir SMALLINT NOT NULL DEFAULT 27, CONSTRAINT carplaces_params_dir_check CHECK (dir = 27)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_28 (dir SMALLINT NOT NULL DEFAULT 28, CONSTRAINT carplaces_params_dir_check CHECK (dir = 28)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_29 (dir SMALLINT NOT NULL DEFAULT 29, CONSTRAINT carplaces_params_dir_check CHECK (dir = 29)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_30 (dir SMALLINT NOT NULL DEFAULT 30, CONSTRAINT carplaces_params_dir_check CHECK (dir = 30)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_31 (dir SMALLINT NOT NULL DEFAULT 31, CONSTRAINT carplaces_params_dir_check CHECK (dir = 31)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_32 (dir SMALLINT NOT NULL DEFAULT 32, CONSTRAINT carplaces_params_dir_check CHECK (dir = 32)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_33 (dir SMALLINT NOT NULL DEFAULT 33, CONSTRAINT carplaces_params_dir_check CHECK (dir = 33)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_34 (dir SMALLINT NOT NULL DEFAULT 34, CONSTRAINT carplaces_params_dir_check CHECK (dir = 34)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_35 (dir SMALLINT NOT NULL DEFAULT 35, CONSTRAINT carplaces_params_dir_check CHECK (dir = 35)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_36 (dir SMALLINT NOT NULL DEFAULT 36, CONSTRAINT carplaces_params_dir_check CHECK (dir = 36)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_37 (dir SMALLINT NOT NULL DEFAULT 37, CONSTRAINT carplaces_params_dir_check CHECK (dir = 37)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_38 (dir SMALLINT NOT NULL DEFAULT 38, CONSTRAINT carplaces_params_dir_check CHECK (dir = 38)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_39 (dir SMALLINT NOT NULL DEFAULT 39, CONSTRAINT carplaces_params_dir_check CHECK (dir = 39)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_40 (dir SMALLINT NOT NULL DEFAULT 40, CONSTRAINT carplaces_params_dir_check CHECK (dir = 40)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_41 (dir SMALLINT NOT NULL DEFAULT 41, CONSTRAINT carplaces_params_dir_check CHECK (dir = 41)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_42 (dir SMALLINT NOT NULL DEFAULT 42, CONSTRAINT carplaces_params_dir_check CHECK (dir = 42)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_43 (dir SMALLINT NOT NULL DEFAULT 43, CONSTRAINT carplaces_params_dir_check CHECK (dir = 43)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_44 (dir SMALLINT NOT NULL DEFAULT 44, CONSTRAINT carplaces_params_dir_check CHECK (dir = 44)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_45 (dir SMALLINT NOT NULL DEFAULT 45, CONSTRAINT carplaces_params_dir_check CHECK (dir = 45)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_46 (dir SMALLINT NOT NULL DEFAULT 46, CONSTRAINT carplaces_params_dir_check CHECK (dir = 46)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_47 (dir SMALLINT NOT NULL DEFAULT 47, CONSTRAINT carplaces_params_dir_check CHECK (dir = 47)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_48 (dir SMALLINT NOT NULL DEFAULT 48, CONSTRAINT carplaces_params_dir_check CHECK (dir = 48)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_49 (dir SMALLINT NOT NULL DEFAULT 49, CONSTRAINT carplaces_params_dir_check CHECK (dir = 49)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_50 (dir SMALLINT NOT NULL DEFAULT 50, CONSTRAINT carplaces_params_dir_check CHECK (dir = 50)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_51 (dir SMALLINT NOT NULL DEFAULT 51, CONSTRAINT carplaces_params_dir_check CHECK (dir = 51)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_52 (dir SMALLINT NOT NULL DEFAULT 52, CONSTRAINT carplaces_params_dir_check CHECK (dir = 52)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_53 (dir SMALLINT NOT NULL DEFAULT 53, CONSTRAINT carplaces_params_dir_check CHECK (dir = 53)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_54 (dir SMALLINT NOT NULL DEFAULT 54, CONSTRAINT carplaces_params_dir_check CHECK (dir = 54)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_55 (dir SMALLINT NOT NULL DEFAULT 55, CONSTRAINT carplaces_params_dir_check CHECK (dir = 55)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_56 (dir SMALLINT NOT NULL DEFAULT 56, CONSTRAINT carplaces_params_dir_check CHECK (dir = 56)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_57 (dir SMALLINT NOT NULL DEFAULT 57, CONSTRAINT carplaces_params_dir_check CHECK (dir = 57)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_58 (dir SMALLINT NOT NULL DEFAULT 58, CONSTRAINT carplaces_params_dir_check CHECK (dir = 58)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_59 (dir SMALLINT NOT NULL DEFAULT 59, CONSTRAINT carplaces_params_dir_check CHECK (dir = 59)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_60 (dir SMALLINT NOT NULL DEFAULT 60, CONSTRAINT carplaces_params_dir_check CHECK (dir = 60)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_61 (dir SMALLINT NOT NULL DEFAULT 61, CONSTRAINT carplaces_params_dir_check CHECK (dir = 61)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_62 (dir SMALLINT NOT NULL DEFAULT 62, CONSTRAINT carplaces_params_dir_check CHECK (dir = 62)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_63 (dir SMALLINT NOT NULL DEFAULT 63, CONSTRAINT carplaces_params_dir_check CHECK (dir = 63)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_64 (dir SMALLINT NOT NULL DEFAULT 64, CONSTRAINT carplaces_params_dir_check CHECK (dir = 64)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_65 (dir SMALLINT NOT NULL DEFAULT 65, CONSTRAINT carplaces_params_dir_check CHECK (dir = 65)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_66 (dir SMALLINT NOT NULL DEFAULT 66, CONSTRAINT carplaces_params_dir_check CHECK (dir = 66)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_67 (dir SMALLINT NOT NULL DEFAULT 67, CONSTRAINT carplaces_params_dir_check CHECK (dir = 67)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_68 (dir SMALLINT NOT NULL DEFAULT 68, CONSTRAINT carplaces_params_dir_check CHECK (dir = 68)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_69 (dir SMALLINT NOT NULL DEFAULT 69, CONSTRAINT carplaces_params_dir_check CHECK (dir = 69)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_70 (dir SMALLINT NOT NULL DEFAULT 70, CONSTRAINT carplaces_params_dir_check CHECK (dir = 70)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_71 (dir SMALLINT NOT NULL DEFAULT 71, CONSTRAINT carplaces_params_dir_check CHECK (dir = 71)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_72 (dir SMALLINT NOT NULL DEFAULT 72, CONSTRAINT carplaces_params_dir_check CHECK (dir = 72)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_73 (dir SMALLINT NOT NULL DEFAULT 73, CONSTRAINT carplaces_params_dir_check CHECK (dir = 73)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_74 (dir SMALLINT NOT NULL DEFAULT 74, CONSTRAINT carplaces_params_dir_check CHECK (dir = 74)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_75 (dir SMALLINT NOT NULL DEFAULT 75, CONSTRAINT carplaces_params_dir_check CHECK (dir = 75)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_76 (dir SMALLINT NOT NULL DEFAULT 76, CONSTRAINT carplaces_params_dir_check CHECK (dir = 76)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_77 (dir SMALLINT NOT NULL DEFAULT 77, CONSTRAINT carplaces_params_dir_check CHECK (dir = 77)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_78 (dir SMALLINT NOT NULL DEFAULT 78, CONSTRAINT carplaces_params_dir_check CHECK (dir = 78)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_79 (dir SMALLINT NOT NULL DEFAULT 79, CONSTRAINT carplaces_params_dir_check CHECK (dir = 79)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_80 (dir SMALLINT NOT NULL DEFAULT 80, CONSTRAINT carplaces_params_dir_check CHECK (dir = 80)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_81 (dir SMALLINT NOT NULL DEFAULT 81, CONSTRAINT carplaces_params_dir_check CHECK (dir = 81)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_82 (dir SMALLINT NOT NULL DEFAULT 82, CONSTRAINT carplaces_params_dir_check CHECK (dir = 82)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_83 (dir SMALLINT NOT NULL DEFAULT 83, CONSTRAINT carplaces_params_dir_check CHECK (dir = 83)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_84 (dir SMALLINT NOT NULL DEFAULT 84, CONSTRAINT carplaces_params_dir_check CHECK (dir = 84)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_85 (dir SMALLINT NOT NULL DEFAULT 85, CONSTRAINT carplaces_params_dir_check CHECK (dir = 85)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_86 (dir SMALLINT NOT NULL DEFAULT 86, CONSTRAINT carplaces_params_dir_check CHECK (dir = 86)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_87 (dir SMALLINT NOT NULL DEFAULT 87, CONSTRAINT carplaces_params_dir_check CHECK (dir = 87)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_88 (dir SMALLINT NOT NULL DEFAULT 88, CONSTRAINT carplaces_params_dir_check CHECK (dir = 88)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_89 (dir SMALLINT NOT NULL DEFAULT 89, CONSTRAINT carplaces_params_dir_check CHECK (dir = 89)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_90 (dir SMALLINT NOT NULL DEFAULT 90, CONSTRAINT carplaces_params_dir_check CHECK (dir = 90)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_91 (dir SMALLINT NOT NULL DEFAULT 91, CONSTRAINT carplaces_params_dir_check CHECK (dir = 91)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_92 (dir SMALLINT NOT NULL DEFAULT 92, CONSTRAINT carplaces_params_dir_check CHECK (dir = 92)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_93 (dir SMALLINT NOT NULL DEFAULT 93, CONSTRAINT carplaces_params_dir_check CHECK (dir = 93)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_94 (dir SMALLINT NOT NULL DEFAULT 94, CONSTRAINT carplaces_params_dir_check CHECK (dir = 94)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_95 (dir SMALLINT NOT NULL DEFAULT 95, CONSTRAINT carplaces_params_dir_check CHECK (dir = 95)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_96 (dir SMALLINT NOT NULL DEFAULT 96, CONSTRAINT carplaces_params_dir_check CHECK (dir = 96)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_97 (dir SMALLINT NOT NULL DEFAULT 97, CONSTRAINT carplaces_params_dir_check CHECK (dir = 97)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_98 (dir SMALLINT NOT NULL DEFAULT 98, CONSTRAINT carplaces_params_dir_check CHECK (dir = 98)) INHERITS (carplaces_params);
CREATE TABLE carplaces_params_99 (dir SMALLINT NOT NULL DEFAULT 99, CONSTRAINT carplaces_params_dir_check CHECK (dir = 99)) INHERITS (carplaces_params);
