CREATE TABLE IF NOT EXISTS houses (
  id BIGINT NOT NULL PRIMARY KEY,
  objectid BIGINT NOT NULL,
  objectguid UUID NOT NULL,
  changeid BIGINT NOT NULL,
  housenum VARCHAR(50),
  addnum1 VARCHAR(50),
  addnum2 VARCHAR(50),
  housetype INT,
  addtype1 INT,
  addtype2 INT,
  opertypeid INT NOT NULL,
  previd BIGINT,
  nextid BIGINT,
  updatedate DATE NOT NULL,
  startdate DATE NOT NULL,
  enddate DATE NOT NULL,
  isactual SMALLINT NOT NULL,
  isactive SMALLINT NOT NULL
);
COMMENT ON TABLE houses IS 'Сведения по номерам домов улиц городов и населенных пунктов';
COMMENT ON COLUMN houses.id IS 'Уникальный идентификатор записи. Ключевое поле';
COMMENT ON COLUMN houses.objectid IS 'Глобальный уникальный идентификатор объекта типа INTEGER';
COMMENT ON COLUMN houses.objectguid IS 'Глобальный уникальный идентификатор адресного объекта типа UUID';
COMMENT ON COLUMN houses.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN houses.housenum IS 'Основной номер дома';
COMMENT ON COLUMN houses.addnum1 IS 'Дополнительный номер дома 1';
COMMENT ON COLUMN houses.addnum2 IS 'Дополнительный номер дома 1';
COMMENT ON COLUMN houses.housetype IS 'Основной тип дома';
COMMENT ON COLUMN houses.addtype1 IS 'Дополнительный тип дома 1';
COMMENT ON COLUMN houses.addtype2 IS 'Дополнительный тип дома 2';
COMMENT ON COLUMN houses.opertypeid IS 'Статус действия над записью – причина появления записи';
COMMENT ON COLUMN houses.previd IS 'Идентификатор записи связывания с предыдущей исторической записью';
COMMENT ON COLUMN houses.nextid IS 'Идентификатор записи связывания с последующей исторической записью';
COMMENT ON COLUMN houses.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN houses.startdate IS 'Начало действия записи';
COMMENT ON COLUMN houses.enddate IS 'Окончание действия записи';
COMMENT ON COLUMN houses.isactual IS 'Статус актуальности адресного объекта ФИАС';
COMMENT ON COLUMN houses.isactive IS 'Признак действующего адресного объекта';
CREATE INDEX IF NOT EXISTS houses_objectid_idx ON houses USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_housetype_idx ON houses USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_startdate_idx ON houses USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_enddate_idx ON houses USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_isactual_idx ON houses USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_isactive_idx ON houses USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_01 (CONSTRAINT houses_01_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_01_objectid_idx ON houses_01 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_01_housetype_idx ON houses_01 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_01_startdate_idx ON houses_01 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_01_enddate_idx ON houses_01 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_01_isactual_idx ON houses_01 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_01_isactive_idx ON houses_01 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_02 (CONSTRAINT houses_02_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_02_objectid_idx ON houses_02 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_02_housetype_idx ON houses_02 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_02_startdate_idx ON houses_02 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_02_enddate_idx ON houses_02 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_02_isactual_idx ON houses_02 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_02_isactive_idx ON houses_02 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_03 (CONSTRAINT houses_03_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_03_objectid_idx ON houses_03 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_03_housetype_idx ON houses_03 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_03_startdate_idx ON houses_03 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_03_enddate_idx ON houses_03 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_03_isactual_idx ON houses_03 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_03_isactive_idx ON houses_03 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_04 (CONSTRAINT houses_04_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_04_objectid_idx ON houses_04 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_04_housetype_idx ON houses_04 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_04_startdate_idx ON houses_04 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_04_enddate_idx ON houses_04 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_04_isactual_idx ON houses_04 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_04_isactive_idx ON houses_04 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_05 (CONSTRAINT houses_05_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_05_objectid_idx ON houses_05 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_05_housetype_idx ON houses_05 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_05_startdate_idx ON houses_05 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_05_enddate_idx ON houses_05 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_05_isactual_idx ON houses_05 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_05_isactive_idx ON houses_05 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_06 (CONSTRAINT houses_06_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_06_objectid_idx ON houses_06 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_06_housetype_idx ON houses_06 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_06_startdate_idx ON houses_06 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_06_enddate_idx ON houses_06 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_06_isactual_idx ON houses_06 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_06_isactive_idx ON houses_06 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_07 (CONSTRAINT houses_07_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_07_objectid_idx ON houses_07 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_07_housetype_idx ON houses_07 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_07_startdate_idx ON houses_07 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_07_enddate_idx ON houses_07 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_07_isactual_idx ON houses_07 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_07_isactive_idx ON houses_07 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_08 (CONSTRAINT houses_08_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_08_objectid_idx ON houses_08 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_08_housetype_idx ON houses_08 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_08_startdate_idx ON houses_08 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_08_enddate_idx ON houses_08 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_08_isactual_idx ON houses_08 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_08_isactive_idx ON houses_08 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_09 (CONSTRAINT houses_09_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_09_objectid_idx ON houses_09 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_09_housetype_idx ON houses_09 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_09_startdate_idx ON houses_09 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_09_enddate_idx ON houses_09 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_09_isactual_idx ON houses_09 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_09_isactive_idx ON houses_09 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_10 (CONSTRAINT houses_10_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_10_objectid_idx ON houses_10 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_10_housetype_idx ON houses_10 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_10_startdate_idx ON houses_10 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_10_enddate_idx ON houses_10 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_10_isactual_idx ON houses_10 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_10_isactive_idx ON houses_10 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_11 (CONSTRAINT houses_11_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_11_objectid_idx ON houses_11 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_11_housetype_idx ON houses_11 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_11_startdate_idx ON houses_11 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_11_enddate_idx ON houses_11 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_11_isactual_idx ON houses_11 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_11_isactive_idx ON houses_11 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_12 (CONSTRAINT houses_12_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_12_objectid_idx ON houses_12 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_12_housetype_idx ON houses_12 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_12_startdate_idx ON houses_12 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_12_enddate_idx ON houses_12 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_12_isactual_idx ON houses_12 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_12_isactive_idx ON houses_12 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_13 (CONSTRAINT houses_13_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_13_objectid_idx ON houses_13 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_13_housetype_idx ON houses_13 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_13_startdate_idx ON houses_13 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_13_enddate_idx ON houses_13 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_13_isactual_idx ON houses_13 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_13_isactive_idx ON houses_13 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_14 (CONSTRAINT houses_14_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_14_objectid_idx ON houses_14 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_14_housetype_idx ON houses_14 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_14_startdate_idx ON houses_14 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_14_enddate_idx ON houses_14 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_14_isactual_idx ON houses_14 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_14_isactive_idx ON houses_14 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_15 (CONSTRAINT houses_15_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_15_objectid_idx ON houses_15 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_15_housetype_idx ON houses_15 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_15_startdate_idx ON houses_15 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_15_enddate_idx ON houses_15 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_15_isactual_idx ON houses_15 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_15_isactive_idx ON houses_15 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_16 (CONSTRAINT houses_16_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_16_objectid_idx ON houses_16 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_16_housetype_idx ON houses_16 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_16_startdate_idx ON houses_16 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_16_enddate_idx ON houses_16 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_16_isactual_idx ON houses_16 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_16_isactive_idx ON houses_16 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_17 (CONSTRAINT houses_17_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_17_objectid_idx ON houses_17 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_17_housetype_idx ON houses_17 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_17_startdate_idx ON houses_17 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_17_enddate_idx ON houses_17 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_17_isactual_idx ON houses_17 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_17_isactive_idx ON houses_17 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_18 (CONSTRAINT houses_18_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_18_objectid_idx ON houses_18 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_18_housetype_idx ON houses_18 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_18_startdate_idx ON houses_18 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_18_enddate_idx ON houses_18 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_18_isactual_idx ON houses_18 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_18_isactive_idx ON houses_18 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_19 (CONSTRAINT houses_19_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_19_objectid_idx ON houses_19 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_19_housetype_idx ON houses_19 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_19_startdate_idx ON houses_19 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_19_enddate_idx ON houses_19 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_19_isactual_idx ON houses_19 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_19_isactive_idx ON houses_19 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_20 (CONSTRAINT houses_20_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_20_objectid_idx ON houses_20 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_20_housetype_idx ON houses_20 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_20_startdate_idx ON houses_20 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_20_enddate_idx ON houses_20 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_20_isactual_idx ON houses_20 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_20_isactive_idx ON houses_20 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_21 (CONSTRAINT houses_21_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_21_objectid_idx ON houses_21 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_21_housetype_idx ON houses_21 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_21_startdate_idx ON houses_21 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_21_enddate_idx ON houses_21 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_21_isactual_idx ON houses_21 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_21_isactive_idx ON houses_21 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_22 (CONSTRAINT houses_22_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_22_objectid_idx ON houses_22 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_22_housetype_idx ON houses_22 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_22_startdate_idx ON houses_22 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_22_enddate_idx ON houses_22 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_22_isactual_idx ON houses_22 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_22_isactive_idx ON houses_22 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_23 (CONSTRAINT houses_23_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_23_objectid_idx ON houses_23 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_23_housetype_idx ON houses_23 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_23_startdate_idx ON houses_23 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_23_enddate_idx ON houses_23 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_23_isactual_idx ON houses_23 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_23_isactive_idx ON houses_23 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_24 (CONSTRAINT houses_24_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_24_objectid_idx ON houses_24 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_24_housetype_idx ON houses_24 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_24_startdate_idx ON houses_24 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_24_enddate_idx ON houses_24 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_24_isactual_idx ON houses_24 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_24_isactive_idx ON houses_24 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_25 (CONSTRAINT houses_25_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_25_objectid_idx ON houses_25 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_25_housetype_idx ON houses_25 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_25_startdate_idx ON houses_25 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_25_enddate_idx ON houses_25 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_25_isactual_idx ON houses_25 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_25_isactive_idx ON houses_25 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_26 (CONSTRAINT houses_26_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_26_objectid_idx ON houses_26 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_26_housetype_idx ON houses_26 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_26_startdate_idx ON houses_26 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_26_enddate_idx ON houses_26 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_26_isactual_idx ON houses_26 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_26_isactive_idx ON houses_26 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_27 (CONSTRAINT houses_27_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_27_objectid_idx ON houses_27 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_27_housetype_idx ON houses_27 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_27_startdate_idx ON houses_27 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_27_enddate_idx ON houses_27 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_27_isactual_idx ON houses_27 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_27_isactive_idx ON houses_27 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_28 (CONSTRAINT houses_28_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_28_objectid_idx ON houses_28 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_28_housetype_idx ON houses_28 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_28_startdate_idx ON houses_28 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_28_enddate_idx ON houses_28 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_28_isactual_idx ON houses_28 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_28_isactive_idx ON houses_28 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_29 (CONSTRAINT houses_29_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_29_objectid_idx ON houses_29 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_29_housetype_idx ON houses_29 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_29_startdate_idx ON houses_29 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_29_enddate_idx ON houses_29 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_29_isactual_idx ON houses_29 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_29_isactive_idx ON houses_29 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_30 (CONSTRAINT houses_30_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_30_objectid_idx ON houses_30 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_30_housetype_idx ON houses_30 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_30_startdate_idx ON houses_30 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_30_enddate_idx ON houses_30 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_30_isactual_idx ON houses_30 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_30_isactive_idx ON houses_30 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_31 (CONSTRAINT houses_31_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_31_objectid_idx ON houses_31 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_31_housetype_idx ON houses_31 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_31_startdate_idx ON houses_31 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_31_enddate_idx ON houses_31 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_31_isactual_idx ON houses_31 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_31_isactive_idx ON houses_31 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_32 (CONSTRAINT houses_32_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_32_objectid_idx ON houses_32 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_32_housetype_idx ON houses_32 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_32_startdate_idx ON houses_32 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_32_enddate_idx ON houses_32 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_32_isactual_idx ON houses_32 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_32_isactive_idx ON houses_32 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_33 (CONSTRAINT houses_33_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_33_objectid_idx ON houses_33 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_33_housetype_idx ON houses_33 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_33_startdate_idx ON houses_33 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_33_enddate_idx ON houses_33 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_33_isactual_idx ON houses_33 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_33_isactive_idx ON houses_33 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_34 (CONSTRAINT houses_34_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_34_objectid_idx ON houses_34 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_34_housetype_idx ON houses_34 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_34_startdate_idx ON houses_34 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_34_enddate_idx ON houses_34 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_34_isactual_idx ON houses_34 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_34_isactive_idx ON houses_34 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_35 (CONSTRAINT houses_35_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_35_objectid_idx ON houses_35 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_35_housetype_idx ON houses_35 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_35_startdate_idx ON houses_35 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_35_enddate_idx ON houses_35 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_35_isactual_idx ON houses_35 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_35_isactive_idx ON houses_35 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_36 (CONSTRAINT houses_36_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_36_objectid_idx ON houses_36 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_36_housetype_idx ON houses_36 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_36_startdate_idx ON houses_36 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_36_enddate_idx ON houses_36 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_36_isactual_idx ON houses_36 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_36_isactive_idx ON houses_36 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_37 (CONSTRAINT houses_37_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_37_objectid_idx ON houses_37 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_37_housetype_idx ON houses_37 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_37_startdate_idx ON houses_37 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_37_enddate_idx ON houses_37 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_37_isactual_idx ON houses_37 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_37_isactive_idx ON houses_37 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_38 (CONSTRAINT houses_38_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_38_objectid_idx ON houses_38 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_38_housetype_idx ON houses_38 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_38_startdate_idx ON houses_38 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_38_enddate_idx ON houses_38 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_38_isactual_idx ON houses_38 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_38_isactive_idx ON houses_38 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_39 (CONSTRAINT houses_39_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_39_objectid_idx ON houses_39 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_39_housetype_idx ON houses_39 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_39_startdate_idx ON houses_39 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_39_enddate_idx ON houses_39 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_39_isactual_idx ON houses_39 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_39_isactive_idx ON houses_39 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_40 (CONSTRAINT houses_40_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_40_objectid_idx ON houses_40 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_40_housetype_idx ON houses_40 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_40_startdate_idx ON houses_40 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_40_enddate_idx ON houses_40 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_40_isactual_idx ON houses_40 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_40_isactive_idx ON houses_40 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_41 (CONSTRAINT houses_41_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_41_objectid_idx ON houses_41 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_41_housetype_idx ON houses_41 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_41_startdate_idx ON houses_41 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_41_enddate_idx ON houses_41 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_41_isactual_idx ON houses_41 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_41_isactive_idx ON houses_41 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_42 (CONSTRAINT houses_42_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_42_objectid_idx ON houses_42 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_42_housetype_idx ON houses_42 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_42_startdate_idx ON houses_42 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_42_enddate_idx ON houses_42 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_42_isactual_idx ON houses_42 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_42_isactive_idx ON houses_42 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_43 (CONSTRAINT houses_43_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_43_objectid_idx ON houses_43 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_43_housetype_idx ON houses_43 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_43_startdate_idx ON houses_43 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_43_enddate_idx ON houses_43 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_43_isactual_idx ON houses_43 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_43_isactive_idx ON houses_43 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_44 (CONSTRAINT houses_44_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_44_objectid_idx ON houses_44 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_44_housetype_idx ON houses_44 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_44_startdate_idx ON houses_44 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_44_enddate_idx ON houses_44 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_44_isactual_idx ON houses_44 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_44_isactive_idx ON houses_44 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_45 (CONSTRAINT houses_45_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_45_objectid_idx ON houses_45 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_45_housetype_idx ON houses_45 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_45_startdate_idx ON houses_45 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_45_enddate_idx ON houses_45 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_45_isactual_idx ON houses_45 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_45_isactive_idx ON houses_45 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_46 (CONSTRAINT houses_46_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_46_objectid_idx ON houses_46 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_46_housetype_idx ON houses_46 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_46_startdate_idx ON houses_46 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_46_enddate_idx ON houses_46 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_46_isactual_idx ON houses_46 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_46_isactive_idx ON houses_46 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_47 (CONSTRAINT houses_47_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_47_objectid_idx ON houses_47 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_47_housetype_idx ON houses_47 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_47_startdate_idx ON houses_47 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_47_enddate_idx ON houses_47 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_47_isactual_idx ON houses_47 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_47_isactive_idx ON houses_47 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_48 (CONSTRAINT houses_48_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_48_objectid_idx ON houses_48 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_48_housetype_idx ON houses_48 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_48_startdate_idx ON houses_48 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_48_enddate_idx ON houses_48 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_48_isactual_idx ON houses_48 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_48_isactive_idx ON houses_48 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_49 (CONSTRAINT houses_49_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_49_objectid_idx ON houses_49 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_49_housetype_idx ON houses_49 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_49_startdate_idx ON houses_49 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_49_enddate_idx ON houses_49 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_49_isactual_idx ON houses_49 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_49_isactive_idx ON houses_49 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_50 (CONSTRAINT houses_50_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_50_objectid_idx ON houses_50 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_50_housetype_idx ON houses_50 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_50_startdate_idx ON houses_50 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_50_enddate_idx ON houses_50 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_50_isactual_idx ON houses_50 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_50_isactive_idx ON houses_50 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_51 (CONSTRAINT houses_51_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_51_objectid_idx ON houses_51 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_51_housetype_idx ON houses_51 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_51_startdate_idx ON houses_51 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_51_enddate_idx ON houses_51 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_51_isactual_idx ON houses_51 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_51_isactive_idx ON houses_51 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_52 (CONSTRAINT houses_52_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_52_objectid_idx ON houses_52 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_52_housetype_idx ON houses_52 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_52_startdate_idx ON houses_52 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_52_enddate_idx ON houses_52 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_52_isactual_idx ON houses_52 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_52_isactive_idx ON houses_52 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_53 (CONSTRAINT houses_53_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_53_objectid_idx ON houses_53 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_53_housetype_idx ON houses_53 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_53_startdate_idx ON houses_53 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_53_enddate_idx ON houses_53 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_53_isactual_idx ON houses_53 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_53_isactive_idx ON houses_53 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_54 (CONSTRAINT houses_54_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_54_objectid_idx ON houses_54 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_54_housetype_idx ON houses_54 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_54_startdate_idx ON houses_54 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_54_enddate_idx ON houses_54 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_54_isactual_idx ON houses_54 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_54_isactive_idx ON houses_54 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_55 (CONSTRAINT houses_55_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_55_objectid_idx ON houses_55 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_55_housetype_idx ON houses_55 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_55_startdate_idx ON houses_55 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_55_enddate_idx ON houses_55 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_55_isactual_idx ON houses_55 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_55_isactive_idx ON houses_55 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_56 (CONSTRAINT houses_56_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_56_objectid_idx ON houses_56 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_56_housetype_idx ON houses_56 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_56_startdate_idx ON houses_56 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_56_enddate_idx ON houses_56 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_56_isactual_idx ON houses_56 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_56_isactive_idx ON houses_56 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_57 (CONSTRAINT houses_57_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_57_objectid_idx ON houses_57 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_57_housetype_idx ON houses_57 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_57_startdate_idx ON houses_57 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_57_enddate_idx ON houses_57 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_57_isactual_idx ON houses_57 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_57_isactive_idx ON houses_57 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_58 (CONSTRAINT houses_58_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_58_objectid_idx ON houses_58 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_58_housetype_idx ON houses_58 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_58_startdate_idx ON houses_58 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_58_enddate_idx ON houses_58 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_58_isactual_idx ON houses_58 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_58_isactive_idx ON houses_58 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_59 (CONSTRAINT houses_59_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_59_objectid_idx ON houses_59 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_59_housetype_idx ON houses_59 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_59_startdate_idx ON houses_59 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_59_enddate_idx ON houses_59 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_59_isactual_idx ON houses_59 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_59_isactive_idx ON houses_59 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_60 (CONSTRAINT houses_60_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_60_objectid_idx ON houses_60 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_60_housetype_idx ON houses_60 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_60_startdate_idx ON houses_60 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_60_enddate_idx ON houses_60 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_60_isactual_idx ON houses_60 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_60_isactive_idx ON houses_60 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_61 (CONSTRAINT houses_61_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_61_objectid_idx ON houses_61 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_61_housetype_idx ON houses_61 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_61_startdate_idx ON houses_61 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_61_enddate_idx ON houses_61 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_61_isactual_idx ON houses_61 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_61_isactive_idx ON houses_61 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_62 (CONSTRAINT houses_62_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_62_objectid_idx ON houses_62 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_62_housetype_idx ON houses_62 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_62_startdate_idx ON houses_62 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_62_enddate_idx ON houses_62 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_62_isactual_idx ON houses_62 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_62_isactive_idx ON houses_62 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_63 (CONSTRAINT houses_63_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_63_objectid_idx ON houses_63 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_63_housetype_idx ON houses_63 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_63_startdate_idx ON houses_63 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_63_enddate_idx ON houses_63 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_63_isactual_idx ON houses_63 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_63_isactive_idx ON houses_63 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_64 (CONSTRAINT houses_64_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_64_objectid_idx ON houses_64 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_64_housetype_idx ON houses_64 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_64_startdate_idx ON houses_64 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_64_enddate_idx ON houses_64 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_64_isactual_idx ON houses_64 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_64_isactive_idx ON houses_64 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_65 (CONSTRAINT houses_65_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_65_objectid_idx ON houses_65 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_65_housetype_idx ON houses_65 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_65_startdate_idx ON houses_65 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_65_enddate_idx ON houses_65 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_65_isactual_idx ON houses_65 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_65_isactive_idx ON houses_65 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_66 (CONSTRAINT houses_66_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_66_objectid_idx ON houses_66 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_66_housetype_idx ON houses_66 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_66_startdate_idx ON houses_66 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_66_enddate_idx ON houses_66 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_66_isactual_idx ON houses_66 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_66_isactive_idx ON houses_66 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_67 (CONSTRAINT houses_67_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_67_objectid_idx ON houses_67 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_67_housetype_idx ON houses_67 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_67_startdate_idx ON houses_67 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_67_enddate_idx ON houses_67 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_67_isactual_idx ON houses_67 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_67_isactive_idx ON houses_67 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_68 (CONSTRAINT houses_68_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_68_objectid_idx ON houses_68 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_68_housetype_idx ON houses_68 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_68_startdate_idx ON houses_68 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_68_enddate_idx ON houses_68 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_68_isactual_idx ON houses_68 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_68_isactive_idx ON houses_68 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_69 (CONSTRAINT houses_69_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_69_objectid_idx ON houses_69 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_69_housetype_idx ON houses_69 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_69_startdate_idx ON houses_69 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_69_enddate_idx ON houses_69 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_69_isactual_idx ON houses_69 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_69_isactive_idx ON houses_69 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_70 (CONSTRAINT houses_70_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_70_objectid_idx ON houses_70 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_70_housetype_idx ON houses_70 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_70_startdate_idx ON houses_70 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_70_enddate_idx ON houses_70 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_70_isactual_idx ON houses_70 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_70_isactive_idx ON houses_70 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_71 (CONSTRAINT houses_71_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_71_objectid_idx ON houses_71 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_71_housetype_idx ON houses_71 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_71_startdate_idx ON houses_71 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_71_enddate_idx ON houses_71 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_71_isactual_idx ON houses_71 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_71_isactive_idx ON houses_71 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_72 (CONSTRAINT houses_72_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_72_objectid_idx ON houses_72 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_72_housetype_idx ON houses_72 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_72_startdate_idx ON houses_72 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_72_enddate_idx ON houses_72 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_72_isactual_idx ON houses_72 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_72_isactive_idx ON houses_72 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_73 (CONSTRAINT houses_73_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_73_objectid_idx ON houses_73 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_73_housetype_idx ON houses_73 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_73_startdate_idx ON houses_73 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_73_enddate_idx ON houses_73 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_73_isactual_idx ON houses_73 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_73_isactive_idx ON houses_73 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_74 (CONSTRAINT houses_74_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_74_objectid_idx ON houses_74 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_74_housetype_idx ON houses_74 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_74_startdate_idx ON houses_74 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_74_enddate_idx ON houses_74 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_74_isactual_idx ON houses_74 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_74_isactive_idx ON houses_74 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_75 (CONSTRAINT houses_75_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_75_objectid_idx ON houses_75 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_75_housetype_idx ON houses_75 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_75_startdate_idx ON houses_75 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_75_enddate_idx ON houses_75 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_75_isactual_idx ON houses_75 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_75_isactive_idx ON houses_75 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_76 (CONSTRAINT houses_76_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_76_objectid_idx ON houses_76 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_76_housetype_idx ON houses_76 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_76_startdate_idx ON houses_76 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_76_enddate_idx ON houses_76 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_76_isactual_idx ON houses_76 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_76_isactive_idx ON houses_76 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_77 (CONSTRAINT houses_77_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_77_objectid_idx ON houses_77 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_77_housetype_idx ON houses_77 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_77_startdate_idx ON houses_77 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_77_enddate_idx ON houses_77 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_77_isactual_idx ON houses_77 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_77_isactive_idx ON houses_77 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_78 (CONSTRAINT houses_78_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_78_objectid_idx ON houses_78 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_78_housetype_idx ON houses_78 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_78_startdate_idx ON houses_78 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_78_enddate_idx ON houses_78 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_78_isactual_idx ON houses_78 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_78_isactive_idx ON houses_78 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_79 (CONSTRAINT houses_79_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_79_objectid_idx ON houses_79 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_79_housetype_idx ON houses_79 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_79_startdate_idx ON houses_79 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_79_enddate_idx ON houses_79 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_79_isactual_idx ON houses_79 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_79_isactive_idx ON houses_79 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_80 (CONSTRAINT houses_80_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_80_objectid_idx ON houses_80 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_80_housetype_idx ON houses_80 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_80_startdate_idx ON houses_80 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_80_enddate_idx ON houses_80 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_80_isactual_idx ON houses_80 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_80_isactive_idx ON houses_80 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_81 (CONSTRAINT houses_81_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_81_objectid_idx ON houses_81 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_81_housetype_idx ON houses_81 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_81_startdate_idx ON houses_81 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_81_enddate_idx ON houses_81 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_81_isactual_idx ON houses_81 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_81_isactive_idx ON houses_81 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_82 (CONSTRAINT houses_82_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_82_objectid_idx ON houses_82 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_82_housetype_idx ON houses_82 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_82_startdate_idx ON houses_82 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_82_enddate_idx ON houses_82 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_82_isactual_idx ON houses_82 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_82_isactive_idx ON houses_82 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_83 (CONSTRAINT houses_83_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_83_objectid_idx ON houses_83 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_83_housetype_idx ON houses_83 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_83_startdate_idx ON houses_83 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_83_enddate_idx ON houses_83 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_83_isactual_idx ON houses_83 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_83_isactive_idx ON houses_83 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_84 (CONSTRAINT houses_84_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_84_objectid_idx ON houses_84 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_84_housetype_idx ON houses_84 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_84_startdate_idx ON houses_84 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_84_enddate_idx ON houses_84 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_84_isactual_idx ON houses_84 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_84_isactive_idx ON houses_84 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_85 (CONSTRAINT houses_85_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_85_objectid_idx ON houses_85 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_85_housetype_idx ON houses_85 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_85_startdate_idx ON houses_85 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_85_enddate_idx ON houses_85 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_85_isactual_idx ON houses_85 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_85_isactive_idx ON houses_85 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_86 (CONSTRAINT houses_86_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_86_objectid_idx ON houses_86 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_86_housetype_idx ON houses_86 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_86_startdate_idx ON houses_86 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_86_enddate_idx ON houses_86 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_86_isactual_idx ON houses_86 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_86_isactive_idx ON houses_86 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_87 (CONSTRAINT houses_87_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_87_objectid_idx ON houses_87 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_87_housetype_idx ON houses_87 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_87_startdate_idx ON houses_87 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_87_enddate_idx ON houses_87 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_87_isactual_idx ON houses_87 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_87_isactive_idx ON houses_87 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_88 (CONSTRAINT houses_88_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_88_objectid_idx ON houses_88 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_88_housetype_idx ON houses_88 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_88_startdate_idx ON houses_88 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_88_enddate_idx ON houses_88 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_88_isactual_idx ON houses_88 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_88_isactive_idx ON houses_88 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_89 (CONSTRAINT houses_89_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_89_objectid_idx ON houses_89 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_89_housetype_idx ON houses_89 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_89_startdate_idx ON houses_89 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_89_enddate_idx ON houses_89 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_89_isactual_idx ON houses_89 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_89_isactive_idx ON houses_89 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_90 (CONSTRAINT houses_90_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_90_objectid_idx ON houses_90 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_90_housetype_idx ON houses_90 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_90_startdate_idx ON houses_90 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_90_enddate_idx ON houses_90 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_90_isactual_idx ON houses_90 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_90_isactive_idx ON houses_90 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_91 (CONSTRAINT houses_91_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_91_objectid_idx ON houses_91 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_91_housetype_idx ON houses_91 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_91_startdate_idx ON houses_91 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_91_enddate_idx ON houses_91 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_91_isactual_idx ON houses_91 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_91_isactive_idx ON houses_91 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_92 (CONSTRAINT houses_92_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_92_objectid_idx ON houses_92 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_92_housetype_idx ON houses_92 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_92_startdate_idx ON houses_92 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_92_enddate_idx ON houses_92 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_92_isactual_idx ON houses_92 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_92_isactive_idx ON houses_92 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_93 (CONSTRAINT houses_93_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_93_objectid_idx ON houses_93 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_93_housetype_idx ON houses_93 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_93_startdate_idx ON houses_93 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_93_enddate_idx ON houses_93 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_93_isactual_idx ON houses_93 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_93_isactive_idx ON houses_93 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_94 (CONSTRAINT houses_94_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_94_objectid_idx ON houses_94 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_94_housetype_idx ON houses_94 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_94_startdate_idx ON houses_94 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_94_enddate_idx ON houses_94 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_94_isactual_idx ON houses_94 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_94_isactive_idx ON houses_94 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_95 (CONSTRAINT houses_95_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_95_objectid_idx ON houses_95 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_95_housetype_idx ON houses_95 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_95_startdate_idx ON houses_95 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_95_enddate_idx ON houses_95 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_95_isactual_idx ON houses_95 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_95_isactive_idx ON houses_95 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_96 (CONSTRAINT houses_96_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_96_objectid_idx ON houses_96 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_96_housetype_idx ON houses_96 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_96_startdate_idx ON houses_96 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_96_enddate_idx ON houses_96 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_96_isactual_idx ON houses_96 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_96_isactive_idx ON houses_96 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_97 (CONSTRAINT houses_97_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_97_objectid_idx ON houses_97 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_97_housetype_idx ON houses_97 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_97_startdate_idx ON houses_97 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_97_enddate_idx ON houses_97 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_97_isactual_idx ON houses_97 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_97_isactive_idx ON houses_97 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_98 (CONSTRAINT houses_98_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_98_objectid_idx ON houses_98 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_98_housetype_idx ON houses_98 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_98_startdate_idx ON houses_98 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_98_enddate_idx ON houses_98 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_98_isactual_idx ON houses_98 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_98_isactive_idx ON houses_98 USING btree (isactive);
CREATE TABLE IF NOT EXISTS houses_99 (CONSTRAINT houses_99_pkey PRIMARY KEY (id)) INHERITS (houses);
CREATE INDEX IF NOT EXISTS houses_99_objectid_idx ON houses_99 USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_99_housetype_idx ON houses_99 USING btree (housetype);
CREATE INDEX IF NOT EXISTS houses_99_startdate_idx ON houses_99 USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_99_enddate_idx ON houses_99 USING btree (enddate);
CREATE INDEX IF NOT EXISTS houses_99_isactual_idx ON houses_99 USING btree (isactual);
CREATE INDEX IF NOT EXISTS houses_99_isactive_idx ON houses_99 USING btree (isactive);
