#!/bin/sh -eux

DIR="$1"
exec psql --no-password --variable=ON_ERROR_STOP=1 <<EOF
CREATE TABLE IF NOT EXISTS addr_obj_params_$DIR (CONSTRAINT addr_obj_params_${DIR}_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE addr_obj_params_$DIR IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN addr_obj_params_$DIR.id IS 'Идентификатор записи';
COMMENT ON COLUMN addr_obj_params_$DIR.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN addr_obj_params_$DIR.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN addr_obj_params_$DIR.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN addr_obj_params_$DIR.typeid IS 'Тип параметра';
COMMENT ON COLUMN addr_obj_params_$DIR.value IS 'Значение параметра';
COMMENT ON COLUMN addr_obj_params_$DIR.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN addr_obj_params_$DIR.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN addr_obj_params_$DIR.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS addr_obj_params_${DIR}_objectid_idx ON addr_obj_params_$DIR USING btree (objectid);
CREATE INDEX IF NOT EXISTS addr_obj_params_${DIR}_typeid_idx ON addr_obj_params_$DIR USING btree (typeid);
CREATE INDEX IF NOT EXISTS addr_obj_params_${DIR}_startdate_idx ON addr_obj_params_$DIR USING btree (startdate);
CREATE INDEX IF NOT EXISTS addr_obj_params_${DIR}_enddate_idx ON addr_obj_params_$DIR USING btree (enddate);
CREATE TABLE IF NOT EXISTS apartments_params_$DIR (CONSTRAINT apartments_params_${DIR}_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE apartments_params_$DIR IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN apartments_params_$DIR.id IS 'Идентификатор записи';
COMMENT ON COLUMN apartments_params_$DIR.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN apartments_params_$DIR.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN apartments_params_$DIR.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN apartments_params_$DIR.typeid IS 'Тип параметра';
COMMENT ON COLUMN apartments_params_$DIR.value IS 'Значение параметра';
COMMENT ON COLUMN apartments_params_$DIR.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN apartments_params_$DIR.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN apartments_params_$DIR.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS apartments_params_${DIR}_objectid_idx ON apartments_params_$DIR USING btree (objectid);
CREATE INDEX IF NOT EXISTS apartments_params_${DIR}_typeid_idx ON apartments_params_$DIR USING btree (typeid);
CREATE INDEX IF NOT EXISTS apartments_params_${DIR}_startdate_idx ON apartments_params_$DIR USING btree (startdate);
CREATE INDEX IF NOT EXISTS apartments_params_${DIR}_enddate_idx ON apartments_params_$DIR USING btree (enddate);
CREATE TABLE IF NOT EXISTS carplaces_params_$DIR (CONSTRAINT carplaces_params_${DIR}_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE carplaces_params_$DIR IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN carplaces_params_$DIR.id IS 'Идентификатор записи';
COMMENT ON COLUMN carplaces_params_$DIR.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN carplaces_params_$DIR.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN carplaces_params_$DIR.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN carplaces_params_$DIR.typeid IS 'Тип параметра';
COMMENT ON COLUMN carplaces_params_$DIR.value IS 'Значение параметра';
COMMENT ON COLUMN carplaces_params_$DIR.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN carplaces_params_$DIR.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN carplaces_params_$DIR.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS carplaces_params_${DIR}_objectid_idx ON carplaces_params_$DIR USING btree (objectid);
CREATE INDEX IF NOT EXISTS carplaces_params_${DIR}_typeid_idx ON carplaces_params_$DIR USING btree (typeid);
CREATE INDEX IF NOT EXISTS carplaces_params_${DIR}_startdate_idx ON carplaces_params_$DIR USING btree (startdate);
CREATE INDEX IF NOT EXISTS carplaces_params_${DIR}_enddate_idx ON carplaces_params_$DIR USING btree (enddate);
CREATE TABLE IF NOT EXISTS houses_params_$DIR (CONSTRAINT houses_params_${DIR}_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE houses_params_$DIR IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN houses_params_$DIR.id IS 'Идентификатор записи';
COMMENT ON COLUMN houses_params_$DIR.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN houses_params_$DIR.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN houses_params_$DIR.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN houses_params_$DIR.typeid IS 'Тип параметра';
COMMENT ON COLUMN houses_params_$DIR.value IS 'Значение параметра';
COMMENT ON COLUMN houses_params_$DIR.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN houses_params_$DIR.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN houses_params_$DIR.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS houses_params_${DIR}_objectid_idx ON houses_params_$DIR USING btree (objectid);
CREATE INDEX IF NOT EXISTS houses_params_${DIR}_typeid_idx ON houses_params_$DIR USING btree (typeid);
CREATE INDEX IF NOT EXISTS houses_params_${DIR}_startdate_idx ON houses_params_$DIR USING btree (startdate);
CREATE INDEX IF NOT EXISTS houses_params_${DIR}_enddate_idx ON houses_params_$DIR USING btree (enddate);
CREATE TABLE IF NOT EXISTS rooms_params_$DIR (CONSTRAINT rooms_params_${DIR}_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE rooms_params_$DIR IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN rooms_params_$DIR.id IS 'Идентификатор записи';
COMMENT ON COLUMN rooms_params_$DIR.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN rooms_params_$DIR.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN rooms_params_$DIR.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN rooms_params_$DIR.typeid IS 'Тип параметра';
COMMENT ON COLUMN rooms_params_$DIR.value IS 'Значение параметра';
COMMENT ON COLUMN rooms_params_$DIR.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN rooms_params_$DIR.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN rooms_params_$DIR.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS rooms_params_${DIR}_objectid_idx ON rooms_params_$DIR USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_params_${DIR}_typeid_idx ON rooms_params_$DIR USING btree (typeid);
CREATE INDEX IF NOT EXISTS rooms_params_${DIR}_startdate_idx ON rooms_params_$DIR USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_params_${DIR}_enddate_idx ON rooms_params_$DIR USING btree (enddate);
CREATE TABLE IF NOT EXISTS steads_params_$DIR (CONSTRAINT steads_params_${DIR}_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE steads_params_$DIR IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN steads_params_$DIR.id IS 'Идентификатор записи';
COMMENT ON COLUMN steads_params_$DIR.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN steads_params_$DIR.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN steads_params_$DIR.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN steads_params_$DIR.typeid IS 'Тип параметра';
COMMENT ON COLUMN steads_params_$DIR.value IS 'Значение параметра';
COMMENT ON COLUMN steads_params_$DIR.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN steads_params_$DIR.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN steads_params_$DIR.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS steads_params_${DIR}_objectid_idx ON steads_params_$DIR USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_params_${DIR}_typeid_idx ON steads_params_$DIR USING btree (typeid);
CREATE INDEX IF NOT EXISTS steads_params_${DIR}_startdate_idx ON steads_params_$DIR USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_params_${DIR}_enddate_idx ON steads_params_$DIR USING btree (enddate);
EOF
