#!/bin/sh -eux

DIR="$1"
exec psql --no-password --variable=ON_ERROR_STOP=1 <<EOF
CREATE SCHEMA IF NOT EXISTS $DIR;
CREATE TABLE IF NOT EXISTS $DIR.addr_obj_params (CONSTRAINT $DIR.addr_obj_params_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE $DIR.addr_obj_params IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN $DIR.addr_obj_params.id IS 'Идентификатор записи';
COMMENT ON COLUMN $DIR.addr_obj_params.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN $DIR.addr_obj_params.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN $DIR.addr_obj_params.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN $DIR.addr_obj_params.typeid IS 'Тип параметра';
COMMENT ON COLUMN $DIR.addr_obj_params.value IS 'Значение параметра';
COMMENT ON COLUMN $DIR.addr_obj_params.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN $DIR.addr_obj_params.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN $DIR.addr_obj_params.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS $DIR.addr_obj_params_objectid_idx ON $DIR.addr_obj_params USING btree (objectid);
CREATE INDEX IF NOT EXISTS $DIR.addr_obj_params_typeid_idx ON $DIR.addr_obj_params USING btree (typeid);
CREATE INDEX IF NOT EXISTS $DIR.addr_obj_params_startdate_idx ON $DIR.addr_obj_params USING btree (startdate);
CREATE INDEX IF NOT EXISTS $DIR.addr_obj_params_enddate_idx ON $DIR.addr_obj_params USING btree (enddate);
CREATE TABLE IF NOT EXISTS $DIR.apartments_params (CONSTRAINT $DIR.apartments_params_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE $DIR.apartments_params IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN $DIR.apartments_params.id IS 'Идентификатор записи';
COMMENT ON COLUMN $DIR.apartments_params.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN $DIR.apartments_params.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN $DIR.apartments_params.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN $DIR.apartments_params.typeid IS 'Тип параметра';
COMMENT ON COLUMN $DIR.apartments_params.value IS 'Значение параметра';
COMMENT ON COLUMN $DIR.apartments_params.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN $DIR.apartments_params.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN $DIR.apartments_params.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS $DIR.apartments_params_objectid_idx ON $DIR.apartments_params USING btree (objectid);
CREATE INDEX IF NOT EXISTS $DIR.apartments_params_typeid_idx ON $DIR.apartments_params USING btree (typeid);
CREATE INDEX IF NOT EXISTS $DIR.apartments_params_startdate_idx ON $DIR.apartments_params USING btree (startdate);
CREATE INDEX IF NOT EXISTS $DIR.apartments_params_enddate_idx ON $DIR.apartments_params USING btree (enddate);
CREATE TABLE IF NOT EXISTS $DIR.carplaces_params (CONSTRAINT $DIR.carplaces_params_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE $DIR.carplaces_params IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN $DIR.carplaces_params.id IS 'Идентификатор записи';
COMMENT ON COLUMN $DIR.carplaces_params.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN $DIR.carplaces_params.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN $DIR.carplaces_params.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN $DIR.carplaces_params.typeid IS 'Тип параметра';
COMMENT ON COLUMN $DIR.carplaces_params.value IS 'Значение параметра';
COMMENT ON COLUMN $DIR.carplaces_params.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN $DIR.carplaces_params.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN $DIR.carplaces_params.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS $DIR.carplaces_params_objectid_idx ON $DIR.carplaces_params USING btree (objectid);
CREATE INDEX IF NOT EXISTS $DIR.carplaces_params_typeid_idx ON $DIR.carplaces_params USING btree (typeid);
CREATE INDEX IF NOT EXISTS $DIR.carplaces_params_startdate_idx ON $DIR.carplaces_params USING btree (startdate);
CREATE INDEX IF NOT EXISTS $DIR.carplaces_params_enddate_idx ON $DIR.carplaces_params USING btree (enddate);
CREATE TABLE IF NOT EXISTS $DIR.houses_params (CONSTRAINT $DIR.houses_params_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE $DIR.houses_params IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN $DIR.houses_params.id IS 'Идентификатор записи';
COMMENT ON COLUMN $DIR.houses_params.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN $DIR.houses_params.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN $DIR.houses_params.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN $DIR.houses_params.typeid IS 'Тип параметра';
COMMENT ON COLUMN $DIR.houses_params.value IS 'Значение параметра';
COMMENT ON COLUMN $DIR.houses_params.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN $DIR.houses_params.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN $DIR.houses_params.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS $DIR.houses_params_objectid_idx ON $DIR.houses_params USING btree (objectid);
CREATE INDEX IF NOT EXISTS $DIR.houses_params_typeid_idx ON $DIR.houses_params USING btree (typeid);
CREATE INDEX IF NOT EXISTS $DIR.houses_params_startdate_idx ON $DIR.houses_params USING btree (startdate);
CREATE INDEX IF NOT EXISTS $DIR.houses_params_enddate_idx ON $DIR.houses_params USING btree (enddate);
CREATE TABLE IF NOT EXISTS $DIR.rooms_params (CONSTRAINT $DIR.rooms_params_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE $DIR.rooms_params IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN $DIR.rooms_params.id IS 'Идентификатор записи';
COMMENT ON COLUMN $DIR.rooms_params.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN $DIR.rooms_params.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN $DIR.rooms_params.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN $DIR.rooms_params.typeid IS 'Тип параметра';
COMMENT ON COLUMN $DIR.rooms_params.value IS 'Значение параметра';
COMMENT ON COLUMN $DIR.rooms_params.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN $DIR.rooms_params.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN $DIR.rooms_params.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS $DIR.rooms_params_objectid_idx ON $DIR.rooms_params USING btree (objectid);
CREATE INDEX IF NOT EXISTS $DIR.rooms_params_typeid_idx ON $DIR.rooms_params USING btree (typeid);
CREATE INDEX IF NOT EXISTS $DIR.rooms_params_startdate_idx ON $DIR.rooms_params USING btree (startdate);
CREATE INDEX IF NOT EXISTS $DIR.rooms_params_enddate_idx ON $DIR.rooms_params USING btree (enddate);
CREATE TABLE IF NOT EXISTS $DIR.steads_params (CONSTRAINT $DIR.steads_params_pkey PRIMARY KEY (id)) INHERITS (param);
COMMENT ON TABLE $DIR.steads_params IS 'Сведения о классификаторе параметров адресообразующих элементов и объектов недвижимости ';
COMMENT ON COLUMN $DIR.steads_params.id IS 'Идентификатор записи';
COMMENT ON COLUMN $DIR.steads_params.objectid IS 'Глобальный уникальный идентификатор адресного объекта ';
COMMENT ON COLUMN $DIR.steads_params.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN $DIR.steads_params.changeidend IS 'ID завершившей транзакции';
COMMENT ON COLUMN $DIR.steads_params.typeid IS 'Тип параметра';
COMMENT ON COLUMN $DIR.steads_params.value IS 'Значение параметра';
COMMENT ON COLUMN $DIR.steads_params.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN $DIR.steads_params.startdate IS 'Дата начала действия записи';
COMMENT ON COLUMN $DIR.steads_params.enddate IS 'Дата окончания действия записи';
CREATE INDEX IF NOT EXISTS $DIR.steads_params_objectid_idx ON $DIR.steads_params USING btree (objectid);
CREATE INDEX IF NOT EXISTS $DIR.steads_params_typeid_idx ON $DIR.steads_params USING btree (typeid);
CREATE INDEX IF NOT EXISTS $DIR.steads_params_startdate_idx ON $DIR.steads_params USING btree (startdate);
CREATE INDEX IF NOT EXISTS $DIR.steads_params_enddate_idx ON $DIR.steads_params USING btree (enddate);
EOF
