CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT NOT NULL PRIMARY KEY,
  objectid BIGINT NOT NULL,
  objectguid UUID NOT NULL,
  changeid BIGINT NOT NULL,
  number VARCHAR(50) NOT NULL,
  roomtype INT NOT NULL,
  opertypeid INT NOT NULL,
  previd BIGINT,
  nextid BIGINT,
  updatedate DATE NOT NULL,
  startdate DATE NOT NULL,
  enddate DATE NOT NULL,
  isactual SMALLINT NOT NULL,
  isactive SMALLINT NOT NULL
);
COMMENT ON TABLE rooms IS 'Сведения по комнатам';
COMMENT ON COLUMN rooms.id IS 'Уникальный идентификатор записи. Ключевое поле';
COMMENT ON COLUMN rooms.objectid IS 'Глобальный уникальный идентификатор объекта типа INTEGER';
COMMENT ON COLUMN rooms.objectguid IS 'Глобальный уникальный идентификатор адресного объекта типа UUID';
COMMENT ON COLUMN rooms.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN rooms.number IS 'Номер комнаты или офиса';
COMMENT ON COLUMN rooms.roomtype IS 'Тип комнаты или офиса';
COMMENT ON COLUMN rooms.opertypeid IS 'Статус действия над записью – причина появления записи';
COMMENT ON COLUMN rooms.previd IS 'Идентификатор записи связывания с предыдущей исторической записью';
COMMENT ON COLUMN rooms.nextid IS 'Идентификатор записи связывания с последующей исторической записью';
COMMENT ON COLUMN rooms.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN rooms.startdate IS 'Начало действия записи';
COMMENT ON COLUMN rooms.enddate IS 'Окончание действия записи';
COMMENT ON COLUMN rooms.isactual IS 'Статус актуальности адресного объекта ФИАС';
COMMENT ON COLUMN rooms.isactive IS 'Признак действующего адресного объекта';
CREATE INDEX IF NOT EXISTS rooms_objectid_idx ON rooms USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_roomtype_idx ON rooms USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_startdate_idx ON rooms USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_enddate_idx ON rooms USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_isactual_idx ON rooms USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_isactive_idx ON rooms USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_01 (CONSTRAINT rooms_01_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_01_objectid_idx ON rooms_01 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_01_roomtype_idx ON rooms_01 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_01_startdate_idx ON rooms_01 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_01_enddate_idx ON rooms_01 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_01_isactual_idx ON rooms_01 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_01_isactive_idx ON rooms_01 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_02 (CONSTRAINT rooms_02_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_02_objectid_idx ON rooms_02 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_02_roomtype_idx ON rooms_02 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_02_startdate_idx ON rooms_02 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_02_enddate_idx ON rooms_02 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_02_isactual_idx ON rooms_02 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_02_isactive_idx ON rooms_02 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_03 (CONSTRAINT rooms_03_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_03_objectid_idx ON rooms_03 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_03_roomtype_idx ON rooms_03 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_03_startdate_idx ON rooms_03 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_03_enddate_idx ON rooms_03 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_03_isactual_idx ON rooms_03 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_03_isactive_idx ON rooms_03 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_04 (CONSTRAINT rooms_04_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_04_objectid_idx ON rooms_04 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_04_roomtype_idx ON rooms_04 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_04_startdate_idx ON rooms_04 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_04_enddate_idx ON rooms_04 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_04_isactual_idx ON rooms_04 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_04_isactive_idx ON rooms_04 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_05 (CONSTRAINT rooms_05_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_05_objectid_idx ON rooms_05 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_05_roomtype_idx ON rooms_05 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_05_startdate_idx ON rooms_05 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_05_enddate_idx ON rooms_05 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_05_isactual_idx ON rooms_05 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_05_isactive_idx ON rooms_05 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_06 (CONSTRAINT rooms_06_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_06_objectid_idx ON rooms_06 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_06_roomtype_idx ON rooms_06 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_06_startdate_idx ON rooms_06 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_06_enddate_idx ON rooms_06 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_06_isactual_idx ON rooms_06 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_06_isactive_idx ON rooms_06 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_07 (CONSTRAINT rooms_07_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_07_objectid_idx ON rooms_07 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_07_roomtype_idx ON rooms_07 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_07_startdate_idx ON rooms_07 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_07_enddate_idx ON rooms_07 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_07_isactual_idx ON rooms_07 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_07_isactive_idx ON rooms_07 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_08 (CONSTRAINT rooms_08_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_08_objectid_idx ON rooms_08 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_08_roomtype_idx ON rooms_08 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_08_startdate_idx ON rooms_08 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_08_enddate_idx ON rooms_08 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_08_isactual_idx ON rooms_08 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_08_isactive_idx ON rooms_08 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_09 (CONSTRAINT rooms_09_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_09_objectid_idx ON rooms_09 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_09_roomtype_idx ON rooms_09 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_09_startdate_idx ON rooms_09 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_09_enddate_idx ON rooms_09 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_09_isactual_idx ON rooms_09 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_09_isactive_idx ON rooms_09 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_10 (CONSTRAINT rooms_10_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_10_objectid_idx ON rooms_10 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_10_roomtype_idx ON rooms_10 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_10_startdate_idx ON rooms_10 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_10_enddate_idx ON rooms_10 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_10_isactual_idx ON rooms_10 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_10_isactive_idx ON rooms_10 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_11 (CONSTRAINT rooms_11_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_11_objectid_idx ON rooms_11 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_11_roomtype_idx ON rooms_11 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_11_startdate_idx ON rooms_11 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_11_enddate_idx ON rooms_11 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_11_isactual_idx ON rooms_11 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_11_isactive_idx ON rooms_11 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_12 (CONSTRAINT rooms_12_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_12_objectid_idx ON rooms_12 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_12_roomtype_idx ON rooms_12 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_12_startdate_idx ON rooms_12 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_12_enddate_idx ON rooms_12 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_12_isactual_idx ON rooms_12 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_12_isactive_idx ON rooms_12 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_13 (CONSTRAINT rooms_13_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_13_objectid_idx ON rooms_13 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_13_roomtype_idx ON rooms_13 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_13_startdate_idx ON rooms_13 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_13_enddate_idx ON rooms_13 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_13_isactual_idx ON rooms_13 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_13_isactive_idx ON rooms_13 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_14 (CONSTRAINT rooms_14_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_14_objectid_idx ON rooms_14 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_14_roomtype_idx ON rooms_14 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_14_startdate_idx ON rooms_14 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_14_enddate_idx ON rooms_14 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_14_isactual_idx ON rooms_14 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_14_isactive_idx ON rooms_14 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_15 (CONSTRAINT rooms_15_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_15_objectid_idx ON rooms_15 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_15_roomtype_idx ON rooms_15 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_15_startdate_idx ON rooms_15 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_15_enddate_idx ON rooms_15 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_15_isactual_idx ON rooms_15 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_15_isactive_idx ON rooms_15 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_16 (CONSTRAINT rooms_16_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_16_objectid_idx ON rooms_16 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_16_roomtype_idx ON rooms_16 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_16_startdate_idx ON rooms_16 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_16_enddate_idx ON rooms_16 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_16_isactual_idx ON rooms_16 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_16_isactive_idx ON rooms_16 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_17 (CONSTRAINT rooms_17_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_17_objectid_idx ON rooms_17 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_17_roomtype_idx ON rooms_17 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_17_startdate_idx ON rooms_17 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_17_enddate_idx ON rooms_17 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_17_isactual_idx ON rooms_17 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_17_isactive_idx ON rooms_17 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_18 (CONSTRAINT rooms_18_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_18_objectid_idx ON rooms_18 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_18_roomtype_idx ON rooms_18 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_18_startdate_idx ON rooms_18 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_18_enddate_idx ON rooms_18 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_18_isactual_idx ON rooms_18 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_18_isactive_idx ON rooms_18 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_19 (CONSTRAINT rooms_19_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_19_objectid_idx ON rooms_19 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_19_roomtype_idx ON rooms_19 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_19_startdate_idx ON rooms_19 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_19_enddate_idx ON rooms_19 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_19_isactual_idx ON rooms_19 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_19_isactive_idx ON rooms_19 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_20 (CONSTRAINT rooms_20_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_20_objectid_idx ON rooms_20 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_20_roomtype_idx ON rooms_20 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_20_startdate_idx ON rooms_20 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_20_enddate_idx ON rooms_20 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_20_isactual_idx ON rooms_20 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_20_isactive_idx ON rooms_20 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_21 (CONSTRAINT rooms_21_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_21_objectid_idx ON rooms_21 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_21_roomtype_idx ON rooms_21 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_21_startdate_idx ON rooms_21 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_21_enddate_idx ON rooms_21 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_21_isactual_idx ON rooms_21 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_21_isactive_idx ON rooms_21 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_22 (CONSTRAINT rooms_22_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_22_objectid_idx ON rooms_22 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_22_roomtype_idx ON rooms_22 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_22_startdate_idx ON rooms_22 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_22_enddate_idx ON rooms_22 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_22_isactual_idx ON rooms_22 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_22_isactive_idx ON rooms_22 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_23 (CONSTRAINT rooms_23_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_23_objectid_idx ON rooms_23 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_23_roomtype_idx ON rooms_23 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_23_startdate_idx ON rooms_23 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_23_enddate_idx ON rooms_23 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_23_isactual_idx ON rooms_23 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_23_isactive_idx ON rooms_23 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_24 (CONSTRAINT rooms_24_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_24_objectid_idx ON rooms_24 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_24_roomtype_idx ON rooms_24 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_24_startdate_idx ON rooms_24 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_24_enddate_idx ON rooms_24 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_24_isactual_idx ON rooms_24 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_24_isactive_idx ON rooms_24 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_25 (CONSTRAINT rooms_25_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_25_objectid_idx ON rooms_25 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_25_roomtype_idx ON rooms_25 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_25_startdate_idx ON rooms_25 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_25_enddate_idx ON rooms_25 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_25_isactual_idx ON rooms_25 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_25_isactive_idx ON rooms_25 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_26 (CONSTRAINT rooms_26_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_26_objectid_idx ON rooms_26 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_26_roomtype_idx ON rooms_26 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_26_startdate_idx ON rooms_26 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_26_enddate_idx ON rooms_26 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_26_isactual_idx ON rooms_26 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_26_isactive_idx ON rooms_26 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_27 (CONSTRAINT rooms_27_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_27_objectid_idx ON rooms_27 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_27_roomtype_idx ON rooms_27 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_27_startdate_idx ON rooms_27 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_27_enddate_idx ON rooms_27 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_27_isactual_idx ON rooms_27 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_27_isactive_idx ON rooms_27 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_28 (CONSTRAINT rooms_28_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_28_objectid_idx ON rooms_28 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_28_roomtype_idx ON rooms_28 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_28_startdate_idx ON rooms_28 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_28_enddate_idx ON rooms_28 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_28_isactual_idx ON rooms_28 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_28_isactive_idx ON rooms_28 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_29 (CONSTRAINT rooms_29_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_29_objectid_idx ON rooms_29 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_29_roomtype_idx ON rooms_29 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_29_startdate_idx ON rooms_29 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_29_enddate_idx ON rooms_29 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_29_isactual_idx ON rooms_29 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_29_isactive_idx ON rooms_29 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_30 (CONSTRAINT rooms_30_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_30_objectid_idx ON rooms_30 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_30_roomtype_idx ON rooms_30 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_30_startdate_idx ON rooms_30 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_30_enddate_idx ON rooms_30 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_30_isactual_idx ON rooms_30 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_30_isactive_idx ON rooms_30 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_31 (CONSTRAINT rooms_31_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_31_objectid_idx ON rooms_31 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_31_roomtype_idx ON rooms_31 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_31_startdate_idx ON rooms_31 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_31_enddate_idx ON rooms_31 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_31_isactual_idx ON rooms_31 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_31_isactive_idx ON rooms_31 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_32 (CONSTRAINT rooms_32_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_32_objectid_idx ON rooms_32 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_32_roomtype_idx ON rooms_32 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_32_startdate_idx ON rooms_32 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_32_enddate_idx ON rooms_32 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_32_isactual_idx ON rooms_32 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_32_isactive_idx ON rooms_32 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_33 (CONSTRAINT rooms_33_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_33_objectid_idx ON rooms_33 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_33_roomtype_idx ON rooms_33 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_33_startdate_idx ON rooms_33 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_33_enddate_idx ON rooms_33 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_33_isactual_idx ON rooms_33 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_33_isactive_idx ON rooms_33 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_34 (CONSTRAINT rooms_34_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_34_objectid_idx ON rooms_34 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_34_roomtype_idx ON rooms_34 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_34_startdate_idx ON rooms_34 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_34_enddate_idx ON rooms_34 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_34_isactual_idx ON rooms_34 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_34_isactive_idx ON rooms_34 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_35 (CONSTRAINT rooms_35_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_35_objectid_idx ON rooms_35 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_35_roomtype_idx ON rooms_35 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_35_startdate_idx ON rooms_35 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_35_enddate_idx ON rooms_35 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_35_isactual_idx ON rooms_35 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_35_isactive_idx ON rooms_35 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_36 (CONSTRAINT rooms_36_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_36_objectid_idx ON rooms_36 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_36_roomtype_idx ON rooms_36 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_36_startdate_idx ON rooms_36 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_36_enddate_idx ON rooms_36 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_36_isactual_idx ON rooms_36 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_36_isactive_idx ON rooms_36 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_37 (CONSTRAINT rooms_37_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_37_objectid_idx ON rooms_37 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_37_roomtype_idx ON rooms_37 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_37_startdate_idx ON rooms_37 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_37_enddate_idx ON rooms_37 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_37_isactual_idx ON rooms_37 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_37_isactive_idx ON rooms_37 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_38 (CONSTRAINT rooms_38_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_38_objectid_idx ON rooms_38 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_38_roomtype_idx ON rooms_38 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_38_startdate_idx ON rooms_38 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_38_enddate_idx ON rooms_38 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_38_isactual_idx ON rooms_38 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_38_isactive_idx ON rooms_38 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_39 (CONSTRAINT rooms_39_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_39_objectid_idx ON rooms_39 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_39_roomtype_idx ON rooms_39 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_39_startdate_idx ON rooms_39 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_39_enddate_idx ON rooms_39 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_39_isactual_idx ON rooms_39 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_39_isactive_idx ON rooms_39 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_40 (CONSTRAINT rooms_40_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_40_objectid_idx ON rooms_40 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_40_roomtype_idx ON rooms_40 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_40_startdate_idx ON rooms_40 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_40_enddate_idx ON rooms_40 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_40_isactual_idx ON rooms_40 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_40_isactive_idx ON rooms_40 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_41 (CONSTRAINT rooms_41_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_41_objectid_idx ON rooms_41 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_41_roomtype_idx ON rooms_41 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_41_startdate_idx ON rooms_41 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_41_enddate_idx ON rooms_41 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_41_isactual_idx ON rooms_41 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_41_isactive_idx ON rooms_41 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_42 (CONSTRAINT rooms_42_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_42_objectid_idx ON rooms_42 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_42_roomtype_idx ON rooms_42 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_42_startdate_idx ON rooms_42 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_42_enddate_idx ON rooms_42 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_42_isactual_idx ON rooms_42 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_42_isactive_idx ON rooms_42 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_43 (CONSTRAINT rooms_43_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_43_objectid_idx ON rooms_43 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_43_roomtype_idx ON rooms_43 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_43_startdate_idx ON rooms_43 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_43_enddate_idx ON rooms_43 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_43_isactual_idx ON rooms_43 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_43_isactive_idx ON rooms_43 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_44 (CONSTRAINT rooms_44_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_44_objectid_idx ON rooms_44 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_44_roomtype_idx ON rooms_44 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_44_startdate_idx ON rooms_44 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_44_enddate_idx ON rooms_44 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_44_isactual_idx ON rooms_44 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_44_isactive_idx ON rooms_44 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_45 (CONSTRAINT rooms_45_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_45_objectid_idx ON rooms_45 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_45_roomtype_idx ON rooms_45 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_45_startdate_idx ON rooms_45 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_45_enddate_idx ON rooms_45 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_45_isactual_idx ON rooms_45 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_45_isactive_idx ON rooms_45 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_46 (CONSTRAINT rooms_46_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_46_objectid_idx ON rooms_46 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_46_roomtype_idx ON rooms_46 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_46_startdate_idx ON rooms_46 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_46_enddate_idx ON rooms_46 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_46_isactual_idx ON rooms_46 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_46_isactive_idx ON rooms_46 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_47 (CONSTRAINT rooms_47_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_47_objectid_idx ON rooms_47 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_47_roomtype_idx ON rooms_47 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_47_startdate_idx ON rooms_47 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_47_enddate_idx ON rooms_47 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_47_isactual_idx ON rooms_47 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_47_isactive_idx ON rooms_47 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_48 (CONSTRAINT rooms_48_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_48_objectid_idx ON rooms_48 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_48_roomtype_idx ON rooms_48 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_48_startdate_idx ON rooms_48 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_48_enddate_idx ON rooms_48 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_48_isactual_idx ON rooms_48 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_48_isactive_idx ON rooms_48 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_49 (CONSTRAINT rooms_49_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_49_objectid_idx ON rooms_49 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_49_roomtype_idx ON rooms_49 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_49_startdate_idx ON rooms_49 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_49_enddate_idx ON rooms_49 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_49_isactual_idx ON rooms_49 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_49_isactive_idx ON rooms_49 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_50 (CONSTRAINT rooms_50_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_50_objectid_idx ON rooms_50 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_50_roomtype_idx ON rooms_50 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_50_startdate_idx ON rooms_50 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_50_enddate_idx ON rooms_50 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_50_isactual_idx ON rooms_50 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_50_isactive_idx ON rooms_50 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_51 (CONSTRAINT rooms_51_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_51_objectid_idx ON rooms_51 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_51_roomtype_idx ON rooms_51 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_51_startdate_idx ON rooms_51 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_51_enddate_idx ON rooms_51 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_51_isactual_idx ON rooms_51 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_51_isactive_idx ON rooms_51 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_52 (CONSTRAINT rooms_52_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_52_objectid_idx ON rooms_52 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_52_roomtype_idx ON rooms_52 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_52_startdate_idx ON rooms_52 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_52_enddate_idx ON rooms_52 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_52_isactual_idx ON rooms_52 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_52_isactive_idx ON rooms_52 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_53 (CONSTRAINT rooms_53_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_53_objectid_idx ON rooms_53 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_53_roomtype_idx ON rooms_53 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_53_startdate_idx ON rooms_53 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_53_enddate_idx ON rooms_53 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_53_isactual_idx ON rooms_53 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_53_isactive_idx ON rooms_53 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_54 (CONSTRAINT rooms_54_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_54_objectid_idx ON rooms_54 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_54_roomtype_idx ON rooms_54 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_54_startdate_idx ON rooms_54 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_54_enddate_idx ON rooms_54 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_54_isactual_idx ON rooms_54 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_54_isactive_idx ON rooms_54 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_55 (CONSTRAINT rooms_55_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_55_objectid_idx ON rooms_55 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_55_roomtype_idx ON rooms_55 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_55_startdate_idx ON rooms_55 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_55_enddate_idx ON rooms_55 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_55_isactual_idx ON rooms_55 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_55_isactive_idx ON rooms_55 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_56 (CONSTRAINT rooms_56_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_56_objectid_idx ON rooms_56 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_56_roomtype_idx ON rooms_56 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_56_startdate_idx ON rooms_56 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_56_enddate_idx ON rooms_56 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_56_isactual_idx ON rooms_56 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_56_isactive_idx ON rooms_56 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_57 (CONSTRAINT rooms_57_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_57_objectid_idx ON rooms_57 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_57_roomtype_idx ON rooms_57 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_57_startdate_idx ON rooms_57 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_57_enddate_idx ON rooms_57 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_57_isactual_idx ON rooms_57 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_57_isactive_idx ON rooms_57 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_58 (CONSTRAINT rooms_58_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_58_objectid_idx ON rooms_58 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_58_roomtype_idx ON rooms_58 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_58_startdate_idx ON rooms_58 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_58_enddate_idx ON rooms_58 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_58_isactual_idx ON rooms_58 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_58_isactive_idx ON rooms_58 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_59 (CONSTRAINT rooms_59_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_59_objectid_idx ON rooms_59 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_59_roomtype_idx ON rooms_59 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_59_startdate_idx ON rooms_59 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_59_enddate_idx ON rooms_59 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_59_isactual_idx ON rooms_59 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_59_isactive_idx ON rooms_59 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_60 (CONSTRAINT rooms_60_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_60_objectid_idx ON rooms_60 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_60_roomtype_idx ON rooms_60 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_60_startdate_idx ON rooms_60 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_60_enddate_idx ON rooms_60 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_60_isactual_idx ON rooms_60 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_60_isactive_idx ON rooms_60 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_61 (CONSTRAINT rooms_61_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_61_objectid_idx ON rooms_61 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_61_roomtype_idx ON rooms_61 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_61_startdate_idx ON rooms_61 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_61_enddate_idx ON rooms_61 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_61_isactual_idx ON rooms_61 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_61_isactive_idx ON rooms_61 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_62 (CONSTRAINT rooms_62_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_62_objectid_idx ON rooms_62 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_62_roomtype_idx ON rooms_62 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_62_startdate_idx ON rooms_62 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_62_enddate_idx ON rooms_62 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_62_isactual_idx ON rooms_62 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_62_isactive_idx ON rooms_62 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_63 (CONSTRAINT rooms_63_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_63_objectid_idx ON rooms_63 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_63_roomtype_idx ON rooms_63 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_63_startdate_idx ON rooms_63 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_63_enddate_idx ON rooms_63 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_63_isactual_idx ON rooms_63 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_63_isactive_idx ON rooms_63 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_64 (CONSTRAINT rooms_64_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_64_objectid_idx ON rooms_64 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_64_roomtype_idx ON rooms_64 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_64_startdate_idx ON rooms_64 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_64_enddate_idx ON rooms_64 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_64_isactual_idx ON rooms_64 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_64_isactive_idx ON rooms_64 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_65 (CONSTRAINT rooms_65_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_65_objectid_idx ON rooms_65 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_65_roomtype_idx ON rooms_65 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_65_startdate_idx ON rooms_65 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_65_enddate_idx ON rooms_65 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_65_isactual_idx ON rooms_65 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_65_isactive_idx ON rooms_65 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_66 (CONSTRAINT rooms_66_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_66_objectid_idx ON rooms_66 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_66_roomtype_idx ON rooms_66 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_66_startdate_idx ON rooms_66 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_66_enddate_idx ON rooms_66 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_66_isactual_idx ON rooms_66 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_66_isactive_idx ON rooms_66 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_67 (CONSTRAINT rooms_67_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_67_objectid_idx ON rooms_67 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_67_roomtype_idx ON rooms_67 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_67_startdate_idx ON rooms_67 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_67_enddate_idx ON rooms_67 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_67_isactual_idx ON rooms_67 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_67_isactive_idx ON rooms_67 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_68 (CONSTRAINT rooms_68_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_68_objectid_idx ON rooms_68 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_68_roomtype_idx ON rooms_68 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_68_startdate_idx ON rooms_68 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_68_enddate_idx ON rooms_68 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_68_isactual_idx ON rooms_68 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_68_isactive_idx ON rooms_68 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_69 (CONSTRAINT rooms_69_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_69_objectid_idx ON rooms_69 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_69_roomtype_idx ON rooms_69 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_69_startdate_idx ON rooms_69 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_69_enddate_idx ON rooms_69 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_69_isactual_idx ON rooms_69 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_69_isactive_idx ON rooms_69 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_70 (CONSTRAINT rooms_70_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_70_objectid_idx ON rooms_70 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_70_roomtype_idx ON rooms_70 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_70_startdate_idx ON rooms_70 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_70_enddate_idx ON rooms_70 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_70_isactual_idx ON rooms_70 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_70_isactive_idx ON rooms_70 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_71 (CONSTRAINT rooms_71_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_71_objectid_idx ON rooms_71 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_71_roomtype_idx ON rooms_71 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_71_startdate_idx ON rooms_71 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_71_enddate_idx ON rooms_71 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_71_isactual_idx ON rooms_71 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_71_isactive_idx ON rooms_71 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_72 (CONSTRAINT rooms_72_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_72_objectid_idx ON rooms_72 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_72_roomtype_idx ON rooms_72 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_72_startdate_idx ON rooms_72 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_72_enddate_idx ON rooms_72 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_72_isactual_idx ON rooms_72 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_72_isactive_idx ON rooms_72 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_73 (CONSTRAINT rooms_73_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_73_objectid_idx ON rooms_73 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_73_roomtype_idx ON rooms_73 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_73_startdate_idx ON rooms_73 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_73_enddate_idx ON rooms_73 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_73_isactual_idx ON rooms_73 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_73_isactive_idx ON rooms_73 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_74 (CONSTRAINT rooms_74_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_74_objectid_idx ON rooms_74 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_74_roomtype_idx ON rooms_74 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_74_startdate_idx ON rooms_74 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_74_enddate_idx ON rooms_74 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_74_isactual_idx ON rooms_74 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_74_isactive_idx ON rooms_74 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_75 (CONSTRAINT rooms_75_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_75_objectid_idx ON rooms_75 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_75_roomtype_idx ON rooms_75 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_75_startdate_idx ON rooms_75 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_75_enddate_idx ON rooms_75 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_75_isactual_idx ON rooms_75 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_75_isactive_idx ON rooms_75 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_76 (CONSTRAINT rooms_76_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_76_objectid_idx ON rooms_76 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_76_roomtype_idx ON rooms_76 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_76_startdate_idx ON rooms_76 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_76_enddate_idx ON rooms_76 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_76_isactual_idx ON rooms_76 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_76_isactive_idx ON rooms_76 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_77 (CONSTRAINT rooms_77_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_77_objectid_idx ON rooms_77 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_77_roomtype_idx ON rooms_77 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_77_startdate_idx ON rooms_77 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_77_enddate_idx ON rooms_77 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_77_isactual_idx ON rooms_77 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_77_isactive_idx ON rooms_77 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_78 (CONSTRAINT rooms_78_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_78_objectid_idx ON rooms_78 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_78_roomtype_idx ON rooms_78 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_78_startdate_idx ON rooms_78 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_78_enddate_idx ON rooms_78 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_78_isactual_idx ON rooms_78 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_78_isactive_idx ON rooms_78 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_79 (CONSTRAINT rooms_79_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_79_objectid_idx ON rooms_79 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_79_roomtype_idx ON rooms_79 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_79_startdate_idx ON rooms_79 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_79_enddate_idx ON rooms_79 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_79_isactual_idx ON rooms_79 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_79_isactive_idx ON rooms_79 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_80 (CONSTRAINT rooms_80_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_80_objectid_idx ON rooms_80 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_80_roomtype_idx ON rooms_80 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_80_startdate_idx ON rooms_80 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_80_enddate_idx ON rooms_80 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_80_isactual_idx ON rooms_80 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_80_isactive_idx ON rooms_80 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_81 (CONSTRAINT rooms_81_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_81_objectid_idx ON rooms_81 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_81_roomtype_idx ON rooms_81 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_81_startdate_idx ON rooms_81 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_81_enddate_idx ON rooms_81 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_81_isactual_idx ON rooms_81 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_81_isactive_idx ON rooms_81 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_82 (CONSTRAINT rooms_82_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_82_objectid_idx ON rooms_82 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_82_roomtype_idx ON rooms_82 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_82_startdate_idx ON rooms_82 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_82_enddate_idx ON rooms_82 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_82_isactual_idx ON rooms_82 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_82_isactive_idx ON rooms_82 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_83 (CONSTRAINT rooms_83_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_83_objectid_idx ON rooms_83 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_83_roomtype_idx ON rooms_83 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_83_startdate_idx ON rooms_83 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_83_enddate_idx ON rooms_83 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_83_isactual_idx ON rooms_83 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_83_isactive_idx ON rooms_83 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_84 (CONSTRAINT rooms_84_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_84_objectid_idx ON rooms_84 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_84_roomtype_idx ON rooms_84 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_84_startdate_idx ON rooms_84 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_84_enddate_idx ON rooms_84 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_84_isactual_idx ON rooms_84 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_84_isactive_idx ON rooms_84 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_85 (CONSTRAINT rooms_85_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_85_objectid_idx ON rooms_85 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_85_roomtype_idx ON rooms_85 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_85_startdate_idx ON rooms_85 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_85_enddate_idx ON rooms_85 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_85_isactual_idx ON rooms_85 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_85_isactive_idx ON rooms_85 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_86 (CONSTRAINT rooms_86_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_86_objectid_idx ON rooms_86 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_86_roomtype_idx ON rooms_86 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_86_startdate_idx ON rooms_86 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_86_enddate_idx ON rooms_86 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_86_isactual_idx ON rooms_86 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_86_isactive_idx ON rooms_86 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_87 (CONSTRAINT rooms_87_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_87_objectid_idx ON rooms_87 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_87_roomtype_idx ON rooms_87 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_87_startdate_idx ON rooms_87 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_87_enddate_idx ON rooms_87 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_87_isactual_idx ON rooms_87 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_87_isactive_idx ON rooms_87 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_88 (CONSTRAINT rooms_88_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_88_objectid_idx ON rooms_88 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_88_roomtype_idx ON rooms_88 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_88_startdate_idx ON rooms_88 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_88_enddate_idx ON rooms_88 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_88_isactual_idx ON rooms_88 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_88_isactive_idx ON rooms_88 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_89 (CONSTRAINT rooms_89_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_89_objectid_idx ON rooms_89 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_89_roomtype_idx ON rooms_89 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_89_startdate_idx ON rooms_89 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_89_enddate_idx ON rooms_89 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_89_isactual_idx ON rooms_89 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_89_isactive_idx ON rooms_89 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_90 (CONSTRAINT rooms_90_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_90_objectid_idx ON rooms_90 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_90_roomtype_idx ON rooms_90 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_90_startdate_idx ON rooms_90 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_90_enddate_idx ON rooms_90 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_90_isactual_idx ON rooms_90 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_90_isactive_idx ON rooms_90 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_91 (CONSTRAINT rooms_91_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_91_objectid_idx ON rooms_91 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_91_roomtype_idx ON rooms_91 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_91_startdate_idx ON rooms_91 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_91_enddate_idx ON rooms_91 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_91_isactual_idx ON rooms_91 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_91_isactive_idx ON rooms_91 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_92 (CONSTRAINT rooms_92_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_92_objectid_idx ON rooms_92 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_92_roomtype_idx ON rooms_92 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_92_startdate_idx ON rooms_92 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_92_enddate_idx ON rooms_92 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_92_isactual_idx ON rooms_92 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_92_isactive_idx ON rooms_92 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_93 (CONSTRAINT rooms_93_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_93_objectid_idx ON rooms_93 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_93_roomtype_idx ON rooms_93 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_93_startdate_idx ON rooms_93 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_93_enddate_idx ON rooms_93 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_93_isactual_idx ON rooms_93 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_93_isactive_idx ON rooms_93 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_94 (CONSTRAINT rooms_94_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_94_objectid_idx ON rooms_94 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_94_roomtype_idx ON rooms_94 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_94_startdate_idx ON rooms_94 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_94_enddate_idx ON rooms_94 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_94_isactual_idx ON rooms_94 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_94_isactive_idx ON rooms_94 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_95 (CONSTRAINT rooms_95_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_95_objectid_idx ON rooms_95 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_95_roomtype_idx ON rooms_95 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_95_startdate_idx ON rooms_95 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_95_enddate_idx ON rooms_95 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_95_isactual_idx ON rooms_95 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_95_isactive_idx ON rooms_95 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_96 (CONSTRAINT rooms_96_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_96_objectid_idx ON rooms_96 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_96_roomtype_idx ON rooms_96 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_96_startdate_idx ON rooms_96 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_96_enddate_idx ON rooms_96 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_96_isactual_idx ON rooms_96 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_96_isactive_idx ON rooms_96 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_97 (CONSTRAINT rooms_97_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_97_objectid_idx ON rooms_97 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_97_roomtype_idx ON rooms_97 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_97_startdate_idx ON rooms_97 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_97_enddate_idx ON rooms_97 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_97_isactual_idx ON rooms_97 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_97_isactive_idx ON rooms_97 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_98 (CONSTRAINT rooms_98_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_98_objectid_idx ON rooms_98 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_98_roomtype_idx ON rooms_98 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_98_startdate_idx ON rooms_98 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_98_enddate_idx ON rooms_98 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_98_isactual_idx ON rooms_98 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_98_isactive_idx ON rooms_98 USING btree (isactive);
CREATE TABLE IF NOT EXISTS rooms_99 (CONSTRAINT rooms_99_pkey PRIMARY KEY (id)) INHERITS (rooms);
CREATE INDEX IF NOT EXISTS rooms_99_objectid_idx ON rooms_99 USING btree (objectid);
CREATE INDEX IF NOT EXISTS rooms_99_roomtype_idx ON rooms_99 USING btree (roomtype);
CREATE INDEX IF NOT EXISTS rooms_99_startdate_idx ON rooms_99 USING btree (startdate);
CREATE INDEX IF NOT EXISTS rooms_99_enddate_idx ON rooms_99 USING btree (enddate);
CREATE INDEX IF NOT EXISTS rooms_99_isactual_idx ON rooms_99 USING btree (isactual);
CREATE INDEX IF NOT EXISTS rooms_99_isactive_idx ON rooms_99 USING btree (isactive);
