CREATE TABLE IF NOT EXISTS steads (
  id INT NOT NULL PRIMARY KEY,
  objectid INT NOT NULL,
  objectguid UUID NOT NULL,
  changeid INT NOT NULL,
  number VARCHAR(250) NOT NULL,
  opertypeid VARCHAR(2) NOT NULL,
  previd INT,
  nextid INT,
  updatedate DATE NOT NULL,
  startdate DATE NOT NULL,
  enddate DATE NOT NULL,
  isactual SMALLINT NOT NULL,
  isactive SMALLINT NOT NULL
);
COMMENT ON TABLE steads IS 'Сведения по земельным участкам';
COMMENT ON COLUMN steads.id IS 'Уникальный идентификатор записи. Ключевое поле';
COMMENT ON COLUMN steads.objectid IS 'Глобальный уникальный идентификатор объекта типа INTEGER';
COMMENT ON COLUMN steads.objectguid IS 'Глобальный уникальный идентификатор адресного объекта типа UUID';
COMMENT ON COLUMN steads.changeid IS 'ID изменившей транзакции';
COMMENT ON COLUMN steads.number IS 'Номер земельного участка';
COMMENT ON COLUMN steads.opertypeid IS 'Статус действия над записью – причина появления записи';
COMMENT ON COLUMN steads.previd IS 'Идентификатор записи связывания с предыдущей исторической записью';
COMMENT ON COLUMN steads.nextid IS 'Идентификатор записи связывания с последующей исторической записью';
COMMENT ON COLUMN steads.updatedate IS 'Дата внесения (обновления) записи';
COMMENT ON COLUMN steads.startdate IS 'Начало действия записи';
COMMENT ON COLUMN steads.enddate IS 'Окончание действия записи';
COMMENT ON COLUMN steads.isactual IS 'Статус актуальности адресного объекта ФИАС';
COMMENT ON COLUMN steads.isactive IS 'Признак действующего адресного объекта';
CREATE INDEX IF NOT EXISTS steads_objectid_idx ON steads USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_startdate_idx ON steads USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_enddate_idx ON steads USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_isactual_idx ON steads USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_isactive_idx ON steads USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_01 (CONSTRAINT steads_01_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_01_objectid_idx ON steads_01 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_01_startdate_idx ON steads_01 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_01_enddate_idx ON steads_01 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_01_isactual_idx ON steads_01 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_01_isactive_idx ON steads_01 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_02 (CONSTRAINT steads_02_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_02_objectid_idx ON steads_02 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_02_startdate_idx ON steads_02 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_02_enddate_idx ON steads_02 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_02_isactual_idx ON steads_02 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_02_isactive_idx ON steads_02 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_03 (CONSTRAINT steads_03_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_03_objectid_idx ON steads_03 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_03_startdate_idx ON steads_03 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_03_enddate_idx ON steads_03 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_03_isactual_idx ON steads_03 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_03_isactive_idx ON steads_03 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_04 (CONSTRAINT steads_04_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_04_objectid_idx ON steads_04 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_04_startdate_idx ON steads_04 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_04_enddate_idx ON steads_04 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_04_isactual_idx ON steads_04 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_04_isactive_idx ON steads_04 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_05 (CONSTRAINT steads_05_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_05_objectid_idx ON steads_05 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_05_startdate_idx ON steads_05 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_05_enddate_idx ON steads_05 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_05_isactual_idx ON steads_05 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_05_isactive_idx ON steads_05 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_06 (CONSTRAINT steads_06_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_06_objectid_idx ON steads_06 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_06_startdate_idx ON steads_06 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_06_enddate_idx ON steads_06 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_06_isactual_idx ON steads_06 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_06_isactive_idx ON steads_06 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_07 (CONSTRAINT steads_07_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_07_objectid_idx ON steads_07 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_07_startdate_idx ON steads_07 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_07_enddate_idx ON steads_07 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_07_isactual_idx ON steads_07 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_07_isactive_idx ON steads_07 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_08 (CONSTRAINT steads_08_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_08_objectid_idx ON steads_08 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_08_startdate_idx ON steads_08 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_08_enddate_idx ON steads_08 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_08_isactual_idx ON steads_08 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_08_isactive_idx ON steads_08 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_09 (CONSTRAINT steads_09_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_09_objectid_idx ON steads_09 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_09_startdate_idx ON steads_09 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_09_enddate_idx ON steads_09 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_09_isactual_idx ON steads_09 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_09_isactive_idx ON steads_09 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_10 (CONSTRAINT steads_10_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_10_objectid_idx ON steads_10 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_10_startdate_idx ON steads_10 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_10_enddate_idx ON steads_10 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_10_isactual_idx ON steads_10 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_10_isactive_idx ON steads_10 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_11 (CONSTRAINT steads_11_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_11_objectid_idx ON steads_11 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_11_startdate_idx ON steads_11 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_11_enddate_idx ON steads_11 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_11_isactual_idx ON steads_11 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_11_isactive_idx ON steads_11 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_12 (CONSTRAINT steads_12_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_12_objectid_idx ON steads_12 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_12_startdate_idx ON steads_12 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_12_enddate_idx ON steads_12 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_12_isactual_idx ON steads_12 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_12_isactive_idx ON steads_12 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_13 (CONSTRAINT steads_13_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_13_objectid_idx ON steads_13 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_13_startdate_idx ON steads_13 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_13_enddate_idx ON steads_13 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_13_isactual_idx ON steads_13 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_13_isactive_idx ON steads_13 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_14 (CONSTRAINT steads_14_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_14_objectid_idx ON steads_14 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_14_startdate_idx ON steads_14 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_14_enddate_idx ON steads_14 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_14_isactual_idx ON steads_14 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_14_isactive_idx ON steads_14 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_15 (CONSTRAINT steads_15_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_15_objectid_idx ON steads_15 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_15_startdate_idx ON steads_15 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_15_enddate_idx ON steads_15 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_15_isactual_idx ON steads_15 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_15_isactive_idx ON steads_15 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_16 (CONSTRAINT steads_16_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_16_objectid_idx ON steads_16 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_16_startdate_idx ON steads_16 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_16_enddate_idx ON steads_16 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_16_isactual_idx ON steads_16 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_16_isactive_idx ON steads_16 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_17 (CONSTRAINT steads_17_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_17_objectid_idx ON steads_17 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_17_startdate_idx ON steads_17 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_17_enddate_idx ON steads_17 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_17_isactual_idx ON steads_17 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_17_isactive_idx ON steads_17 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_18 (CONSTRAINT steads_18_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_18_objectid_idx ON steads_18 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_18_startdate_idx ON steads_18 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_18_enddate_idx ON steads_18 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_18_isactual_idx ON steads_18 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_18_isactive_idx ON steads_18 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_19 (CONSTRAINT steads_19_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_19_objectid_idx ON steads_19 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_19_startdate_idx ON steads_19 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_19_enddate_idx ON steads_19 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_19_isactual_idx ON steads_19 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_19_isactive_idx ON steads_19 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_20 (CONSTRAINT steads_20_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_20_objectid_idx ON steads_20 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_20_startdate_idx ON steads_20 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_20_enddate_idx ON steads_20 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_20_isactual_idx ON steads_20 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_20_isactive_idx ON steads_20 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_21 (CONSTRAINT steads_21_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_21_objectid_idx ON steads_21 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_21_startdate_idx ON steads_21 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_21_enddate_idx ON steads_21 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_21_isactual_idx ON steads_21 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_21_isactive_idx ON steads_21 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_22 (CONSTRAINT steads_22_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_22_objectid_idx ON steads_22 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_22_startdate_idx ON steads_22 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_22_enddate_idx ON steads_22 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_22_isactual_idx ON steads_22 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_22_isactive_idx ON steads_22 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_23 (CONSTRAINT steads_23_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_23_objectid_idx ON steads_23 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_23_startdate_idx ON steads_23 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_23_enddate_idx ON steads_23 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_23_isactual_idx ON steads_23 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_23_isactive_idx ON steads_23 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_24 (CONSTRAINT steads_24_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_24_objectid_idx ON steads_24 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_24_startdate_idx ON steads_24 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_24_enddate_idx ON steads_24 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_24_isactual_idx ON steads_24 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_24_isactive_idx ON steads_24 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_25 (CONSTRAINT steads_25_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_25_objectid_idx ON steads_25 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_25_startdate_idx ON steads_25 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_25_enddate_idx ON steads_25 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_25_isactual_idx ON steads_25 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_25_isactive_idx ON steads_25 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_26 (CONSTRAINT steads_26_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_26_objectid_idx ON steads_26 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_26_startdate_idx ON steads_26 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_26_enddate_idx ON steads_26 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_26_isactual_idx ON steads_26 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_26_isactive_idx ON steads_26 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_27 (CONSTRAINT steads_27_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_27_objectid_idx ON steads_27 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_27_startdate_idx ON steads_27 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_27_enddate_idx ON steads_27 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_27_isactual_idx ON steads_27 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_27_isactive_idx ON steads_27 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_28 (CONSTRAINT steads_28_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_28_objectid_idx ON steads_28 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_28_startdate_idx ON steads_28 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_28_enddate_idx ON steads_28 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_28_isactual_idx ON steads_28 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_28_isactive_idx ON steads_28 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_29 (CONSTRAINT steads_29_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_29_objectid_idx ON steads_29 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_29_startdate_idx ON steads_29 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_29_enddate_idx ON steads_29 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_29_isactual_idx ON steads_29 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_29_isactive_idx ON steads_29 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_30 (CONSTRAINT steads_30_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_30_objectid_idx ON steads_30 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_30_startdate_idx ON steads_30 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_30_enddate_idx ON steads_30 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_30_isactual_idx ON steads_30 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_30_isactive_idx ON steads_30 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_31 (CONSTRAINT steads_31_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_31_objectid_idx ON steads_31 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_31_startdate_idx ON steads_31 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_31_enddate_idx ON steads_31 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_31_isactual_idx ON steads_31 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_31_isactive_idx ON steads_31 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_32 (CONSTRAINT steads_32_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_32_objectid_idx ON steads_32 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_32_startdate_idx ON steads_32 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_32_enddate_idx ON steads_32 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_32_isactual_idx ON steads_32 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_32_isactive_idx ON steads_32 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_33 (CONSTRAINT steads_33_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_33_objectid_idx ON steads_33 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_33_startdate_idx ON steads_33 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_33_enddate_idx ON steads_33 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_33_isactual_idx ON steads_33 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_33_isactive_idx ON steads_33 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_34 (CONSTRAINT steads_34_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_34_objectid_idx ON steads_34 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_34_startdate_idx ON steads_34 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_34_enddate_idx ON steads_34 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_34_isactual_idx ON steads_34 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_34_isactive_idx ON steads_34 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_35 (CONSTRAINT steads_35_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_35_objectid_idx ON steads_35 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_35_startdate_idx ON steads_35 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_35_enddate_idx ON steads_35 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_35_isactual_idx ON steads_35 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_35_isactive_idx ON steads_35 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_36 (CONSTRAINT steads_36_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_36_objectid_idx ON steads_36 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_36_startdate_idx ON steads_36 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_36_enddate_idx ON steads_36 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_36_isactual_idx ON steads_36 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_36_isactive_idx ON steads_36 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_37 (CONSTRAINT steads_37_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_37_objectid_idx ON steads_37 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_37_startdate_idx ON steads_37 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_37_enddate_idx ON steads_37 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_37_isactual_idx ON steads_37 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_37_isactive_idx ON steads_37 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_38 (CONSTRAINT steads_38_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_38_objectid_idx ON steads_38 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_38_startdate_idx ON steads_38 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_38_enddate_idx ON steads_38 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_38_isactual_idx ON steads_38 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_38_isactive_idx ON steads_38 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_39 (CONSTRAINT steads_39_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_39_objectid_idx ON steads_39 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_39_startdate_idx ON steads_39 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_39_enddate_idx ON steads_39 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_39_isactual_idx ON steads_39 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_39_isactive_idx ON steads_39 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_40 (CONSTRAINT steads_40_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_40_objectid_idx ON steads_40 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_40_startdate_idx ON steads_40 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_40_enddate_idx ON steads_40 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_40_isactual_idx ON steads_40 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_40_isactive_idx ON steads_40 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_41 (CONSTRAINT steads_41_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_41_objectid_idx ON steads_41 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_41_startdate_idx ON steads_41 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_41_enddate_idx ON steads_41 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_41_isactual_idx ON steads_41 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_41_isactive_idx ON steads_41 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_42 (CONSTRAINT steads_42_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_42_objectid_idx ON steads_42 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_42_startdate_idx ON steads_42 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_42_enddate_idx ON steads_42 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_42_isactual_idx ON steads_42 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_42_isactive_idx ON steads_42 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_43 (CONSTRAINT steads_43_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_43_objectid_idx ON steads_43 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_43_startdate_idx ON steads_43 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_43_enddate_idx ON steads_43 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_43_isactual_idx ON steads_43 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_43_isactive_idx ON steads_43 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_44 (CONSTRAINT steads_44_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_44_objectid_idx ON steads_44 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_44_startdate_idx ON steads_44 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_44_enddate_idx ON steads_44 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_44_isactual_idx ON steads_44 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_44_isactive_idx ON steads_44 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_45 (CONSTRAINT steads_45_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_45_objectid_idx ON steads_45 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_45_startdate_idx ON steads_45 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_45_enddate_idx ON steads_45 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_45_isactual_idx ON steads_45 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_45_isactive_idx ON steads_45 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_46 (CONSTRAINT steads_46_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_46_objectid_idx ON steads_46 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_46_startdate_idx ON steads_46 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_46_enddate_idx ON steads_46 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_46_isactual_idx ON steads_46 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_46_isactive_idx ON steads_46 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_47 (CONSTRAINT steads_47_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_47_objectid_idx ON steads_47 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_47_startdate_idx ON steads_47 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_47_enddate_idx ON steads_47 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_47_isactual_idx ON steads_47 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_47_isactive_idx ON steads_47 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_48 (CONSTRAINT steads_48_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_48_objectid_idx ON steads_48 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_48_startdate_idx ON steads_48 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_48_enddate_idx ON steads_48 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_48_isactual_idx ON steads_48 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_48_isactive_idx ON steads_48 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_49 (CONSTRAINT steads_49_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_49_objectid_idx ON steads_49 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_49_startdate_idx ON steads_49 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_49_enddate_idx ON steads_49 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_49_isactual_idx ON steads_49 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_49_isactive_idx ON steads_49 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_50 (CONSTRAINT steads_50_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_50_objectid_idx ON steads_50 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_50_startdate_idx ON steads_50 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_50_enddate_idx ON steads_50 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_50_isactual_idx ON steads_50 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_50_isactive_idx ON steads_50 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_51 (CONSTRAINT steads_51_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_51_objectid_idx ON steads_51 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_51_startdate_idx ON steads_51 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_51_enddate_idx ON steads_51 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_51_isactual_idx ON steads_51 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_51_isactive_idx ON steads_51 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_52 (CONSTRAINT steads_52_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_52_objectid_idx ON steads_52 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_52_startdate_idx ON steads_52 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_52_enddate_idx ON steads_52 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_52_isactual_idx ON steads_52 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_52_isactive_idx ON steads_52 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_53 (CONSTRAINT steads_53_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_53_objectid_idx ON steads_53 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_53_startdate_idx ON steads_53 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_53_enddate_idx ON steads_53 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_53_isactual_idx ON steads_53 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_53_isactive_idx ON steads_53 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_54 (CONSTRAINT steads_54_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_54_objectid_idx ON steads_54 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_54_startdate_idx ON steads_54 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_54_enddate_idx ON steads_54 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_54_isactual_idx ON steads_54 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_54_isactive_idx ON steads_54 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_55 (CONSTRAINT steads_55_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_55_objectid_idx ON steads_55 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_55_startdate_idx ON steads_55 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_55_enddate_idx ON steads_55 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_55_isactual_idx ON steads_55 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_55_isactive_idx ON steads_55 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_56 (CONSTRAINT steads_56_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_56_objectid_idx ON steads_56 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_56_startdate_idx ON steads_56 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_56_enddate_idx ON steads_56 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_56_isactual_idx ON steads_56 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_56_isactive_idx ON steads_56 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_57 (CONSTRAINT steads_57_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_57_objectid_idx ON steads_57 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_57_startdate_idx ON steads_57 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_57_enddate_idx ON steads_57 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_57_isactual_idx ON steads_57 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_57_isactive_idx ON steads_57 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_58 (CONSTRAINT steads_58_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_58_objectid_idx ON steads_58 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_58_startdate_idx ON steads_58 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_58_enddate_idx ON steads_58 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_58_isactual_idx ON steads_58 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_58_isactive_idx ON steads_58 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_59 (CONSTRAINT steads_59_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_59_objectid_idx ON steads_59 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_59_startdate_idx ON steads_59 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_59_enddate_idx ON steads_59 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_59_isactual_idx ON steads_59 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_59_isactive_idx ON steads_59 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_60 (CONSTRAINT steads_60_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_60_objectid_idx ON steads_60 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_60_startdate_idx ON steads_60 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_60_enddate_idx ON steads_60 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_60_isactual_idx ON steads_60 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_60_isactive_idx ON steads_60 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_61 (CONSTRAINT steads_61_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_61_objectid_idx ON steads_61 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_61_startdate_idx ON steads_61 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_61_enddate_idx ON steads_61 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_61_isactual_idx ON steads_61 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_61_isactive_idx ON steads_61 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_62 (CONSTRAINT steads_62_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_62_objectid_idx ON steads_62 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_62_startdate_idx ON steads_62 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_62_enddate_idx ON steads_62 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_62_isactual_idx ON steads_62 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_62_isactive_idx ON steads_62 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_63 (CONSTRAINT steads_63_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_63_objectid_idx ON steads_63 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_63_startdate_idx ON steads_63 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_63_enddate_idx ON steads_63 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_63_isactual_idx ON steads_63 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_63_isactive_idx ON steads_63 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_64 (CONSTRAINT steads_64_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_64_objectid_idx ON steads_64 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_64_startdate_idx ON steads_64 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_64_enddate_idx ON steads_64 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_64_isactual_idx ON steads_64 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_64_isactive_idx ON steads_64 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_65 (CONSTRAINT steads_65_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_65_objectid_idx ON steads_65 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_65_startdate_idx ON steads_65 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_65_enddate_idx ON steads_65 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_65_isactual_idx ON steads_65 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_65_isactive_idx ON steads_65 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_66 (CONSTRAINT steads_66_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_66_objectid_idx ON steads_66 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_66_startdate_idx ON steads_66 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_66_enddate_idx ON steads_66 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_66_isactual_idx ON steads_66 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_66_isactive_idx ON steads_66 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_67 (CONSTRAINT steads_67_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_67_objectid_idx ON steads_67 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_67_startdate_idx ON steads_67 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_67_enddate_idx ON steads_67 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_67_isactual_idx ON steads_67 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_67_isactive_idx ON steads_67 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_68 (CONSTRAINT steads_68_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_68_objectid_idx ON steads_68 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_68_startdate_idx ON steads_68 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_68_enddate_idx ON steads_68 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_68_isactual_idx ON steads_68 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_68_isactive_idx ON steads_68 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_69 (CONSTRAINT steads_69_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_69_objectid_idx ON steads_69 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_69_startdate_idx ON steads_69 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_69_enddate_idx ON steads_69 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_69_isactual_idx ON steads_69 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_69_isactive_idx ON steads_69 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_70 (CONSTRAINT steads_70_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_70_objectid_idx ON steads_70 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_70_startdate_idx ON steads_70 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_70_enddate_idx ON steads_70 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_70_isactual_idx ON steads_70 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_70_isactive_idx ON steads_70 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_71 (CONSTRAINT steads_71_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_71_objectid_idx ON steads_71 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_71_startdate_idx ON steads_71 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_71_enddate_idx ON steads_71 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_71_isactual_idx ON steads_71 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_71_isactive_idx ON steads_71 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_72 (CONSTRAINT steads_72_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_72_objectid_idx ON steads_72 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_72_startdate_idx ON steads_72 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_72_enddate_idx ON steads_72 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_72_isactual_idx ON steads_72 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_72_isactive_idx ON steads_72 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_73 (CONSTRAINT steads_73_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_73_objectid_idx ON steads_73 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_73_startdate_idx ON steads_73 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_73_enddate_idx ON steads_73 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_73_isactual_idx ON steads_73 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_73_isactive_idx ON steads_73 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_74 (CONSTRAINT steads_74_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_74_objectid_idx ON steads_74 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_74_startdate_idx ON steads_74 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_74_enddate_idx ON steads_74 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_74_isactual_idx ON steads_74 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_74_isactive_idx ON steads_74 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_75 (CONSTRAINT steads_75_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_75_objectid_idx ON steads_75 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_75_startdate_idx ON steads_75 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_75_enddate_idx ON steads_75 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_75_isactual_idx ON steads_75 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_75_isactive_idx ON steads_75 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_76 (CONSTRAINT steads_76_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_76_objectid_idx ON steads_76 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_76_startdate_idx ON steads_76 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_76_enddate_idx ON steads_76 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_76_isactual_idx ON steads_76 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_76_isactive_idx ON steads_76 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_77 (CONSTRAINT steads_77_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_77_objectid_idx ON steads_77 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_77_startdate_idx ON steads_77 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_77_enddate_idx ON steads_77 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_77_isactual_idx ON steads_77 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_77_isactive_idx ON steads_77 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_78 (CONSTRAINT steads_78_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_78_objectid_idx ON steads_78 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_78_startdate_idx ON steads_78 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_78_enddate_idx ON steads_78 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_78_isactual_idx ON steads_78 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_78_isactive_idx ON steads_78 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_79 (CONSTRAINT steads_79_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_79_objectid_idx ON steads_79 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_79_startdate_idx ON steads_79 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_79_enddate_idx ON steads_79 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_79_isactual_idx ON steads_79 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_79_isactive_idx ON steads_79 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_80 (CONSTRAINT steads_80_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_80_objectid_idx ON steads_80 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_80_startdate_idx ON steads_80 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_80_enddate_idx ON steads_80 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_80_isactual_idx ON steads_80 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_80_isactive_idx ON steads_80 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_81 (CONSTRAINT steads_81_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_81_objectid_idx ON steads_81 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_81_startdate_idx ON steads_81 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_81_enddate_idx ON steads_81 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_81_isactual_idx ON steads_81 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_81_isactive_idx ON steads_81 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_82 (CONSTRAINT steads_82_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_82_objectid_idx ON steads_82 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_82_startdate_idx ON steads_82 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_82_enddate_idx ON steads_82 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_82_isactual_idx ON steads_82 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_82_isactive_idx ON steads_82 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_83 (CONSTRAINT steads_83_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_83_objectid_idx ON steads_83 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_83_startdate_idx ON steads_83 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_83_enddate_idx ON steads_83 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_83_isactual_idx ON steads_83 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_83_isactive_idx ON steads_83 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_84 (CONSTRAINT steads_84_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_84_objectid_idx ON steads_84 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_84_startdate_idx ON steads_84 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_84_enddate_idx ON steads_84 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_84_isactual_idx ON steads_84 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_84_isactive_idx ON steads_84 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_85 (CONSTRAINT steads_85_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_85_objectid_idx ON steads_85 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_85_startdate_idx ON steads_85 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_85_enddate_idx ON steads_85 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_85_isactual_idx ON steads_85 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_85_isactive_idx ON steads_85 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_86 (CONSTRAINT steads_86_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_86_objectid_idx ON steads_86 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_86_startdate_idx ON steads_86 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_86_enddate_idx ON steads_86 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_86_isactual_idx ON steads_86 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_86_isactive_idx ON steads_86 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_87 (CONSTRAINT steads_87_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_87_objectid_idx ON steads_87 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_87_startdate_idx ON steads_87 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_87_enddate_idx ON steads_87 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_87_isactual_idx ON steads_87 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_87_isactive_idx ON steads_87 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_88 (CONSTRAINT steads_88_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_88_objectid_idx ON steads_88 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_88_startdate_idx ON steads_88 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_88_enddate_idx ON steads_88 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_88_isactual_idx ON steads_88 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_88_isactive_idx ON steads_88 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_89 (CONSTRAINT steads_89_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_89_objectid_idx ON steads_89 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_89_startdate_idx ON steads_89 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_89_enddate_idx ON steads_89 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_89_isactual_idx ON steads_89 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_89_isactive_idx ON steads_89 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_90 (CONSTRAINT steads_90_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_90_objectid_idx ON steads_90 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_90_startdate_idx ON steads_90 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_90_enddate_idx ON steads_90 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_90_isactual_idx ON steads_90 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_90_isactive_idx ON steads_90 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_91 (CONSTRAINT steads_91_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_91_objectid_idx ON steads_91 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_91_startdate_idx ON steads_91 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_91_enddate_idx ON steads_91 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_91_isactual_idx ON steads_91 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_91_isactive_idx ON steads_91 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_92 (CONSTRAINT steads_92_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_92_objectid_idx ON steads_92 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_92_startdate_idx ON steads_92 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_92_enddate_idx ON steads_92 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_92_isactual_idx ON steads_92 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_92_isactive_idx ON steads_92 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_93 (CONSTRAINT steads_93_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_93_objectid_idx ON steads_93 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_93_startdate_idx ON steads_93 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_93_enddate_idx ON steads_93 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_93_isactual_idx ON steads_93 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_93_isactive_idx ON steads_93 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_94 (CONSTRAINT steads_94_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_94_objectid_idx ON steads_94 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_94_startdate_idx ON steads_94 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_94_enddate_idx ON steads_94 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_94_isactual_idx ON steads_94 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_94_isactive_idx ON steads_94 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_95 (CONSTRAINT steads_95_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_95_objectid_idx ON steads_95 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_95_startdate_idx ON steads_95 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_95_enddate_idx ON steads_95 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_95_isactual_idx ON steads_95 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_95_isactive_idx ON steads_95 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_96 (CONSTRAINT steads_96_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_96_objectid_idx ON steads_96 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_96_startdate_idx ON steads_96 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_96_enddate_idx ON steads_96 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_96_isactual_idx ON steads_96 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_96_isactive_idx ON steads_96 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_97 (CONSTRAINT steads_97_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_97_objectid_idx ON steads_97 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_97_startdate_idx ON steads_97 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_97_enddate_idx ON steads_97 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_97_isactual_idx ON steads_97 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_97_isactive_idx ON steads_97 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_98 (CONSTRAINT steads_98_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_98_objectid_idx ON steads_98 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_98_startdate_idx ON steads_98 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_98_enddate_idx ON steads_98 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_98_isactual_idx ON steads_98 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_98_isactive_idx ON steads_98 USING btree (isactive);
CREATE TABLE IF NOT EXISTS steads_99 (CONSTRAINT steads_99_pkey PRIMARY KEY (id)) INHERITS (steads);
CREATE INDEX IF NOT EXISTS steads_99_objectid_idx ON steads_99 USING btree (objectid);
CREATE INDEX IF NOT EXISTS steads_99_startdate_idx ON steads_99 USING btree (startdate);
CREATE INDEX IF NOT EXISTS steads_99_enddate_idx ON steads_99 USING btree (enddate);
CREATE INDEX IF NOT EXISTS steads_99_isactual_idx ON steads_99 USING btree (isactual);
CREATE INDEX IF NOT EXISTS steads_99_isactive_idx ON steads_99 USING btree (isactive);
